// ════════════════════════════════════════════════════════════════════════════
// PHASE 5ad — APPEND TO data.js
// Civilizations 521–550
// ════════════════════════════════════════════════════════════════════════════
//
// INSTRUCTIONS (owner):
//   1. Open your local data.js
//   2. Find the very last closing  ];  at the bottom
//   3. Replace that  ];  with a comma, then paste ALL lines below
//      (these entries already end with the correct closing bracket)
//
// ════════════════════════════════════════════════════════════════════════════

// ── PHASE 5ad — Civilizations 521–550 ─────────────────────────────────────
// Append to CIVS array in data.js — APPEND-ONLY

  { id:521, n:"Mississippian Culture — Moundville Phase I", r:"Americas", t:"confirmed",
    s:1050, e:1250, p:10000, lang:"muskogean", gov:"chiefdom",
    d:"The Phase I occupation of Moundville (~1050–1250 CE) represents the founding and rapid growth of what would become the second-largest Mississippian centre in North America, a period of intense mound construction, population aggregation, and political centralisation in the Black Warrior Valley. Timothy Pauketat's research has documented the extraordinary speed of Moundville's emergence — within a few generations, a dispersed agricultural population transformed into a nucleated urban centre with a clear site hierarchy, suggesting a top-down political reorganisation rather than gradual organic growth. The Phase I community built the initial platform mounds, established the central plaza, and began the construction of the defensive palisade that enclosed the ceremonial precinct. The founding of Moundville may have been associated with a specific political or religious innovation — possibly the adoption of Cahokia-derived cosmological and political ideas — that gave its founders sufficient ideological authority to aggregate and direct large-scale collective labour." },

  { id:522, n:"Sican / Lambayeque Culture", r:"Americas", t:"confirmed",
    s:750, e:1375, p:200000, lang:"mochica", gov:"theocracy",
    d:"The Sican (Lambayeque) culture of northern coastal Peru (~750–1375 CE) was one of the great goldworking civilisations of the ancient Americas, producing gold and tumbaga (gold-copper alloy) objects of extraordinary technical sophistication — including the famous Tumi ceremonial knives and funerary masks — that define a distinctive artistic tradition centred on the fanged deity figure known as the Sican Lord. The culture's founder is identified in oral tradition as Naymlap, a semi-divine ruler who arrived by sea from the north with a fleet of balsa rafts, an origin narrative that encodes both the Sican elite's claim to exotic, supernatural origins and possibly genuine memory of maritime contact. The major Sican ceremonial centre at Batán Grande features massive adobe truncated pyramids that served as royal burial facilities; one royal tomb excavated by Izumi Shimada contained a inverted male burial surrounded by the remains of sacrificed women, enormous quantities of gold objects, and arsenical bronze tools. The Sican were conquered by the Chimú around 1375 CE." },

  { id:523, n:"Moche Civilisation", r:"Americas", t:"confirmed",
    s:100, e:800, p:60000, lang:"mochica", gov:"theocracy",
    d:"The Moche civilisation of northern coastal Peru (~100–800 CE) is renowned for producing the most naturalistically expressive ceramic art of any pre-Columbian Andean culture — portrait vessels capturing individual human faces with psychological specificity not seen elsewhere in the ancient Americas, and narrative scenes of warfare, sacrifice, and erotic mythology executed with extraordinary technical and artistic skill. The Moche built massive adobe platform complexes — the Huaca del Sol and Huaca de la Luna at the capital near present-day Trujillo — using a distinctive system of brick production in which individual communities contributed marked bricks, documenting a labour taxation system. The Sacrifice Ceremony, depicted repeatedly in Moche art, was confirmed as a real ritual when excavations at the Huaca de la Luna revealed skeletal evidence of sacrificed warriors matching the iconographic sequence exactly. The Moche collapse around 800 CE, possibly triggered by a prolonged El Niño drought cycle, ended one of the most vivid artistic civilisations of the ancient world." },

  { id:524, n:"Nazca Civilisation", r:"Americas", t:"confirmed",
    s:-100, e:800, p:25000, lang:"proto-quechuan", gov:"chiefdom",
    d:"The Nazca civilisation of the southern Peruvian coastal desert (~100 BCE–800 CE) is most famous for the Nazca Lines — an extraordinary complex of geoglyphs etched into the desert pavement covering an area of approximately 450 square kilometres, including giant figures of animals (hummingbird, spider, monkey, condor), geometric shapes, and straight lines extending for kilometres with mathematical precision. The lines were created by removing the reddish surface stones to reveal the lighter ground beneath — a simple technique, but the scale and precision of execution remain remarkable. Mainstream archaeology interprets the lines as ceremonial pathways and offerings to deities, possibly associated with water and fertility rituals in an extremely arid environment. Erich von Däniken's ancient astronaut hypothesis proposed the lines as landing strips for spacecraft, a claim rejected by archaeology but enormously influential in popular culture. The Nazca also produced sophisticated polychrome pottery and an underground aqueduct system (puquios) that may still function today, distributing water across the desert landscape." },

  { id:525, n:"Tiahuanaco — Astronomical Alignment", r:"Americas", t:"debated",
    s:-15000, e:-10000, p:0, lang:"unknown", gov:"unknown",
    d:"Arthur Posnansky's monumental study Tiahuanacu: The Cradle of American Man (1945) proposed, based on astronomical analysis of the alignments of the Kalasasaya enclosure at Tiwanaku, that the monument was designed to mark the solstices and equinoxes at a date of approximately 15,000 BCE — when the obliquity of the ecliptic would have placed the sunrise and sunset at the angles encoded in the Kalasasaya's gateway positions. This would make Tiwanaku not a 500 CE construction but a monument of extraordinary antiquity, predating the Younger Dryas boundary and potentially representing one of the oldest astronomical monuments on Earth. Mainstream archaeology decisively rejects Posnansky's dating on multiple grounds: the ceramic sequences, radiocarbon dates, and architectural analysis all firmly place the monumental construction at 500–900 CE. Alternative scholars including Graham Hancock and Brien Foerster have revisited Posnansky's astronomical arguments. The debate exemplifies the difficulty of using astronomical alignment dating alone, which can produce multiple candidate dates across precessional cycles without independent corroboration." },

  { id:526, n:"Mississippian Culture — Florence Mound", r:"Americas", t:"confirmed",
    s:1100, e:1400, p:500, lang:"muskogean", gov:"chiefdom",
    d:"Florence Mound in present-day northern Alabama represents one of dozens of smaller Mississippian mound sites within the Tennessee Valley regional system, a minor ceremonial centre that participated in the exchange networks and political hierarchies of the broader Mississippian world while maintaining a primarily local agricultural community. Sites like Florence Mound are collectively more important than individually prominent sites for understanding how Mississippian civilisation actually functioned at the community level — the daily life, agricultural rhythms, and local ritual practices of the majority population who lived away from the great paramount centres. The Tennessee Valley's density of smaller Mississippian mound sites documents a landscape that was intensively occupied and politically organised across its entire length during the Mississippian period, a fact often obscured by the focus on spectacular sites like Cahokia and Moundville." },

  { id:527, n:"Paracas Culture", r:"Americas", t:"confirmed",
    s:-800, e:100, p:10000, lang:"proto-nazca", gov:"chiefdom",
    d:"The Paracas culture of the Ica region of coastal Peru (~800 BCE–100 CE) is renowned for two extraordinary achievements: the Paracas Cavernas and Paracas Necrópolis burial traditions, which preserved mummified human remains in underground chambers and elaborate textile wrappings in the hyperarid coastal desert, and the Paracas textiles themselves — considered the finest pre-Columbian textiles in the Americas, woven with thread counts exceeding modern machine-woven fabric and featuring complex mythological imagery in colours still vivid after two millennia. The Paracas mummies also document intentional cranial modification — elongated skulls achieved by binding infants' heads between boards — creating elite individuals whose skull shape visually distinguished them from commoners. Brien Foerster has controversially proposed, based on claimed DNA analysis, that some Paracas elongated skulls represent a genetically distinct population rather than artificially modified normal human skulls, a claim not accepted by mainstream physical anthropology." },

  { id:528, n:"Chavín de Huántar", r:"Americas", t:"confirmed",
    s:-900, e:-200, p:3000, lang:"proto-quechuan", gov:"theocracy",
    d:"Chavín de Huántar in the Peruvian highlands (~900–200 BCE) was the major ceremonial centre of the first pan-Andean religious tradition, a pilgrimage site whose distinctive iconographic system — the Staff God, the fanged supernatural beings, the supernatural raptors — spread across the Andean world as the Chavín Horizon and laid the visual and religious foundations for a thousand years of subsequent Andean artistic and religious development. The site itself is an extraordinary architectural achievement: a complex of interlocking stone galleries, ventilation shafts, and drainage channels built into a mountain, with a sophisticated acoustic design that created disorienting sound effects — roaring water, echoes, bass frequencies — experienced by pilgrims potentially under the influence of psychedelic San Pedro cactus. John Rick's excavations have documented the deliberate theatrical design of the Chavín experience, arguing that the site's priests used architecture, acoustics, and psychoactive substances to create overwhelming religious experiences that validated their authority." },

  { id:529, n:"Recuay Culture", r:"Americas", t:"confirmed",
    s:1, e:700, p:15000, lang:"proto-quechuan", gov:"chiefdom",
    d:"The Recuay culture of the northern Peruvian highlands (~1–700 CE) developed a distinctive sculptural and ceramic tradition in the Callejón de Huaylas valley — a high mountain corridor between the Cordillera Blanca and the Cordillera Negra — that combined kaolin white-ware ceramics with three-dimensional figurative sculpture depicting armed warriors, supernatural beings, and elite life scenes. Recuay elite burial traditions involved elaborate stone-lined tombs (chullpas) and the interment of individuals with rich grave goods including bronze weapons and distinctive negative-painted pottery. The culture's geographical position in the highland corridor placed it between the coastal Moche civilisation to the west and the highland cultures of the Andean interior, and Recuay material culture shows evidence of complex interactions — sometimes hostile, sometimes commercial — with Moche expansion into the highlands. Recuay sculptural traditions appear to have influenced subsequent highland Andean artistic traditions and may have transmitted certain iconographic elements to the later Tiwanaku-Wari horizon." },

  { id:530, n:"Valdivia Culture", r:"Americas", t:"confirmed",
    s:-3500, e:-1500, p:5000, lang:"unknown-coastal-ecuador", gov:"village",
    d:"The Valdivia culture of coastal Ecuador (~3500–1500 BCE) produced the oldest known pottery in the Americas — a discovery that fundamentally revised understanding of South American cultural development when Betty Meggers and colleagues published the finding in 1965. The early Valdivia ceramics are technically sophisticated from their first appearance, without the experimental crudeness typically associated with the invention of pottery, leading Meggers to controversially propose transpacific diffusion from the Jōmon culture of Japan — whose pottery is of similar antiquity and certain stylistic similarities. Mainstream archaeology has largely rejected the transpacific hypothesis in favour of independent invention, but the question of why early Valdivia ceramics appear so accomplished from the outset remains not fully resolved. Valdivia is also known for its distinctive female figurines — the earliest known figurative sculpture in the Americas — which may represent ancestor figures, fertility deities, or markers of social identity." },

  { id:531, n:"Norte Chico / Caral — Satellite Sites", r:"Americas", t:"confirmed",
    s:-3000, e:-1800, p:20000, lang:"unknown-coastal-peru", gov:"theocracy",
    d:"The Norte Chico civilisation of coastal Peru extended well beyond the primary site of Caral to encompass at least 30 major sites across the Supe, Pativilca, Fortaleza, and Huaura valleys — a regional civilisation of the third millennium BCE that collectively represents the earliest complex society in the Americas. Sites including Huaricanga, Pozo Santo, Miraya, and Caballete each feature monumental platform mounds, sunken circular plazas of a form unique to Norte Chico, and evidence of the coastal-inland exchange economy based on anchoveta fishing and agricultural products. The absence of warfare evidence across the entire Norte Chico cultural horizon — no defensive architecture, no weapons in burials, no skeletal trauma consistent with organised violence — is one of the most striking features of this civilisation and has led some scholars to propose that Norte Chico achieved urban complexity through economic interdependence and religious integration rather than coercive political power. Whether this represents a genuinely peaceful civilisation or merely an absence of preserved evidence for conflict remains debated." },

  { id:532, n:"Tiwanaku — Pumapunku", r:"Americas", t:"debated",
    s:-500, e:1100, p:20000, lang:"puquina", gov:"theocracy",
    d:"Pumapunku, a platform complex at the Tiwanaku site in Bolivia, contains stone blocks of a kind that have attracted intense attention from both mainstream archaeologists and alternative scholars — H-shaped andesite blocks machined to tolerances of fractions of a millimetre, with complex interlocking geometries that would be challenging even with modern tools. Brien Foerster and others in the alternative archaeology tradition argue these precision tolerances evidence advanced technology beyond what the accepted Tiwanaku date of ~500–900 CE can explain, and propose a much earlier construction date. Mainstream archaeology attributes the precision to skilled stone dressing using harder stone tools and abrasives, with radiocarbon dates for organic material associated with the construction firmly in the first millennium CE. The blocks' H-shaped profiles appear designed for interlocking structural connections, and the site shows evidence of deliberate demolition in antiquity — possibly during the political collapse of Tiwanaku — that scattered the precision-cut elements. Pumapunku remains one of the most visited and debated sites in alternative archaeology." },

  { id:533, n:"Mississippian Culture — Fatherland", r:"Americas", t:"confirmed",
    s:1250, e:1730, p:4000, lang:"natchez", gov:"theocracy",
    d:"The Fatherland site near present-day Natchez, Mississippi, was the historic capital of the Natchez Nation — the last major functioning Mississippian-tradition chiefdom encountered by European colonists in the lower Mississippi Valley, and the only one documented in sufficient ethnographic detail to reconstruct the living political and religious system of the Mississippian world. French colonial sources from the late 17th and early 18th centuries describe the Natchez political system in considerable detail: the Great Sun, a divine ruler carried on a litter and never permitted to touch the ground, whose word was law over life and death; a rigid hereditary caste system of Suns, Nobles, Honoured Men, and Stinkards; and an eternal sacred fire maintained in the temple atop the primary platform mound. When the Great Sun died, retainers were strangled to accompany him. The French destroyed the Natchez Nation in 1731 following the Natchez Revolt of 1729, ending the last intact Mississippian political system. Fatherland's occupation continuity from the prehistoric Plaquemine tradition through the historic Natchez period makes it uniquely valuable for connecting archaeology to documented living culture." },

  { id:534, n:"Mississippian Culture — Grand Village", r:"Americas", t:"confirmed",
    s:1300, e:1731, p:1500, lang:"natchez", gov:"theocracy",
    d:"Grand Village of the Natchez Indians in present-day Natchez, Mississippi, is the best-documented late Mississippian site in North America — a platform mound complex that served as the ceremonial centre of the historic Natchez Nation from approximately 1300 CE until the French destruction of the Natchez in 1731. Unlike most Mississippian sites known only through archaeology, Grand Village was observed and described in detail by French missionaries, soldiers, and colonial officials including Antoine-Simon Le Page du Pratz, whose Histoire de la Louisiane (1758) preserves the most complete account of Mississippian ceremonial life ever written. The site's mounds supported the house of the Great Sun and the temple containing the sacred fire and bone bundles of deceased Great Suns. Excavations at Grand Village have confirmed the French documentary accounts in detail, providing a uniquely powerful methodological demonstration of how ethnographic records and archaeological evidence can be used to validate and enrich each other." },

  { id:535, n:"Cahuilla / Desert Cultures — California", r:"Americas", t:"confirmed",
    s:-3000, e:1850, p:6000, lang:"uto-aztecan-cahuilla", gov:"band",
    d:"The Cahuilla and related Desert Cultures of inland southern California developed one of the most sophisticated hunter-gatherer adaptations to an arid environment in the Americas — a 5,000-year tradition of intensive resource management in the Coachella Valley, San Bernardino Mountains, and surrounding desert that supported relatively dense populations without agriculture through systematic exploitation of acorns, mesquite, pinyon pine, and desert game. Cahuilla society was organised around patrilineal clans with hereditary ritual specialists (net) and an elaborate ceremonial life including the mourning ceremony (nukmit) and the bird songs — a cycle of hundreds of linked songs encoding geographical knowledge, cosmological narratives, and historical memory transmitted across generations. The Cahuilla's intimate knowledge of desert hydrology, plant phenology, and animal behaviour constituted a sophisticated ecological science developed over millennia. Their survival through Spanish colonisation, American conquest, and the reservation system — the Cahuilla remain a federally recognised nation today — demonstrates remarkable cultural resilience." },

  { id:536, n:"Anasazi / Ancestral Puebloan — Chaco Roads", r:"Americas", t:"debated",
    s:850, e:1150, p:15000, lang:"proto-puebloan", gov:"theocracy",
    d:"The Chaco road system — a network of engineered roads radiating from Chaco Canyon across the Colorado Plateau, surveyed in detail through aerial photography and ground investigation — remains one of the most debated features of Ancestral Puebloan civilisation. The roads run in mathematically straight lines for distances of up to 60km, cutting through terrain regardless of topography, sometimes bifurcating and running in parallel without obvious functional reason. Some roads terminate at isolated great kivas or small outlier great houses; others lead to natural landscape features. The straightness, scale, and apparent non-utilitarian character of some roads has generated alternative interpretations: Pueblo oral tradition connects roads to spirit pathways; some researchers propose astronomical alignments; others see them as the material expression of a road-based cosmology in which straight paths connected the living to the ancestors. Anna Sofaer's Solstice Project has documented solar and lunar alignments at Chaco architecture that, combined with the road system, suggests a sophisticated cosmological programme integrating architecture, roads, and astronomical observation." },

  { id:537, n:"Hohokam — Snaketown", r:"Americas", t:"confirmed",
    s:300, e:1150, p:2000, lang:"uto-aztecan-proto", gov:"chiefdom",
    d:"Snaketown on the Gila River in present-day Arizona was the largest and longest-occupied Hohokam village and the archaeological type site for the Hohokam cultural sequence, excavated by Emil Haury in major campaigns in 1934–35 and 1964–65. The site's deep stratigraphy documents the full trajectory of Hohokam cultural development from the Pioneer period through the Colonial and Sedentary periods, revealing a community that maintained continuous occupation for approximately 1,500 years on the banks of the Gila River. Snaketown's canal system, ball courts, and platform mound document the full Hohokam cultural package — Mesoamerican-derived features integrated into a distinctly Sonoran Desert cultural context. The site is located on the Gila River Indian Community reservation of the Akimel O'odham (Pima) people, who consider Snaketown part of their ancestral heritage; at the O'odham community's request, the site was backfilled after Haury's 1964–65 excavation and is not open to excavation." },

  { id:538, n:"Ancestral Puebloan — Pueblo Bonito", r:"Americas", t:"confirmed",
    s:850, e:1150, p:1200, lang:"proto-puebloan", gov:"theocracy",
    d:"Pueblo Bonito in Chaco Canyon, New Mexico, is the largest and most thoroughly studied great house of the Ancestral Puebloan world — a D-shaped multi-storey structure of over 650 rooms and 37 kivas rising to four and possibly five storeys, built with a precision of stone masonry that architectural analysts have described as exceeding that of any contemporary structure in the Americas. Construction proceeded in distinct phases across more than two centuries, maintaining the overall D-plan with remarkable consistency. Despite its enormous size, Pueblo Bonito appears to have housed relatively few permanent residents — the room-to-population ratio suggests a primarily ceremonial and storage function, with most rooms used for ritual equipment, food stores, or turquoise and shell valuables. The cylinder jars found at Pueblo Bonito — residue-tested and confirmed to have held cacao — document the importation of this Mesoamerican prestige beverage from sources over 1,200km distant. Pueblo Bonito's spatial and architectural complexity continues to generate new interpretations with each generation of excavation and analysis." },

  { id:539, n:"Poverty Point — Watson Brake Complex", r:"Americas", t:"confirmed",
    s:-3500, e:-2800, p:500, lang:"unknown", gov:"band-chiefdom",
    d:"Watson Brake in present-day Louisiana — eleven earthen mounds connected by a low oval ridge, radiocarbon-dated to approximately 3500–2800 BCE — is the oldest known mound complex in North America, predating Poverty Point by 1,800 years and predating the Egyptian Old Kingdom pyramids by several centuries. Its construction by hunter-gatherers in the Lower Mississippi Valley pushes the impulse to build monumental earthworks in North America back to a period when only scattered Archaic hunter-gatherer bands occupied the region, with no agriculture, no ceramics, and no obvious surplus economy capable of supporting collective monument construction by conventional models. The Watson Brake mounds are modest in scale compared to later Poverty Point constructions, but their antiquity is extraordinary. The site was discovered and dated only in the 1990s, and its implications for models of North American cultural development are still being absorbed. Watson Brake suggests that the Lower Mississippi Valley had an exceptionally deep tradition of monumental construction that Poverty Point represents not as an anomaly but as the culmination of a much longer regional development." },

  { id:540, n:"Mississippian Culture — Toltec Mounds", r:"Americas", t:"confirmed",
    s:700, e:1050, p:3000, lang:"various-quapaw-proto", gov:"chiefdom",
    d:"Toltec Mounds in present-day Arkansas — despite its misleading name, which reflects 19th-century assumptions about Mexican connections rather than actual cultural links — is the largest Late Woodland and early Mississippian site in the Lower Mississippi Valley and an important transitional site documenting the cultural transformation from Woodland to Mississippian traditions in the region. The site features 18 mounds enclosed within an embankment, occupied primarily during the Plum Bayou culture phase (~700–1050 CE) that immediately preceded the full Mississippian fluorescence. Toltec Mounds appears to have been a major regional ceremonial centre during a formative period in the development of Mississippian civilisation, and its scale suggests it functioned as a proto-urban aggregation centre before the classic Mississippian pattern of plaza-oriented platform mound towns was fully established. The site's study has been important for understanding the transition from Woodland to Mississippian cultural patterns in the central Mississippi Valley." },

  { id:541, n:"Mississippian Culture — Winterville Phase II", r:"Americas", t:"confirmed",
    s:1200, e:1450, p:2000, lang:"various-muskogean", gov:"chiefdom",
    d:"The later phase occupation at Winterville in present-day Mississippi documents the mature development of this Lower Mississippi Valley Mississippian centre, with expanded mound construction, intensified participation in the Southeastern Ceremonial Complex exchange network, and evidence of increasing political complexity within the regional chiefdom hierarchy. Winterville's position in the Yazoo Basin placed it within a zone of exceptionally dense Mississippian settlement, where numerous mound centres competed and cooperated within a landscape that may have supported some of the highest pre-Columbian population densities east of the Mississippi River. The Yazoo Basin's extraordinarily productive alluvial soils — among the most fertile in North America — supported the agricultural surplus that underpinned the dense Mississippian settlement of this region, and the competition for control of these resources likely drove the political complexity documented at sites like Winterville throughout its Phase II occupation." },

  { id:542, n:"Paleo-Indian — Clovis Culture", r:"Americas", t:"confirmed",
    s:-13500, e:-12800, p:5000, lang:"unknown-paleo-indian", gov:"band",
    d:"The Clovis culture (~13,500–12,800 BCE) represents the earliest definitively documented widespread human occupation of North America — a distinctive lithic technology characterised by large, fluted projectile points of exceptional craftsmanship that spread across the Americas with extraordinary speed, appearing from Alaska to Patagonia within perhaps 500–1,000 years. Clovis hunters were megafauna specialists, with kill sites documenting their hunting of mammoths, mastodons, camels, horses, and giant ground sloths. The debate over whether Clovis people were responsible for the extinction of North American megafauna — the 'Pleistocene Overkill' hypothesis of Paul Martin — remains one of archaeology's most contested questions, with climate change and the Younger Dryas Impact Hypothesis as alternative or contributing explanations. The Clovis-first model — which held that Clovis represented the founding population of the Americas — has been decisively overturned by pre-Clovis sites including Monte Verde in Chile (~14,500 BCE) and Chiquihuite Cave in Mexico (~26,000 BCE), establishing that humans were in the Americas well before Clovis." },

  { id:543, n:"Paleo-Indian — Pre-Clovis Peoples", r:"Americas", t:"confirmed",
    s:-20000, e:-13500, p:2000, lang:"unknown-paleo-indian", gov:"band",
    d:"The accumulating evidence for pre-Clovis human presence in the Americas — sites including Monte Verde, Chile (~14,500 BCE), Chiquihuite Cave, Mexico (~26,000 BCE), Meadowcroft Rockshelter, Pennsylvania (~16,000 BCE), and Buttermilk Creek, Texas (~15,500 BCE) — has definitively established that humans arrived in the Americas before the Clovis culture and through routes other than the Bering Land Bridge ice-free corridor. The coastal migration hypothesis — humans following the kelp forest highway along the Pacific coast of Asia and North America by watercraft — is now the leading model for the initial peopling of the Americas, potentially predating the opening of the ice-free interior corridor. Genetic evidence supports multiple founding populations and possibly multiple entry events. Graham Hancock's America Before (2019) synthesises the pre-Clovis evidence and argues it supports a much more ancient and complex human presence in the Americas than mainstream archaeology has acknowledged, potentially extending to the time of the last glacial maximum or earlier." },

  { id:544, n:"Chinchorro Culture", r:"Americas", t:"confirmed",
    s:-7000, e:-1500, p:3000, lang:"unknown-andean-coastal", gov:"band",
    d:"The Chinchorro culture of northern Chile and southern Peru (~7000–1500 BCE) produced the oldest artificial mummies in the world — predating Egyptian mummification by approximately 2,000 years — through an elaborate mortuary process involving the complete disassembly and reconstruction of the human body: defleshing, removal of organs and brain, reinforcement of the skeleton with sticks, reconstruction of the body surface with clay, reattachment of the skin, and coating with red or black pigment. This practice was applied not only to high-status individuals but apparently across the entire community including infants and fetuses, suggesting a democratic or community-wide rather than elite mortuary tradition — a marked contrast to the elite-focused mummification of ancient Egypt. The Chinchorro people were maritime hunter-gatherers subsisting on the extraordinary productivity of the Humboldt Current, which made the Atacama coastal zone one of the richest marine environments on Earth. The impulse to elaborate mummification 7,000 years ago in a non-agricultural community has no fully satisfying cultural explanation." },

  { id:545, n:"Tiwanaku — Lake Titicaca Sacred Landscape", r:"Americas", t:"confirmed",
    s:-500, e:1000, p:100000, lang:"puquina", gov:"theocracy",
    d:"The Lake Titicaca basin as a whole constituted a sacred landscape for the Tiwanaku civilisation, with the lake itself — the world's highest navigable body of water at 3,812 metres elevation — serving as the cosmological centre of a religious system that extended across the Andean world. The Island of the Sun and the Island of the Moon within the lake were the mythological birthplace of the sun and moon in Andean cosmology, a significance that predated Tiwanaku and was subsequently adopted and amplified by the Inca. Tiwanaku's transformation of the lake's margins through raised field agriculture — converting the marshy totora reed beds into productive farmland through elevated planting surfaces surrounded by water channels — represented an engineering project of extraordinary scale, with some estimates suggesting the system covered over 80,000 hectares at its maximum extent. The water channels served not only as drainage and nutrient sources but as thermal regulators, absorbing solar heat during the day and releasing it at night to protect crops from the killing frosts that regularly occur at this altitude." },

  { id:546, n:"Mississippian Culture — Obion", r:"Americas", t:"confirmed",
    s:900, e:1350, p:1500, lang:"muskogean-proto", gov:"chiefdom",
    d:"Obion Mounds in present-day western Tennessee was a significant Mississippian centre of the western Tennessee region, a platform mound complex whose position in the lowland zone between the Tennessee River and the Mississippi River placed it within the exchange sphere of both the Cahokia-influenced northern Mississippian world and the Moundville-influenced southern tradition. The site documents the cultural diversity within the Mississippian tradition — regional variants in ceramic style, mound shape, and site layout that reveal local adaptations of the shared Mississippian cultural template rather than a monolithic, uniform civilisation imposed from Cahokia outward. Archaeological survey of the western Tennessee lowlands has revealed a dense settlement pattern of smaller villages and farmsteads surrounding Obion and similar mound centres, documenting the agricultural landscape that supported these political and ceremonial focal points." },

  { id:547, n:"Chimu — Chan Chan Extended", r:"Americas", t:"confirmed",
    s:900, e:1470, p:60000, lang:"mochica", gov:"monarchy",
    d:"Chan Chan, the capital of the Chimú Empire in present-day northern Peru, was the largest pre-Columbian city in South America and one of the largest adobe cities ever built — a sprawling urban landscape covering approximately 20 square kilometres, organised around nine or ten royal compounds (ciudadelas) each built by a successive Chimú king as his personal palace and ultimately his mausoleum. The ciudadela system documents a distinctive Chimú political institution: the principle of split inheritance, in which a new king built a new palace and accumulated new wealth while the deceased king's palace was maintained by his descendants as a mortuary cult estate. This split inheritance system drove the continuous expansion of Chimú territory and wealth extraction, as each new ruler needed to generate the resources to build a new ciudadela while maintaining existing ones. Chan Chan's hydraulic infrastructure — long canals bringing water from the Santa and Moche rivers across the desert — made the city possible in one of Earth's most arid coastal environments." },

  { id:548, n:"Muisca Confederation", r:"Americas", t:"confirmed",
    s:600, e:1538, p:300000, lang:"chibchan-muisca", gov:"confederation",
    d:"The Muisca Confederation of the high Bogotá savanna in present-day Colombia (~600–1538 CE) was one of the four major civilisations of the Americas at the time of Spanish contact, alongside the Aztec, Maya, and Inca, though it is far less well known in popular accounts of pre-Columbian civilisation. The Muisca are the origin of the El Dorado legend — their ritual of Zipa (the ruler) coating himself in gold dust and casting gold and emerald offerings into Lake Guatavita was witnessed and reported by Spanish conquistadors and ignited centuries of gold-seeking expeditions across South America. The Muisca were the world's largest producers of emeralds, extracting them from the Muzo and Chivor mines in the eastern Andes. Their political organisation — a confederation of city-states under two paramount rulers, the Zipa and the Zaque — was sophisticated enough to maintain political cohesion across a population of 300,000–500,000 people in a challenging high-altitude environment. The Spanish conquest of the Muisca homeland in 1537–1538 was rapid due to internal political divisions the conquistadors exploited." },

  { id:549, n:"Mississippian Culture — Helena Crossing", r:"Americas", t:"confirmed",
    s:900, e:1400, p:1000, lang:"various-muskogean", gov:"chiefdom",
    d:"Helena Crossing Mounds in present-day Arkansas was a significant Mississippian centre on the west bank of the Mississippi River, occupying a strategically important position at a natural crossing point that made it a node in the river-borne exchange network of the central Mississippi Valley. Sites like Helena Crossing document the Mississippian practice of establishing ceremonial and political centres at river confluences and crossings — geographic chokepoints that enabled the control of trade and movement along the natural highway system of the river network. The Mississippi River and its major tributaries constituted the primary transport infrastructure of the Mississippian world, and the political geography of Mississippian chiefdoms closely tracks the distribution of navigable waterways. Helena Crossing's position opposite present-day Helena, Arkansas, reflects the enduring strategic significance of this particular river crossing across multiple millennia of human history." },

  { id:550, n:"Mississippian Culture — Powers Phase", r:"Americas", t:"confirmed",
    s:1000, e:1400, p:2000, lang:"various-siouan", gov:"chiefdom",
    d:"The Powers Phase of the Mississippi River lowlands in present-day southeastern Missouri (~1000–1400 CE) is archaeologically significant as a well-documented regional Mississippian community whose settlement pattern — a single large centre (Powers Fort) surrounded by four medium villages and numerous hamlets and farmsteads — has been comprehensively surveyed and mapped, providing one of the most complete pictures of how a Mississippian local community system was spatially organised across the landscape. James Price and James Griffin's systematic survey of the Powers Phase settlement system in the 1970s and 1980s became a model for regional settlement archaeology and demonstrated that Mississippian communities could be understood as integrated territorial systems rather than isolated site assemblages. The Powers Phase people appear to have abandoned their territory rapidly around 1400 CE, possibly in response to the same climatic and political disruptions that were reorganising Mississippian societies across the region." },
  // END PHASE 5ad
];
