// ════════════════════════════════════════════════════════════════════════════
// PHASE 5ae — APPEND TO data.js
// Civilizations 551–580
// ════════════════════════════════════════════════════════════════════════════
//
// INSTRUCTIONS (owner):
//   1. Open your local data.js
//   2. Find the very last closing  ];  at the bottom
//   3. Replace that  ];  with a comma, then paste ALL lines below
//      (these entries already end with the correct closing bracket)
//
// ════════════════════════════════════════════════════════════════════════════

// ── PHASE 5ae — Civilizations 551–580 ─────────────────────────────────────
// Append to CIVS array in data.js — APPEND-ONLY

  { id:551, n:"Mississippian Culture — Zebree", r:"Americas", t:"confirmed",
    s:900, e:1200, p:500, lang:"various-mississippian", gov:"chiefdom",
    d:"Zebree in present-day northeastern Arkansas is an early Mississippian site whose careful excavation documented the transition from Late Woodland to early Mississippian cultural patterns in the central Mississippi Valley with unusual stratigraphic clarity. The site preserves evidence of the rapid adoption of Mississippian ceramic technology, maize intensification, and community reorganisation that characterises the Mississippian emergence across the region around 900–1000 CE. Zebree's importance lies not in its scale but in the precision with which it documents this cultural transition at the community level — the shift in house form, ceramic assemblage, and agricultural practice that marks the archaeological boundary between Woodland and Mississippian traditions. Such transitional sites are critical for understanding how the Mississippian cultural package spread — whether through migration, elite emulation, religious conversion, or economic advantage — across the Eastern Woodlands." },

  { id:552, n:"Fremont — Nine Mile Canyon", r:"Americas", t:"confirmed",
    s:950, e:1250, p:2000, lang:"unknown-fremont", gov:"band-chiefdom",
    d:"Nine Mile Canyon in present-day Utah contains one of the largest and most spectacular concentrations of rock art in North America — over 10,000 petroglyphs and pictographs created primarily by Fremont culture people between approximately 950–1250 CE, earning it the designation 'the world's longest art gallery.' The imagery includes hunting scenes of extraordinary naturalism, anthropomorphic figures with elaborate headdresses and regalia, shield-bearing warriors, bighorn sheep hunts, and cosmological symbols whose meaning remains imperfectly understood. The canyon served as a travel corridor connecting the Uinta Basin to the Colorado Plateau, and the concentration of imagery at specific narrows and water sources suggests the rock art marked significant locations in a sacred and practical landscape. Nine Mile Canyon's rock art corpus documents the Fremont people's rich ceremonial and intellectual life in a medium more durable than the perishable organic materials that constitute most of their preserved cultural output." },

  { id:553, n:"Mogollon Culture", r:"Americas", t:"confirmed",
    s:200, e:1450, p:15000, lang:"uto-aztecan-proto", gov:"village",
    d:"The Mogollon culture (~200–1450 CE) of the mountains and desert grasslands of southwestern New Mexico and southeastern Arizona developed one of the most distinctive ceramic traditions of the American Southwest — Mimbres pottery, produced during the Classic Mimbres phase (~1000–1150 CE), features black-on-white geometric and figurative designs of extraordinary sophistication, including narrative hunting scenes, mythological beings, fish, insects, and humans rendered with an economy of line and compositional mastery that ranks among the finest ceramic art of the pre-Columbian Americas. Mimbres bowls were typically 'killed' — pierced with a hole — before being placed over the face of the deceased in burial, suggesting a cosmological belief about releasing the vessel's spirit. The Mimbres artistic tradition collapsed abruptly around 1150 CE, with the abandonment of Classic Mimbres villages, in a pattern potentially linked to the same climate stress affecting Ancestral Puebloan communities to the north." },

  { id:554, n:"Sinagua Culture", r:"Americas", t:"confirmed",
    s:500, e:1425, p:10000, lang:"uto-aztecan-proto", gov:"village",
    d:"The Sinagua culture (~500–1425 CE) of north-central Arizona — whose name means 'without water' in Spanish, reflecting the challenging environment they occupied — developed a distinctive cultural tradition in the Verde Valley and the San Francisco Peaks region that combined elements of Hohokam, Ancestral Puebloan, and Mogollon traditions with local innovation. The most spectacular Sinagua site is Montezuma Castle — a five-storey cliff dwelling of 20 rooms built into a natural limestone alcove 27 metres above the Verde Valley floor, one of the best-preserved prehistoric cliff dwellings in North America. The Sinagua also built Tuzigoot, a hilltop pueblo of 110 rooms overlooking the Verde River, and Wupatki, a large pueblo near the San Francisco Peaks built on volcanic cinders deposited by the 1064–1065 CE eruption of Sunset Crater — an eruption that initially disrupted and ultimately attracted farming populations to the region as volcanic ash improved soil moisture retention." },

  { id:555, n:"Salado Culture", r:"Americas", t:"confirmed",
    s:1150, e:1450, p:20000, lang:"uto-aztecan-proto", gov:"village",
    d:"The Salado culture (~1150–1450 CE) of the Tonto Basin and Salt River drainage of central Arizona represents a cultural florescence in which Hohokam, Mogollon, and Ancestral Puebloan influences synthesised into a distinctive regional tradition characterised above all by polychrome pottery — red, white, and black ceramics of a distinctive style traded widely across the Southwest and used as mortuary goods in a burial tradition that interred the dead beneath house floors. The cliff dwellings of the Tonto National Monument — Upper and Lower Tonto Cliff Dwelling — are the most accessible surviving Salado architectural achievements. The Salado flourished during a period when the collapse of Chaco Canyon and the reorganisation of Hohokam society were creating population movements across the Southwest, and their rapid growth may reflect successful adaptation to the demographic disruption of the 13th century. Their abandonment of the Tonto Basin around 1450 CE, in common with most Southwestern cultures, remains linked to drought cycles documented in tree-ring records." },

  { id:556, n:"Ancestral Puebloan — Bandelier", r:"Americas", t:"confirmed",
    s:1150, e:1550, p:5000, lang:"proto-puebloan", gov:"village",
    d:"Bandelier National Monument in present-day New Mexico preserves the remains of Ancestral Puebloan occupation of the Pajarito Plateau — a landscape of dramatic volcanic tuff canyons where people carved rooms directly into the soft cliff faces to supplement freestanding pueblo construction, creating the distinctive talus house and cave room communities of Frijoles Canyon and surrounding drainages. The Pajarito Plateau communities developed in the 12th and 13th centuries CE as populations moved south from the Four Corners region following the abandonment of Mesa Verde and related sites. Tyuonyi, the largest community at Bandelier, was a circular pueblo of approximately 400 rooms surrounding a central plaza, occupied from approximately 1350–1550 CE. The descendants of Bandelier's occupants are the modern Cochiti, San Ildefonso, Santa Clara, and other Pueblo peoples of the Rio Grande Valley, who maintain oral traditions and ceremonial connections to the Pajarito Plateau sites." },

  { id:557, n:"Ancestral Puebloan — Aztec Ruins", r:"Americas", t:"confirmed",
    s:1100, e:1300, p:2000, lang:"proto-puebloan", gov:"theocracy",
    d:"Aztec Ruins National Monument in present-day New Mexico — named by 19th-century American settlers who incorrectly attributed the site to the Aztecs — is a large Ancestral Puebloan great house complex built and occupied primarily during the 12th and 13th centuries CE, serving as a major regional centre in the northern San Juan Basin after the decline of Chaco Canyon. The site features a great house of approximately 450 rooms, a fully reconstructed great kiva — the only fully reconstructed great kiva open to the public — and evidence of two distinct construction episodes associated first with the Chacoan and subsequently with the Mesa Verde cultural traditions, making Aztec Ruins uniquely valuable for documenting the transition between these two phases of Ancestral Puebloan regional organisation. The great kiva's reconstruction, completed by Earl Morris in 1934, provides an unparalleled sense of the interior ceremonial space of Ancestral Puebloan communal ritual." },

  { id:558, n:"Mississippian Culture — Lilbourn", r:"Americas", t:"confirmed",
    s:1000, e:1400, p:1000, lang:"various-siouan", gov:"chiefdom",
    d:"Lilbourn Mounds in present-day southeastern Missouri represents a Mississippian centre in the Cairo Lowland — the northernmost extension of the Mississippi River alluvial plain — documenting the spread of Mississippian cultural traditions into a zone that served as a transition between the Cahokia-dominated American Bottom to the north and the Lower Mississippi Valley Mississippian tradition to the south. The Cairo Lowland contained a dense concentration of Mississippian mound sites that exploited the extraordinarily fertile alluvial soils of this region, now largely obliterated by agricultural drainage and modification. Lilbourn's mound configuration and ceramic assemblage show connections to both the Cahokia sphere to the north and the Powers Phase regional system to the west, documenting the overlapping influence zones of different Mississippian political systems in this transitional geographic zone." },

  { id:559, n:"Ancestral Puebloan — Wupatki", r:"Americas", t:"confirmed",
    s:1100, e:1250, p:2000, lang:"proto-puebloan", gov:"village",
    d:"Wupatki Pueblo in present-day northern Arizona was built on the volcanic cinders deposited by the 1064–1065 CE eruption of Sunset Crater — one of the most precisely dated natural events in prehistoric North American history, confirmed by tree-ring analysis of timbers killed by the eruption. The ash fall initially disrupted existing farming communities but ultimately attracted new populations to the area as volcanic cinders acted as a mulch, improving soil moisture retention and agricultural productivity in an otherwise marginal environment. At its peak around 1100–1150 CE, Wupatki was one of the largest pueblos in the region, with approximately 100 rooms, a ball court connecting it culturally to Hohokam traditions to the south, and a community blowhole — a crack in the underlying rock through which air moves with changing atmospheric pressure, possibly understood as a breathing earth in Pueblo cosmology. The Sunset Crater eruption and the Wupatki florescence it produced represent one of the clearest documented examples of a catastrophic natural event reshaping the cultural landscape of the prehistoric Southwest." },

  { id:560, n:"Hohokam — Casa Grande", r:"Americas", t:"confirmed",
    s:1150, e:1450, p:5000, lang:"uto-aztecan-proto", gov:"chiefdom",
    d:"Casa Grande ('Great House') in present-day Arizona is the most enigmatic and debated structure in the Hohokam cultural tradition — a four-storey caliche adobe tower of massive walls built around 1350 CE, whose function remains uncertain despite over a century of archaeological investigation. Proposed interpretations include an astronomical observatory (openings in the walls align with the sun at solstices and equinoxes), a watchtower, an elite residence, a ceremonial structure, or a combination of these functions. Casa Grande was the first prehistoric ruin in the United States to receive federal protection, designated a national monument by President Benjamin Harrison in 1892. The surrounding compound contains multiple smaller structures, a ball court, and evidence of the canal irrigation system that sustained the Hohokam community of Coolidge. The structure's unique architectural form — nothing quite like it exists elsewhere in the prehistoric Southwest — makes it both compelling and frustrating for archaeologists attempting to understand its original function and meaning within Hohokam society." },

  { id:561, n:"Ancestral Puebloan — Hovenweep", r:"Americas", t:"confirmed",
    s:900, e:1300, p:2500, lang:"proto-puebloan", gov:"village",
    d:"Hovenweep National Monument in present-day Utah and Colorado preserves six clusters of Ancestral Puebloan towers, pueblos, and kivas built primarily during the 13th century CE on canyon rims and boulders overlooking small drainages in the Great Sage Plain. The towers of Hovenweep — D-shaped, round, square, and oval structures of careful masonry built at the canyon edge — have attracted particular attention for their possible astronomical function: openings in several towers align with the rising and setting sun at solstices and equinoxes, consistent with Anna Sofaer's broader argument for astronomical intentionality in Ancestral Puebloan architecture. The towers may also have served as defensive structures in a period of increasing inter-community conflict documented archaeologically across the northern Southwest in the 13th century. Hovenweep's communities were abandoned around 1300 CE in the same migration that emptied the Four Corners region, with descendants moving to the Rio Grande Pueblos of New Mexico." },

  { id:562, n:"Mississippian Culture — Moundville Related Sites", r:"Americas", t:"confirmed",
    s:1100, e:1400, p:5000, lang:"muskogean", gov:"chiefdom",
    d:"The constellation of Moundville-related sites in the Black Warrior and Warrior-Tombigbee drainage — including Snow's Bend, Asphalt Plant, and numerous smaller mound sites — collectively document the regional chiefdom system of which Moundville was the paramount centre. Archaeological survey and excavation at these secondary centres has revealed the mechanisms by which Moundville projected political and religious authority across its territory: the distribution of Moundville-style ceramics, the presence of reduced-scale mound construction replicating the Moundville template, and the flow of prestige goods from the paramount centre to subsidiary sites in a redistributive economy that bound the regional system together. The secondary centres served as administrative nodes connecting the agricultural hinterland to the ceremonial capital, collecting tribute, hosting local ceremonies, and providing a graduated hierarchy of political authority between the farming villages and the paramount site." },

  { id:563, n:"Hopewell — Newark Earthworks", r:"Americas", t:"confirmed",
    s:-100, e:500, p:3000, lang:"various-eastern-woodlands", gov:"chiefdom",
    d:"The Newark Earthworks in present-day Ohio constitute the largest known earthwork complex in the world — a system of geometric enclosures covering an area of approximately 10 square miles, including a perfect circle of 1,054 metres diameter, a perfect octagon of 50 hectares, and multiple other precisely constructed geometric forms connected by parallel-walled avenues. The geometric precision of the Newark earthworks — surveyed repeatedly and confirmed to maintain near-perfect geometric form across the entire complex — implies a sophisticated knowledge of geometry, surveying, and large-scale landscape planning. Ray Hively and Robert Horn's analysis demonstrated that the octagon and circle encode accurate predictions of the 18.6-year lunar cycle — specifically the northernmost moonrise and moonset of the lunar standstill cycle. The Newark Earthworks are now bisected by a golf course, roads, and the Ohio State Fairgrounds, making this extraordinary monument one of the most compromised major archaeological sites in North America. The Octagon remains on the golf course, which the Ohio History Connection is working to recover for public access." },

  { id:564, n:"Hopewell — Mound City", r:"Americas", t:"confirmed",
    s:-100, e:400, p:1000, lang:"various-ohio", gov:"chiefdom",
    d:"Mound City in present-day Ohio — now Hopewell Culture National Historical Park — is a precisely square earthen enclosure of 4.5 hectares containing 23 burial mounds, one of the most important Hopewell ceremonial sites in the Ohio heartland. The mounds at Mound City contained extraordinarily rich assemblages of grave goods documenting the Hopewell exchange network at its most elaborate: copper cutouts from Lake Superior copper, obsidian from Yellowstone, silver from Ontario, grizzly bear teeth from the Rocky Mountains, and mica from the southern Appalachians — prestige materials assembled from sources across the entire North American continent. The site was catastrophically disturbed during World War I when a military training camp was constructed directly over the earthworks, destroying most of the mound deposits. Subsequent excavation by Henry Shetrone in the 1920s recovered significant material from disturbed contexts, but the irreplaceable stratigraphic information lost during the military occupation represents one of American archaeology's greatest losses." },

  { id:565, n:"Hopewell — Seip Earthworks", r:"Americas", t:"confirmed",
    s:-100, e:400, p:500, lang:"various-ohio", gov:"chiefdom",
    d:"Seip Earthworks in present-day Ohio is one of the most important Hopewell ritual centres in the Scioto River valley, featuring a large circular and oval enclosure system surrounding burial mounds whose excavation in the early 20th century produced some of the most spectacular Hopewell mortuary assemblages ever recovered. The Seip Mound 1 — the primary burial mound within the enclosure — yielded copper breastplates, mica cutouts, pearl ornaments, and effigy platform pipes of extraordinary quality, now among the prized collections of the Ohio History Connection. The Seip earthworks demonstrate the characteristic Hopewell combination of geometric precision in earthwork construction with lavish mortuary investment — a pattern suggesting that the ritual and cosmological authority embodied in the earthwork geometry was directly connected to the social and spiritual power of the elite individuals interred within the mounds. The site is partially preserved and partially destroyed by agriculture." },

  { id:566, n:"Mississippian — Lubbub Creek", r:"Americas", t:"confirmed",
    s:900, e:1400, p:1000, lang:"muskogean", gov:"chiefdom",
    d:"Lubbub Creek Archaeological Complex in present-day Alabama was a Mississippian mound centre on the Tombigbee River whose systematic excavation in the 1970s and early 1980s — prompted by the planned construction of the Tennessee-Tombigbee Waterway — produced one of the most complete datasets for a small Mississippian community ever assembled, documenting the full range of residential, agricultural, and ceremonial activities at a site below the paramount centre level. The Lubbub Creek data have been extensively used to model Mississippian community organisation, agricultural intensification, and the relationship between small mound centres and their surrounding agricultural hinterlands. The site exemplifies the salvage archaeology principle: the threat of destruction by a federal construction project mobilised resources for excavation that would otherwise not have been available, producing scientific knowledge at the cost of the irreplaceable physical site." },

  { id:567, n:"Mississippian — Lake George", r:"Americas", t:"confirmed",
    s:1100, e:1400, p:3000, lang:"various-muskogean", gov:"chiefdom",
    d:"Lake George Mounds in present-day Mississippi was a major Mississippian centre of the Yazoo Basin — the same extraordinarily productive alluvial zone that supported Winterville and Carson Mounds — featuring a large platform mound complex that served as a regional ceremonial and political focal point within the dense Mississippian settlement of the lower Yazoo River drainage. The Yazoo Basin as a whole constituted one of the most densely Mississippian-settled regions in North America, with mound sites distributed at intervals of a few kilometres across the bottomland, suggesting a landscape that was politically organised and economically integrated at a fine spatial scale. Lake George's position within this landscape identifies it as a significant node in the regional exchange and political hierarchy, though its specific role relative to Winterville and other nearby centres involves questions of temporal priority and political dominance that archaeological evidence has not yet fully resolved." },

  { id:568, n:"Mississippian — Pocahontas", r:"Americas", t:"confirmed",
    s:1000, e:1400, p:500, lang:"various-mississippian", gov:"chiefdom",
    d:"Pocahontas Mounds in present-day Mississippi represents another node in the dense network of Mississippian centres across the Yazoo Basin alluvial plain, documenting the fine-grained political and ceremonial landscape of this extraordinarily productive agricultural zone. The distribution of mound sites like Pocahontas across the Yazoo Basin at regular intervals reflects the spatial logic of the Mississippian chiefdom system — each centre serving a surrounding agricultural territory whose surplus supported the ceremonial and political activities at the mound site, with higher-order centres like Winterville and Lake George integrating multiple lower-order centres into a regional hierarchy. Pocahontas and similar smaller Yazoo Basin sites have been less studied than the major centres, but their collective significance for understanding Mississippian settlement systems is considerable, representing the median experience of Mississippian political life rather than the exceptional scale of paramount centres." },

  { id:569, n:"Ancestral Puebloan — Salmon Ruins", r:"Americas", t:"confirmed",
    s:1080, e:1280, p:1000, lang:"proto-puebloan", gov:"theocracy",
    d:"Salmon Ruins near present-day Bloomfield, New Mexico, was a Chacoan outlier great house built in a single massive construction episode around 1088–1094 CE — its precisely dated construction documented by dendrochronology of its primary roof beams — making it one of the most precisely dated major prehistoric structures in North America. The site served as a northern Chacoan administrative centre and ritual facility in the San Juan River valley, built according to the standardised Chacoan great house template with core-and-veneer masonry, kivas integrated into the room block, and a tower kiva. After the decline of the Chacoan system around 1130 CE, Salmon Ruins was reoccupied by Mesa Verde-tradition people who modified and extended the structure, creating an unusually clear stratigraphic record of the Chacoan-to-Mesa Verde cultural transition in a single site. A catastrophic fire in the secondary occupation period killed a significant number of children whose remains were found in the tower kiva, one of the most poignant discoveries in Southwestern archaeology." },

  { id:570, n:"Mississippian — Ingomar Mounds", r:"Americas", t:"confirmed",
    s:1000, e:1350, p:500, lang:"various-muskogean", gov:"chiefdom",
    d:"Ingomar Mounds in present-day Mississippi is a small Mississippian platform mound site that — while modest in scale — was the subject of one of the first systematic archaeological investigations of a Mississippian site in the Yazoo Basin, conducted by Calvin Brown in the early 20th century. The documentation of sites like Ingomar established the basic typology of Mississippian mound architecture in the Lower Mississippi Valley and contributed to the recognition of the Mississippian culture as a coherent archaeological tradition spanning the eastern United States. The Yazoo Basin sites collectively — Winterville, Carson, Lake George, Pocahontas, Ingomar, and dozens of others — represent a settlement density that speaks to the extraordinary agricultural productivity of the Mississippi alluvial plain and the political sophistication of the Mississippian peoples who organised and inhabited this landscape for over 500 years." },

  { id:571, n:"Woodland Culture — Havana Tradition", r:"Americas", t:"confirmed",
    s:-200, e:400, p:15000, lang:"various-eastern-woodlands", gov:"chiefdom",
    d:"The Havana Hopewell tradition of the Illinois River valley (~200 BCE–400 CE) was one of the two primary centres of Hopewell ceremonialism — alongside the Ohio Hopewell heartland — and the source of much of the ceramic and exchange material that defined the Hopewell Interaction Sphere across the eastern half of North America. Havana Hopewell sites, particularly Dickson Mounds and the Fulton County mound groups, demonstrate the full elaboration of Hopewell mortuary ceremonialism: geometric earthwork enclosures, log-lined burial chambers, and rich assemblages of exotic goods from across the continent. The Illinois River valley's position at the confluence of multiple major waterways — connecting the Great Lakes to the Gulf of Mexico and the Mississippi to the Ohio — gave Havana Hopewell communities unparalleled access to the long-distance exchange networks that defined the Hopewell world. The Havana tradition's decline around 400 CE, in common with Ohio Hopewell, remains poorly explained — the 'Hopewell Collapse' is one of eastern North American archaeology's enduring questions." },

  { id:572, n:"Woodland Culture — Kansas City Hopewell", r:"Americas", t:"confirmed",
    s:-100, e:700, p:5000, lang:"various-plains", gov:"chiefdom",
    d:"The Kansas City Hopewell tradition of the Missouri and Kansas River confluence region represents the westernmost major expression of Hopewell ceremonialism, documenting the extraordinary geographic reach of the Hopewell Interaction Sphere into the eastern margins of the Great Plains. Kansas City Hopewell communities participated in the exchange of platform pipes, copper objects, and exotic materials with the Ohio and Illinois Hopewell heartlands while developing local adaptations appropriate to the prairie-forest ecotone environment they occupied. The westernmost Hopewell sites provide important evidence for the mechanisms of Hopewell interaction — whether through direct travel of individuals, relay exchange along chains of communities, or periodic aggregation events — and for the relationship between Hopewell ceremonialism and the subsistence economies of communities living in diverse environments at the system's margins. Kansas City Hopewell's survival into the 7th century CE, after Ohio and Illinois Hopewell had declined, suggests regional variability in the Hopewell Collapse that complicates simple monocausal explanations." },

  { id:573, n:"Mississippian — Orendorf Site", r:"Americas", t:"confirmed",
    s:1050, e:1200, p:3000, lang:"various-illinois", gov:"chiefdom",
    d:"The Orendorf site in present-day western Illinois was one of the largest early Mississippian communities in the central Illinois River valley, occupied during the critical period of Mississippian emergence and expansion in the 11th and 12th centuries CE. The site's large residential population, defensive palisade, and platform mound document the emergence of Mississippian-pattern communities in the northern periphery of the Cahokia sphere — communities that adopted Mississippian cultural practices while adapting them to the environmental and social conditions of the Illinois valley. Orendorf's excavation has contributed to understanding how Mississippian cultural packages spread northward from the Cahokia heartland, and whether this spread involved migration of people, movement of ideas through trade and intermarriage, or the forcible incorporation of existing communities into Cahokia's political sphere. Evidence of violence at some northern Mississippian sites — including burned villages and skeletal trauma — suggests the expansion was not always peaceful." },

  { id:574, n:"Mississippian — Cahokia Woodhenge", r:"Americas", t:"confirmed",
    s:900, e:1200, p:0, lang:"various-siouan", gov:"theocracy",
    d:"The Woodhenge solar calendar complex at Cahokia — a series of large red cedar post circles reconstructed through postholes excavated adjacent to Monks Mound — represents one of the most sophisticated astronomical instruments of the pre-Columbian Americas. Warren Wittry's identification and Warren Witty and Robert Hall's subsequent analysis of five successive post circles, each slightly larger than the last, demonstrated that the circles were designed so that a person standing at the centre post could observe the sunrise at the solstices and equinoxes in alignment with specific marker posts on the circle's circumference. The circles' sequential construction documents a refinement process over time, suggesting ongoing astronomical observation and calendar improvement. The summer solstice sunrise as seen from Woodhenge aligns over Monks Mound itself, connecting the solar calendar to the political and religious centre of Cahokia in a single sightline. Woodhenge demonstrates that the Cahokia leadership maintained sophisticated astronomical knowledge as an instrument of political authority — controlling the calendar meant controlling the timing of planting, ceremony, and tribute." },

  { id:575, n:"Ancestral Puebloan — Chetro Ketl", r:"Americas", t:"confirmed",
    s:1020, e:1120, p:500, lang:"proto-puebloan", gov:"theocracy",
    d:"Chetro Ketl in Chaco Canyon, New Mexico, is the second-largest great house in the canyon — a D-shaped structure of approximately 500 rooms and 16 kivas built over a construction period of about a century, featuring an elevated colonnade (the only known colonnade in Ancestral Puebloan architecture) and an enormous enclosed plaza of 1.5 hectares. The colonnade — a row of masonry columns supporting a raised walkway along the south face of the great house — has no known functional precedent in the Southwest and has been interpreted as evidence of direct Mesoamerican architectural influence, possibly from the colonnaded halls of Tula or Teotihuacan. Chetro Ketl's road connections, water control features, and the elaborate great kiva in its plaza document it as one of the primary ritual and administrative facilities of the Chacoan system. Its abandonment around 1120 CE, slightly before Pueblo Bonito, traces the sequence of Chacoan great house disuse that marked the system's collapse." },

  { id:576, n:"Woodland Culture — Marksville", r:"Americas", t:"confirmed",
    s:-100, e:400, p:2000, lang:"various-lower-mississippi", gov:"chiefdom",
    d:"The Marksville culture of the Lower Mississippi Valley (~100 BCE–400 CE) was the southern expression of Hopewell ceremonialism, documenting the extraordinary southward reach of the Hopewell Interaction Sphere to the Gulf Coast region. Marksville site in present-day Louisiana features geometric earthwork enclosures and burial mounds whose contents — copper objects, platform pipes, and exotic ceramic vessels — are unmistakably Hopewell in character despite the site's location nearly 1,000km from the Ohio heartland. The Marksville tradition provides crucial evidence for understanding how the Hopewell Interaction Sphere maintained coherence across such vast distances: the similarity of ritual practice, mortuary treatment, and prestige object styles across communities separated by hundreds of kilometres implies either frequent long-distance travel, relay exchange networks of remarkable efficiency, or the movement of ritual specialists across the system. Marksville's position at the southern end of the Mississippi River valley also connects the Hopewell world to the earlier Poverty Point tradition of the same region, raising questions about long-term cultural continuity in the Lower Mississippi Valley." },

  { id:577, n:"Mississippian — Aztalan Phase II", r:"Americas", t:"confirmed",
    s:1100, e:1200, p:300, lang:"various-great-lakes", gov:"chiefdom",
    d:"The mature occupation of Aztalan in present-day Wisconsin documents what appears to be an intensification of Mississippian practices at this northernmost outpost — a period in which the community's connections to the Cahokia sphere were maintained or strengthened even as the site remained an isolated enclave in a landscape dominated by local Woodland-tradition peoples. The evidence for human sacrifice and possible ritual cannibalism at Aztalan — disarticulated and processed human bones in specific contextual associations — has generated significant debate about whether these represent Mississippian mortuary practices brought from the south, evidence of conflict with local peoples, or misinterpreted refuse. Aztalan's abandonment around 1200 CE, while Cahokia itself was still at or near its peak, suggests that the northernmost Mississippian communities were vulnerable to local pressures that the metropolitan centre itself was insulated from. The site stands as evidence of both the ambition and the limits of Mississippian cultural expansion." },

  { id:578, n:"Ancestral Puebloan — Lowry Pueblo", r:"Americas", t:"confirmed",
    s:1090, e:1300, p:100, lang:"proto-puebloan", gov:"village",
    d:"Lowry Pueblo in present-day southwestern Colorado is a Chacoan outlier great house of moderate size — approximately 40 rooms and eight kivas — whose distinctive feature is the painted great kiva, one of the very few Ancestral Puebloan great kivas to preserve significant surviving wall paintings in situ. The paintings, executed in red, white, and black pigments on plaster, depict geometric and possibly cosmological imagery consistent with the broader Ancestral Puebloan ceremonial tradition. Lowry Pueblo was built in stages between approximately 1090 and 1120 CE, with tree-ring dating establishing a precise construction chronology. Its position as a Chacoan outlier in the northern periphery of the system documents the geographic extent of Chacoan political and religious influence and the mechanisms by which standardised great house architecture was replicated across the Colorado Plateau as a visible marker of participation in the Chacoan system." },

  { id:579, n:"Mississippian — Coles Creek Culture", r:"Americas", t:"confirmed",
    s:700, e:1200, p:10000, lang:"various-lower-mississippi", gov:"chiefdom",
    d:"The Coles Creek culture of the Lower Mississippi Valley (~700–1200 CE) represents the immediate predecessor of the full Mississippian tradition in this region — a period of increasing social complexity, mound construction, and platform mound-centred ceremonialism that set the stage for the Mississippian fluorescence but predates the adoption of certain key Mississippian markers, particularly maize intensification and the full elaboration of Southeastern Ceremonial Complex iconography. Coles Creek sites, distributed across the Mississippi and Red River alluvial plains, document the gradual development of ranked society, redistributive chiefdom economies, and monumental earthwork construction in the Lower Mississippi Valley in the centuries before the Classic Mississippian pattern emerged. The relationship between Coles Creek and the subsequent Mississippian tradition in this region is one of continuity and transformation rather than replacement — the Mississippian tradition of the Lower Valley grew from Coles Creek roots rather than being introduced by population movements from the north." },

  { id:580, n:"Ancestral Puebloan — Yellow Jacket", r:"Americas", t:"confirmed",
    s:900, e:1300, p:2500, lang:"proto-puebloan", gov:"village",
    d:"Yellow Jacket Pueblo in present-day southwestern Colorado was one of the largest Ancestral Puebloan communities of the Mesa Verde region, with an estimated 1,200–1,900 rooms making it comparable in scale to Pueblo Bonito despite its relative obscurity in popular accounts of the Ancestral Puebloan world. The site features multiple great kivas, a great house, and evidence of a community that aggregated population from surrounding smaller sites during the 13th century — the same population consolidation process documented at many Mesa Verde-tradition sites in the period before the final abandonment of the Four Corners region around 1300 CE. Yellow Jacket's scale suggests it briefly served as a regional population centre during the organisational disruption of the late Pueblo III period, drawing people from a wide surrounding area in a pattern of demographic consolidation that immediately preceded the mass migration southward to the Rio Grande and beyond." },
  // END PHASE 5ae
];
