// ════════════════════════════════════════════════════════════════════════════
// PHASE 5ab — APPEND TO data.js
// Civilizations 461–490
// ════════════════════════════════════════════════════════════════════════════
//
// INSTRUCTIONS (owner):
//   1. Open your local data.js
//   2. Find the very last closing  ];  at the bottom
//   3. Replace that  ];  with a comma, then paste ALL lines below
//      (these entries already end with the correct closing bracket)
//
// ════════════════════════════════════════════════════════════════════════════

// ── PHASE 5ab — Civilizations 461–490 ─────────────────────────────────────
// Append to CIVS array in data.js — APPEND-ONLY

  { id:461, n:"Mississippian Culture — Winterville", r:"Americas", t:"confirmed",
    s:1000, e:1450, p:1500, lang:"various-muskogean", gov:"chiefdom",
    d:"Winterville Mounds in present-day Mississippi was a significant Mississippian ceremonial and political centre featuring 23 mounds arranged around a central plaza, ranking among the larger Mississippian sites in the Lower Mississippi Valley. The site served as a regional redistribution hub within the Mississippian exchange network, with material evidence connecting it to both Cahokia to the north and the Gulf Coast to the south. Winterville's occupation coincides with the height of the Mississippian fluorescence and its abandonment, like most major centres, precedes European contact by generations. The site's mound configurations and plaza layout conform closely to the standard Mississippian town planning template, suggesting strong ideological and political connections to the broader Mississippian world rather than a locally distinctive tradition." },

  { id:462, n:"Taino Civilisation", r:"Americas", t:"confirmed",
    s:1200, e:1550, p:1000000, lang:"taino-arawakan", gov:"chiefdom",
    d:"The Taino people of the Greater Antilles — Cuba, Hispaniola, Puerto Rico, Jamaica, and the Bahamas — were the first Indigenous Americans encountered by Christopher Columbus in 1492, and their civilisation was effectively destroyed within fifty years through a combination of introduced disease, enslavement, and deliberate violence that constitutes one of history's most complete and rapid demographic collapses. At contact, the Taino numbered an estimated one million people, organised into chiefdoms (cacicazgos) under hereditary chiefs (caciques) and sub-chiefs, with a sophisticated agricultural system based on cassava cultivation, a rich ceremonial life centred on zemis (sacred objects), and a ballgame tradition connecting them to the broader Mesoamerican world. Taino cultural elements — including the words hammock, canoe, hurricane, tobacco, and barbecue — entered Spanish and subsequently English, making Taino one of the most linguistically influential languages of the contact period despite its speakers' near-total destruction." },

  { id:463, n:"Mississippian Culture — Parkin", r:"Americas", t:"confirmed",
    s:1350, e:1541, p:3000, lang:"various-mississippian", gov:"chiefdom",
    d:"Parkin Mounds in present-day Arkansas is archaeologically significant as one of the few Mississippian sites that may be directly identified with a specific European historical record — it is a strong candidate for Casqui, the powerful chiefdom described in the accounts of Hernando de Soto's 1541 expedition through the Mississippi Valley. If the identification is correct, Parkin provides the rare opportunity to correlate Mississippian material culture directly with a named polity described by European eyewitnesses who encountered it while it was still functioning. The de Soto accounts describe Casqui as a major regional power engaged in active warfare with its neighbours, with the chief seeking Spanish military alliance — a glimpse of living Mississippian political dynamics unavailable from purely archaeological evidence. This historical anchoring makes Parkin disproportionately valuable for reconstructing the political landscape of the Late Mississippian period." },

  { id:464, n:"Mapungubwe Kingdom", r:"Africa", t:"confirmed",
    s:1075, e:1220, p:9000, lang:"shona-proto", gov:"monarchy",
    d:"Mapungubwe in present-day Limpopo Province, South Africa, was the first state-level society in southern Africa, predating Great Zimbabwe by over a century and establishing the political and economic template — gold trade, cattle wealth, and hilltop elite settlement — that would define the region's subsequent civilisational development. The hilltop citadel at Mapungubwe Hill, accessible only by a single narrow rock face passage, housed the ruling elite in deliberate physical separation from the commoner population below — one of the earliest documented examples of spatial class segregation in southern African archaeology. The famous Mapungubwe golden rhinoceros — a small foil-covered wooden sculpture — is one of the most evocative objects in African archaeology and a national symbol of South Africa. Mapungubwe's decline around 1220 CE, possibly linked to climate change making the Limpopo valley less productive, saw its population and political system migrate northward to establish what became the Kingdom of Zimbabwe." },

  { id:465, n:"Mississippian Culture — Carson Mounds", r:"Americas", t:"confirmed",
    s:1000, e:1400, p:1000, lang:"various-muskogean", gov:"chiefdom",
    d:"Carson Mounds in present-day Mississippi was one of the largest Mississippian sites in the Lower Mississippi Valley alluvial plain, with 37 mounds making it one of the most extensive mound complexes in the American Southeast. The site's large size and its position within the densely settled Yazoo Basin suggest it served as a major regional centre within the Mississippian political landscape of the lower valley. Like other Mississippian centres of the region, Carson was abandoned before European contact, and the alluvial agricultural lands surrounding it were subsequently converted to cotton agriculture, obscuring and destroying much of the associated residential and midden archaeology. Carson Mounds represents the broad pattern of Mississippian settlement density in the Lower Mississippi Valley — a landscape once dotted with mound centres at intervals of a day's travel, most now lost to agriculture and time." },

  { id:466, n:"Mississippian Culture — Bottle Creek", r:"Americas", t:"confirmed",
    s:1250, e:1550, p:1000, lang:"various-muskogean", gov:"chiefdom",
    d:"Bottle Creek Mounds in present-day coastal Alabama was the major Mississippian ceremonial centre of the Mobile-Tensaw delta region, a complex of 18 mounds on an island in the delta that served as the political and religious capital for Mississippian communities across the coastal plain. Its island location — accessible only by water — gave Bottle Creek a distinctive character among Mississippian centres, and its occupation extended later than most inland centres, with some evidence of activity into the early historic period. The coastal delta environment provided different subsistence resources than inland Mississippian centres, with estuarine fishing and shellfish supplementing the maize agriculture central to the broader Mississippian economy. Bottle Creek's persistence into the contact period makes it potentially linkable to the coastal Mississippian groups encountered by 16th-century Spanish explorers of the Gulf Coast." },

  { id:467, n:"Aksumite — Queen of Sheba Tradition", r:"Africa", t:"theorized",
    s:-1000, e:-900, p:0, lang:"ge-ez-proto", gov:"monarchy",
    d:"The Queen of Sheba — known as Makeda in Ethiopian tradition, Bilqis in Islamic tradition — is described in the Hebrew Bible (1 Kings 10) and the Quran as a powerful and wealthy queen who visited King Solomon in Jerusalem, a meeting that in Ethiopian royal tradition produced a son, Menelik I, ancestor of the Solomonic dynasty that ruled Ethiopia until Emperor Haile Selassie's deposition in 1974. The Kebra Nagast, the 14th-century Ethiopian national epic, elaborates this tradition and describes Menelik I bringing the Ark of the Covenant from Jerusalem to Aksum, where it is claimed to remain today. The historical identification of Sheba remains debated: candidates include the Sabaean kingdom of southwestern Arabia (South Yemen), the Ethiopian highlands, or both simultaneously. Archaeological evidence for a powerful pre-Aksumite queen matching the biblical description has not been found, but the tradition's extraordinary persistence across Ethiopian, Yemeni, and Jewish cultures across three millennia argues for some historical kernel." },

  { id:468, n:"Mississippian Culture — Anna Mounds", r:"Americas", t:"confirmed",
    s:1200, e:1500, p:1000, lang:"various-muskogean", gov:"chiefdom",
    d:"Anna Mounds in present-day Mississippi was a regional Mississippian centre of the Natchez Bluffs area, an archaeologically important zone where some of the last functioning Mississippian-tradition chiefly societies survived into the historic period as the Natchez people. The Natchez, who maintained a mound-centred political and religious system well into the 18th century and were only destroyed by French colonial military action in 1731, provide one of the most detailed ethnohistoric records of how Mississippian political and religious institutions actually functioned — including the divine status of the Great Sun chief, the rigid social hierarchy, and the mortuary practices involving retainer sacrifice that are archaeologically documented at much earlier sites. This continuity between prehistoric Mississippian archaeology and Natchez ethnohistory makes the Anna Mounds region uniquely valuable for interpreting the broader Mississippian record." },

  { id:469, n:"Medieval Iceland / Norse Commonwealth", r:"Europe", t:"confirmed",
    s:874, e:1262, p:60000, lang:"old-norse", gov:"commonwealth",
    d:"The Icelandic Commonwealth (~874–1262 CE) represents one of history's most remarkable political experiments — a functional stateless society of 60,000 people governing itself for nearly 400 years through a system of local assemblies (things) culminating in the Althing, one of the world's oldest parliaments, established in 930 CE at Þingvellir. Iceland had no king, no standing army, no executive branch — disputes were resolved through law, arbitration, and socially enforced honour obligations. The sagas composed in this period — the Íslendingasögur — are among the finest achievements of medieval literature, recording the settlement of Iceland, the discovery of North America by Leif Eriksson, and the social dramas of an honour-based society with extraordinary psychological sophistication. The Commonwealth's eventual submission to the Norwegian crown in 1262, following a century of escalating internal violence, raises profound questions about the limits of stateless governance under conditions of growing inequality." },

  { id:470, n:"Mississippian Culture — Plaquemine", r:"Americas", t:"confirmed",
    s:1200, e:1700, p:5000, lang:"various-muskogean", gov:"chiefdom",
    d:"The Plaquemine culture of the Lower Mississippi Valley (~1200–1700 CE) represents a regional variant of the Mississippian tradition that maintained distinctive cultural practices while participating in the broader Mississippian exchange network. Crucially, Plaquemine-tradition peoples — particularly the Natchez, Taensa, and related groups — survived into the European colonial period, providing the most direct link between prehistoric Mississippian archaeology and documented historical Indigenous cultures anywhere in the American Southeast. French colonial accounts of the Natchez Nation, particularly their Temple Mound ceremonialism, the divine rulership of the Great Sun, and the sacrificial mortuary practices accompanying elite deaths, illuminate cultural practices archaeologically documented at Mississippian sites centuries earlier. The Plaquemine tradition's longevity — persisting into the 18th century while most Mississippian cultures had already reorganised or dissolved — makes it the closest thing to a living window into the Mississippian world." },

  { id:471, n:"Mississippian Culture — Irene", r:"Americas", t:"confirmed",
    s:1150, e:1450, p:1000, lang:"muskogean-proto", gov:"chiefdom",
    d:"The Irene site near present-day Savannah, Georgia, represents the Irene phase of Mississippian cultural development in the coastal Georgia lowlands — a regional tradition that connected the interior Mississippian world to the Atlantic coastal plain and the Guale people documented in Spanish colonial records of the 16th and 17th centuries. The Irene mound complex demonstrates the southeasternmost coastal extension of classic Mississippian town planning, and the continuity between Irene phase archaeology and the historic Guale Nation provides another valuable link between prehistoric material culture and documented historical Indigenous societies. The Guale participated in the Spanish mission system of coastal Georgia and Florida, leaving a colonial documentary record that has been used to interpret the preceding Irene archaeological horizon. This coast-interior connection illustrates how Mississippian cultural ideas and institutions permeated even the coastal margins of the American Southeast." },

  { id:472, n:"Harappan — Lothal", r:"Asia", t:"confirmed",
    s:-2400, e:-1900, p:15000, lang:"indus-unknown", gov:"city-state",
    d:"Lothal in present-day Gujarat, India, was a major Harappan port city and industrial centre whose most remarkable feature is a large dockyard — a rectangular basin of fired brick connected to a tidal river channel — which, if correctly interpreted, represents the world's earliest known artificial dock for maritime trade. Excavated by S.R. Rao from 1955–1960, Lothal shows evidence of a bead-making industry exporting products across the Harappan trade network, a sophisticated fire altar suggesting Vedic-style ritual practice, and a grid-planned urban layout characteristic of the Harappan civilisation. The interpretation of the large basin as a dockyard has been challenged by some scholars who argue it was a large water reservoir; the debate hinges on hydrology and siltation patterns. If the dockyard interpretation is correct, Lothal's maritime infrastructure demonstrates Harappan seafaring capability fully 4,000 years ago, consistent with textual evidence of Harappan/Meluhhan trade in Mesopotamian records." },

  { id:473, n:"Harappan — Dholavira", r:"Asia", t:"confirmed",
    s:-2650, e:-1450, p:20000, lang:"indus-unknown", gov:"city-state",
    d:"Dholavira on the island of Khadir in the Great Rann of Kutch, India, is one of the five largest Harappan cities and the most extensively excavated major site of the civilisation, remarkable for its extraordinary water conservation infrastructure — a series of 16 reservoirs covering approximately one-third of the city's area, fed by seasonal flash floods through engineered channels, allowing the city to survive in one of India's most arid environments. Dholavira's three-part town plan — citadel, middle town, and lower town — is more clearly preserved than any other Harappan site. A unique Harappan inscription of ten large signs, found displayed on a gateway, is the longest known Harappan inscription and possibly a public display text — the first potential example of public writing in South Asian history. UNESCO recognised Dholavira as a World Heritage Site in 2021. The site's sophisticated water management offers striking lessons in ancient engineering responses to environmental stress." },

  { id:474, n:"Mississippian Culture — Moundville Phase III", r:"Americas", t:"confirmed",
    s:1500, e:1650, p:500, lang:"muskogean", gov:"remnant-chiefdom",
    d:"The Phase III occupation of Moundville (~1500–1650 CE) represents the final archaeological horizon at the site before complete abandonment, by which time the population had reduced to a small remnant community maintaining ceremonial use of a precinct that had once been the capital of a major regional polity. Material culture from this phase shows increasing divergence from classic Mississippian traditions and the emergence of what archaeologists identify as proto-historic and early historic Creek cultural patterns, suggesting the descendants of Moundville's population contributed to the formation of the Muscogee (Creek) Confederacy that European colonists would encounter in the 18th century. The Phase III occupation completes the remarkable transformation of Moundville across three phases — from densely populated urban capital to ceremonial mortuary precinct to small-scale remnant occupation — a trajectory that encapsulates the full arc of Mississippian civilisation in a single site." },

  { id:475, n:"Scythian — Royal Tombs of the Pontic Steppe", r:"Europe", t:"confirmed",
    s:-500, e:-200, p:200000, lang:"scythian-iranian", gov:"tribal-confederation",
    d:"The Royal Scythian kurgans of the Pontic steppe — enormous burial mounds some exceeding 20 metres in height, clustered across present-day Ukraine — contained the wealthiest assemblages of gold objects produced anywhere in the ancient world, including the famous Pectoral from Tovsta Mohyla (4th century BCE), a gold breastplate depicting Scythian daily life and mythology in extraordinary detail. These tombs, excavated primarily by Soviet and Ukrainian archaeologists from the 1950s onward, document a nomadic elite whose access to Greek craftsmen, Persian luxury goods, and trans-Eurasian trade networks produced material culture of dazzling sophistication. The kurgan burial tradition — a mound over a timber-lined burial chamber with horses, weapons, gold, and occasionally sacrificed retainers or wives — spread from Scythian origins across the steppe world and may be ancestral to similar traditions from Hungary to Mongolia. The ongoing excavation of Ukrainian kurgans has been severely disrupted by the Russian invasion of 2022, destroying irreplaceable archaeological context." },

  { id:476, n:"Minoan — Pre-Palatial / Early Bronze Age Crete", r:"Europe", t:"confirmed",
    s:-3100, e:-1900, p:30000, lang:"pre-minoan-unknown", gov:"chiefdom",
    d:"Pre-Palatial Crete (~3100–1900 BCE) represents the formative period of Aegean Bronze Age civilisation before the construction of the great Minoan palace complexes, during which Crete developed the population density, agricultural surplus, and social complexity that would produce the Neopalatial florescence. Early Bronze Age Cretan culture shows connections to Cycladic and Anatolian traditions and the earliest development of the distinctive Minoan pottery and seal engraving traditions. The transition to the First Palace period around 1900 BCE, with the near-simultaneous construction of palaces at Knossos, Phaistos, and Malia, represents one of the most dramatic and poorly-explained emergence events in Aegean archaeology — a sudden leap in organisational complexity with no obvious single trigger. The pre-palatial background makes this emergence more rather than less puzzling, and understanding the social and economic drivers of the palace system's origin remains a central question in Bronze Age Aegean studies." },

  { id:477, n:"Mississippian Culture — Aztalan", r:"Americas", t:"confirmed",
    s:1050, e:1200, p:500, lang:"various-great-lakes", gov:"chiefdom",
    d:"Aztalan in present-day Wisconsin was the northernmost major Mississippian site, a stockaded settlement with two platform mounds whose presence nearly 1,000km north of Cahokia raises fascinating questions about how and why Mississippian cultural and political institutions spread into the Great Lakes region. The site shows a mix of local Woodland ceramic traditions and imported Mississippian styles, suggesting a community that was either a Mississippian colony, a local population that adopted Mississippian practices through trade and contact, or a hybrid community of both. Aztalan's palisaded enclosure, built of closely spaced posts and bastions, has been interpreted as evidence of a hostile frontier environment — a Mississippian outpost in territory where its practices were not universally welcomed. The site's relatively brief occupation (~150 years) before abandonment may reflect the limits of Mississippian cultural expansion into environments and social contexts where its political and religious model could not sustain itself." },

  { id:478, n:"Luwian Civilisation", r:"Middle East", t:"debated",
    s:-2000, e:-700, p:500000, lang:"luwian", gov:"city-state",
    d:"The Luwians were an Indo-European-speaking people of Bronze and Iron Age Anatolia who used two writing systems — cuneiform Luwian and hieroglyphic Luwian — and whose civilisation extended across much of southern and western Anatolia and into northern Syria. They were closely related to the Hittites, sharing a common cultural ancestor, and Luwian was actually more widely spoken than Hittite across the Hittite Empire. The controversial scholar Eberhard Zangger has argued that the Luwians were the primary authors of the Late Bronze Age Collapse (~1200 BCE) as a confederation of western Anatolian city-states — potentially identifiable with the Egyptian 'Sea Peoples' — and that a major Luwian civilisation has been systematically overlooked because its cities lie under unexcavated mounds across western Turkey. Mainstream Hittitology treats Zangger's thesis with scepticism but acknowledges the significant archaeological gap in western Anatolian Bronze Age research. The Luwian language survived the Bronze Age Collapse in neo-Hittite city-states of northern Syria until the 7th century BCE." },

  { id:479, n:"Meroitic Kingdom", r:"Africa", t:"confirmed",
    s:-300, e:350, p:200000, lang:"meroitic", gov:"monarchy",
    d:"The Meroitic Kingdom (~300 BCE–350 CE) of present-day Sudan was the successor state to the Kushite (Napatan) dynasty that had once ruled Egypt, and at its height controlled the middle Nile Valley from the third to sixth cataracts. Meroe became the new royal capital following the southward shift of Kushite power, and the city's iron smelting industry — evidenced by enormous slag heaps — made it possibly the major iron production centre of sub-Saharan Africa in the ancient world. The Meroitic people developed their own alphabetic script (Meroitic) around 300 BCE, adapted from the Egyptian demotic and hieroglyphic scripts — one of the earliest indigenous African writing systems — but it remains only partially deciphered, with phonetic values known but the underlying language not yet fully understood. The spectacular royal pyramid fields at Meroe and Nuri, with their steep-sided profiles distinct from Egyptian pyramids, are among the most extraordinary archaeological sites in Africa and document a mortuary tradition maintained for over a thousand years." },

  { id:480, n:"Mississippian Culture — Medoc Mountain", r:"Americas", t:"confirmed",
    s:1000, e:1400, p:300, lang:"siouan-proto", gov:"chiefdom",
    d:"Medoc Mountain Mound in present-day North Carolina represents the Pee Dee phase of Mississippian development in the Carolina Piedmont, a small but archaeologically significant platform mound complex that documents the spread of Mississippian cultural influences into the eastern foothills of the Appalachians. The Pee Dee culture, of which Medoc Mountain is the type site alongside Town Creek, shows Mississippian-derived town planning and ceramic traditions adapted to a local Piedmont environmental and cultural context. The site's occupants were likely ancestors of the Catawba Nation, who maintained a presence in the Carolina Piedmont into the colonial period. Like Town Creek, Medoc Mountain represents the frontier of Mississippian cultural influence at its northeastern extreme, illustrating both the remarkable reach of Mississippian ideas and the ways those ideas were transformed and localised as they moved away from their heartland in the Mississippi Valley." },

  { id:481, n:"Caananite Civilisation", r:"Middle East", t:"confirmed",
    s:-3500, e:-1200, p:200000, lang:"canaanite-semitic", gov:"city-state",
    d:"The Canaanite civilisation of the Levant (~3500–1200 BCE) was one of the ancient Near East's most influential cultures — the Bronze Age inhabitants of the land that biblical tradition describes as promised to the Israelites, and the creators of the alphabetic writing system from which virtually all modern alphabets descend. The Phoenician alphabet, itself a refinement of the earlier Proto-Sinaitic and Proto-Canaanite scripts, is the ancestor of Greek, Latin, Arabic, Hebrew, and through them nearly every writing system used today. Canaanite city-states including Ugarit, Megiddo, Hazor, and Byblos were major participants in the Late Bronze Age cosmopolitan world, trading with Egypt, the Hittites, Cyprus, and the Aegean. The destruction of Canaanite urban centres in the Late Bronze Age Collapse (~1200 BCE) and the subsequent emergence of Israelite, Phoenician, and Aramean cultures from the Canaanite substrate makes the Canaanite civilisation foundational to the entire subsequent history of the Levant and, through its writing system, to global civilisation." },

  { id:482, n:"Mississippian Culture — Deep Bottom", r:"Americas", t:"confirmed",
    s:1100, e:1400, p:500, lang:"siouan-proto", gov:"chiefdom",
    d:"Deep Bottom and the broader upper Roanoke River Mississippian complex in present-day Virginia and North Carolina represents the northernmost documented penetration of Mississippian cultural influences along the Atlantic slope of the Appalachians, documenting the remarkable reach of Mississippian exchange networks and cultural transmission into the far northeast of the tradition's range. Sites in this region show Mississippian-derived ceramics, mortuary practices, and possibly mound construction traditions adapted to an Appalachian Piedmont context. The archaeological visibility of Mississippian influence at these extreme northeastern sites raises the question of what lay beyond the documented frontier — whether Mississippian exchange networks and cultural influence extended even further northeast into what is now Virginia, Maryland, and the Chesapeake region in ways not yet archaeologically documented. The northeastern frontier of Mississippian influence remains one of the less-studied aspects of this continent-spanning cultural tradition." },

  { id:483, n:"Mississippian Culture — Moundville Outliers", r:"Americas", t:"confirmed",
    s:1100, e:1400, p:500, lang:"muskogean", gov:"chiefdom",
    d:"The Moundville Outlier sites — a constellation of smaller Mississippian mound centres within the Black Warrior Valley political sphere of Moundville — document the regional political system centred on Moundville at its height, in which a paramount centre controlled a hierarchy of subsidiary sites across a defined territory. This hierarchical site structure — large paramount centre, medium-sized secondary centres, small villages and farmsteads — is the archaeological signature of a chiefdom political system, and the Moundville regional system is one of the most clearly documented examples of this settlement hierarchy anywhere in North American archaeology. The distribution of prestige goods across the hierarchy — concentrated at Moundville and distributed in diminishing quantities to lower-tier sites — demonstrates the redistributive economy through which Moundville's paramount chief maintained political authority. The collapse of this system in the 14th century, when Moundville transitioned to a mortuary precinct, apparently dismantled the regional political hierarchy as well." },

  { id:484, n:"Chumash Maritime Culture", r:"Americas", t:"confirmed",
    s:-8000, e:1820, p:20000, lang:"chumash", gov:"chiefdom",
    d:"The Chumash people of the southern California coast developed one of the most sophisticated maritime cultures in pre-Columbian North America, building the tomol — a plank canoe of extraordinary technical sophistication, constructed from driftwood planks sewn together with plant fibre and caulked with natural asphalt from the La Brea tar seeps — that enabled regular open-water crossings to the Channel Islands and sustained a trade and exchange network along the Santa Barbara coast. The Chumash supported unusually high population densities for a hunter-gatherer society through the extraordinary productivity of the marine environment, developing a complex social hierarchy, a professional class of artisans, and a shell bead currency (the only well-documented shell bead monetary system in aboriginal North America). Their rock art — particularly the painted cave sites of the Chumash Painted Cave — is among the most elaborate in North America and reflects a cosmological system involving shamanic transformation, celestial observation, and the winter solstice. The Chumash represent the maximum social complexity achievable within a non-agricultural maritime economy." },

  { id:485, n:"Casas Grandes / Paquimé", r:"Americas", t:"confirmed",
    s:1130, e:1450, p:3000, lang:"uto-aztecan-proto", gov:"city-state",
    d:"Casas Grandes (Paquimé) in present-day Chihuahua, Mexico, was the major urban centre of the Mogollon cultural tradition and the largest prehistoric settlement in the American Southwest-Northwest Mexico region, featuring multi-storey adobe architecture, an underground drainage system, ball courts connecting it to Mesoamerican traditions, and extensive facilities for the breeding of scarlet macaws — exported as prestige goods northward into the Ancestral Puebloan world. Paquimé served as a crucial interface between the complex societies of Mesoamerica to the south and the Ancestral Puebloan and Hohokam cultures of the American Southwest to the north, channelling Mesoamerican prestige goods, architectural ideas, and possibly religious concepts into the Southwest while exporting turquoise, shell, and copper southward. The site's abandonment around 1450 CE, possibly through violence, ended this north-south exchange role and isolated the southwestern Puebloan world from its Mesoamerican connections." },

  { id:486, n:"Hohokam Civilisation", r:"Americas", t:"confirmed",
    s:300, e:1450, p:40000, lang:"uto-aztecan-proto", gov:"chiefdom",
    d:"The Hohokam civilisation (~300–1450 CE) of the Sonoran Desert in present-day Arizona developed the most extensive prehistoric irrigation canal system in North America — over 800km of main canals and thousands of kilometres of secondary channels in the Phoenix Basin alone — transforming the desert floor into productive agricultural land capable of supporting tens of thousands of people. The Hohokam maintained ball courts linking them culturally to Mesoamerica, produced distinctive red-on-buff ceramics traded across the Southwest, and created a regional exchange network distributing shell from the Gulf of California, turquoise, and copper bells. The abandonment of the major Hohokam centres in the 14th–15th centuries CE, associated with severe drought and possible social disruption, is one of North American archaeology's most studied collapse events. The O'odham people of southern Arizona maintain oral traditions connecting them directly to the Hohokam, and the Hohokam canal alignments underlie the modern Phoenix metropolitan water system." },

  { id:487, n:"Ancestral Puebloans — Mesa Verde", r:"Americas", t:"confirmed",
    s:600, e:1300, p:30000, lang:"uto-aztecan-puebloan", gov:"theocracy",
    d:"Mesa Verde in present-day Colorado represents the architectural apex of Ancestral Puebloan civilisation — the cliff dwellings cut into the sandstone alcoves of Mesa Verde's canyon walls, including Cliff Palace (the largest cliff dwelling in North America), Long House, and Spruce Tree House, are among the most spectacular achievements of any pre-Columbian North American culture. Built primarily in the 12th and 13th centuries CE in defensible positions that suggest increasing warfare or social tension, the cliff dwellings were occupied for only a few generations before being abandoned around 1300 CE during a prolonged drought documented in tree-ring records. The rapidity and completeness of the abandonment — rooms left with intact pottery, tools, and food stores — suggests an urgent departure. The descendants of Mesa Verde's inhabitants are the modern Pueblo peoples of New Mexico and Arizona, who maintain oral traditions about the migration from the 'place of mist and fog.' Mesa Verde's cliff dwellings were declared a UNESCO World Heritage Site in 1978." },

  { id:488, n:"Fremont Culture", r:"Americas", t:"confirmed",
    s:600, e:1350, p:15000, lang:"unknown-uto-aztecan", gov:"band-chiefdom",
    d:"The Fremont culture (~600–1350 CE) of Utah and adjacent regions of the American West represents a distinctive cultural tradition contemporary with the Ancestral Puebloans to the south but differing in crucial ways — maintaining hunting and gathering as a major subsistence strategy alongside maize agriculture, producing a distinctive figurine tradition and moccasin style not found in Pueblo cultures, and leaving an extraordinary rock art corpus across Utah's canyon country. Fremont people occupied a range of environments from the Great Basin to the Colorado Plateau, demonstrating considerable ecological flexibility. Their relationships with Ancestral Puebloans to the south, Plains cultures to the east, and Great Basin foragers to the west made them a cultural interface zone in the prehistoric Southwest. Like the Ancestral Puebloans, the Fremont largely abandoned their settled sites around 1350 CE, possibly in response to climatic deterioration and pressure from expanding Numic-speaking peoples from the Great Basin. Their descendants are debated, with possible connections to historic Ute, Paiute, and Shoshone peoples." },

  { id:489, n:"Poverty Point — Lower Mississippi Archaic", r:"Americas", t:"confirmed",
    s:-3500, e:-1700, p:10000, lang:"unknown", gov:"band-chiefdom",
    d:"The Lower Mississippi Valley Archaic cultures (~3500–1700 BCE) that preceded and produced Poverty Point represent a poorly-understood but archaeologically significant tradition of increasing social complexity among hunter-gatherer populations along the Mississippi, Red, and Ouachita Rivers. The gradual accumulation of evidence for long-distance exchange, specialised tool production, and incipient social differentiation in this period documents the process by which hunter-gatherer societies in the Lower Mississippi Valley developed the organisational capabilities that eventually produced the extraordinary florescence of Poverty Point. Earthwork construction in this region predates Poverty Point itself, with sites like Watson Brake (~3500 BCE) — 11 mounds connected by a low ridge in an oval pattern — now recognised as the earliest known mound complex in North America, predating Poverty Point by 1,800 years. Watson Brake demonstrates that the impulse to build monumental earthworks in the American Southeast has a far deeper history than previously recognised." },

  { id:490, n:"Denisovan — Asian Distribution", r:"Asia", t:"theorized",
    s:-400000, e:-30000, p:0, lang:"unknown", gov:"unknown",
    d:"The Denisovans — an archaic human population known initially only from fragmentary remains in Denisova Cave in the Russian Altai — are now understood through ancient DNA analysis to have ranged across a vast territory from Siberia through Southeast Asia to Oceania, based on the geographic distribution of Denisovan genetic inheritance in modern populations. Melanesians and Aboriginal Australians carry approximately 3–5% Denisovan ancestry, suggesting a major Denisovan population in Southeast Asia or Wallacea that interbred with modern humans migrating through the region. Philippine Negritos carry the highest known proportion of Denisovan ancestry of any living population (~5%), suggesting prolonged contact in island Southeast Asia. Andrew Collins's Denisovan Origins (2019) proposes Denisovans as the builders of Göbekli Tepe and other early monumental sites, arguing their cognitive capabilities were equivalent to or exceeded those of contemporary Homo sapiens. Mainstream paleoanthropology acknowledges Denisovan cognitive sophistication — a needle, a bracelet, and decorated bones from Denisova Cave demonstrate symbolic behaviour — but does not accept monument-building capacity without physical evidence." },
  // END PHASE 5ab
];
