// ════════════════════════════════════════════════════════════════════════════
// PHASE 5z — APPEND TO data.js
// ════════════════════════════════════════════════════════════════════════════
//
// INSTRUCTIONS (owner):
//   1. Open your local data.js
//   2. Find the very last closing  ];  at the bottom of the CIVS array
//   3. Replace that  ];  with a comma, then paste ALL lines below it
//      (the new entries already end with  ];  )
//
// ════════════════════════════════════════════════════════════════════════════

// ── PHASE 5z — Civilizations 401–430 ──────────────────────────────────────
// Append these entries to the end of the CIVS array in data.js
// APPEND-ONLY — do not modify any existing records

  { id:401, n:"Kerma / Kingdom of Kush (Early)", r:"Africa", t:"confirmed",
    s:-2500, e:-1500, p:80000, lang:"kushitic", gov:"monarchy",
    d:"The Kerma culture of Upper Nubia (~2500–1500 BCE) represents one of Africa's earliest and most powerful indigenous kingdoms, flourishing along the Nile south of the third cataract in present-day Sudan. At its height the Kingdom of Kerma fielded armies capable of challenging Middle Kingdom Egypt and formed alliances with the Hyksos during Egypt's Second Intermediate Period. The Kerma people built massive mudbrick burial tumuli (deffufas) of extraordinary scale and sophistication, with evidence of elite burials involving hundreds of sacrificed retainers. Contemporary Egyptological scholarship has increasingly recognised Kerma as a peer civilisation to Egypt rather than a peripheral culture, though its full cultural complexity continues to be reassessed as excavations at the site of Kerma deepen." },

  { id:402, n:"Phrygian Kingdom", r:"Middle East", t:"confirmed",
    s:-1200, e:-546, p:500000, lang:"phrygian", gov:"monarchy",
    d:"The Phrygian Kingdom of central Anatolia (~1200–546 BCE) rose to prominence following the collapse of the Hittite Empire and at its height under King Midas controlled much of Asia Minor. The Phrygians contributed significantly to Aegean and Near Eastern culture: their music (the Phrygian mode), their goddess Cybele — the Great Mother — who was later adopted by Greece and Rome, and their distinctive carved rock facades and tumulus burials. King Midas is a historical figure whose legendary golden touch may encode memory of Phrygia's genuine mineral wealth. The kingdom was absorbed into the Lydian and subsequently Persian empires, though Phrygian religious traditions survived for centuries in Greek and Roman mystery cult practices." },

  { id:403, n:"Lydian Empire", r:"Middle East", t:"confirmed",
    s:-700, e:-546, p:600000, lang:"lydian", gov:"monarchy",
    d:"The Lydian Empire of western Anatolia (~700–546 BCE) is credited by Herodotus with the invention of coinage — the first known use of stamped electrum coins as a standardised medium of exchange, an innovation that transformed commerce across the ancient world. Under King Croesus, Lydia achieved extraordinary wealth and became a major diplomatic player, seeking alliances with Greece and Egypt against the rising Persian threat. The Lydians developed sophisticated trade networks, legal institutions, and a material culture of considerable refinement. Croesus's famous exchange with Solon about happiness and his disastrous campaign against Cyrus the Great of Persia, which ended Lydian independence, became a foundational story in Greek philosophy about the limits of wealth and the unpredictability of fate." },

  { id:404, n:"Khazar Khaganate", r:"Europe", t:"confirmed",
    s:650, e:969, p:1000000, lang:"turkic-khazar", gov:"khaganate",
    d:"The Khazar Khaganate (~650–969 CE) was a major Turkic semi-nomadic empire controlling the strategically vital steppes between the Black Sea and the Caspian Sea, acting for centuries as a buffer between the expanding Islamic Caliphates and Eastern Europe. Most remarkably, the Khazar ruling elite converted to Judaism in the 8th–9th century CE — the only significant political conversion to Judaism in post-biblical history — while the general population encompassed Muslims, Christians, and pagans in notable religious pluralism. The Khazars controlled lucrative trade routes linking the Byzantine Empire, the Abbasid Caliphate, and the Rus. Arthur Koestler's controversial 1976 thesis in The Thirteenth Tribe proposed Khazar Jewish converts as a significant demographic ancestor of Ashkenazi Jews, a claim that remains debated in population genetics." },

  { id:405, n:"Tocharian Civilisation", r:"Asia", t:"confirmed",
    s:-2000, e:900, p:200000, lang:"tocharian", gov:"city-state",
    d:"The Tocharians were an Indo-European-speaking people of the Tarim Basin in present-day western China, known from Buddhist texts and manuscripts in two related languages (Tocharian A and B) discovered in oasis towns along the northern Silk Road. Their physical remains — mummies preserved in the desert conditions of the Tarim Basin dating to ~2000 BCE — show strikingly Western features including red and blonde hair, confounding early assumptions about population movements into Central Asia. The Tocharian languages are linguistically closest to Celtic and Italic branches of Indo-European, suggesting an ancient migration from western Eurasia. The Tocharians served as cultural intermediaries transmitting Buddhism, art traditions, and technologies between India, Iran, China, and the steppe world before Turkic expansion absorbed their communities." },

  { id:406, n:"Sogdian Merchant Network", r:"Asia", t:"confirmed",
    s:300, e:1000, p:300000, lang:"sogdian", gov:"merchant-republic",
    d:"The Sogdians of ancient Transoxiana (present-day Uzbekistan and Tajikistan) built one of the ancient world's most remarkable commercial civilisations — not through military conquest but through mercantile genius. From approximately 300–1000 CE, Sogdian merchants dominated the Silk Road trade from China to Byzantium, establishing diaspora trading colonies across Central Asia and into Tang Dynasty China. Sogdian letters discovered near Dunhuang dating to ~313 CE are the earliest known merchant correspondence from the Silk Road. The Sogdians transmitted Buddhism, Zoroastrianism, Manichaeism, and Christianity along their trade routes, as well as technologies including papermaking, silk weaving, and musical instruments. Their script directly influenced the development of the Uyghur, Mongolian, and Manchu writing systems, giving them an outsized linguistic legacy far beyond their political power." },

  { id:407, n:"Mississippian Culture — Moundville", r:"Americas", t:"confirmed",
    s:1000, e:1450, p:10000, lang:"muskogean", gov:"chiefdom",
    d:"Moundville in present-day Alabama was the second-largest Mississippian urban centre after Cahokia, reaching its peak between 1000–1350 CE with a population of approximately 10,000 and covering 300 acres along the Black Warrior River. The site features 29 platform mounds arranged around a central plaza, with the largest mounds associated with elite residences and mortuary facilities. Moundville's material culture — particularly its engraved shell gorgets and ceramics depicting a distinctive iconographic system scholars call the Southeastern Ceremonial Complex — reveals a sophisticated cosmological and political programme shared across the Mississippian world. The site appears to have transitioned from a densely inhabited urban centre to a largely vacant mortuary precinct by around 1300 CE, suggesting a deliberate ceremonial reorganisation rather than simple decline." },

  { id:408, n:"Hopewell Interaction Sphere", r:"Americas", t:"confirmed",
    s:-100, e:500, p:50000, lang:"various-eastern-woodlands", gov:"chiefdom-network",
    d:"The Hopewell Interaction Sphere (~100 BCE–500 CE) was not a single civilisation but a remarkable continent-spanning exchange network centred in the Ohio and Illinois river valleys, through which prestige goods, religious ideas, and mortuary practices were shared across an area stretching from the Rocky Mountains to the Atlantic coast. Hopewell earthworks — geometric enclosures of extraordinary precision and scale, some covering four square miles — served as ceremonial gathering sites rather than permanent settlements. Hopewell burial mounds contain objects of copper from the Great Lakes, obsidian from Yellowstone, mica from the Appalachians, shark teeth from the Gulf Coast, and grizzly bear skulls from the Rockies, demonstrating trade networks of continental scope. The collapse of Hopewell around 500 CE remains one of North American archaeology's most debated questions." },

  { id:409, n:"Poverty Point", r:"Americas", t:"confirmed",
    s:-1700, e:-1100, p:5000, lang:"unknown", gov:"chiefdom",
    d:"Poverty Point in present-day Louisiana (~1700–1100 BCE) is one of the most extraordinary and enigmatic sites in North American prehistory — a massive earthwork complex built by hunter-gatherers at a time when no agricultural civilisation was thought possible in the region. The site features six concentric C-shaped ridges, each containing house sites, surrounding a central plaza, plus several large mounds, covering an area of approximately 400 acres. Poverty Point was a major regional trade hub, with materials arriving from sources across eastern North America. The site challenges the assumption that monumental architecture requires agriculture: like Göbekli Tepe in a different context, Poverty Point demonstrates that hunter-gatherer social organisation could generate the collective labour and planning necessary for large-scale construction. Its origins and the identity of its builders remain incompletely understood." },

  { id:410, n:"Tiwanaku Empire", r:"Americas", t:"confirmed",
    s:500, e:1000, p:400000, lang:"puquina", gov:"theocracy",
    d:"The Tiwanaku Empire (~500–1000 CE) centred at its eponymous capital on the Bolivian Altiplano at 3,850 metres elevation — one of the highest urban centres in the ancient world — developed an sophisticated state religion and agricultural system that sustained populations across the harsh high-altitude environment of the Andes. Tiwanaku's raised field (suka kollus) agriculture transformed the marshy shores of Lake Titicaca into highly productive farmland through an ingenious system of water channels that regulated temperature and moisture. The site's monumental Gateway of the Sun, megalithic stone architecture, and distinctive iconography — particularly the Staff God figure — spread across the Andean world and persisted long after Tiwanaku's political collapse. Arthur Posnansky controversially dated Tiwanaku's astronomical alignments to ~15,000 BCE; mainstream archaeology dates the monumental phase to 500–900 CE." },

  { id:411, n:"Chimú Empire", r:"Americas", t:"confirmed",
    s:900, e:1470, p:500000, lang:"mochica", gov:"monarchy",
    d:"The Chimú Empire of coastal Peru (~900–1470 CE) was the largest and most sophisticated Pre-Columbian state on the Pacific coast of South America before the Inca, controlling 1,000km of coastline from its magnificent capital Chan Chan — the largest pre-Columbian city in South America, covering 20 square kilometres of interlocking royal compounds (ciudadelas), with walls up to 9 metres high. The Chimú were master metalworkers in gold, silver, and bronze, and their hydraulic engineering — long irrigation canals stretching up to 70km through desert terrain — sustained dense agricultural populations in one of the world's driest environments. They were eventually conquered by the Inca around 1470 CE, who reportedly deported Chimú craftsmen to Cusco to work for the Inca state, transmitting Chimú metallurgical techniques that defined the gold and silver work the Spanish later encountered." },

  { id:412, n:"Mississippian Culture — Spiro Mounds", r:"Americas", t:"confirmed",
    s:800, e:1450, p:2000, lang:"caddoan", gov:"chiefdom",
    d:"Spiro Mounds in present-day Oklahoma was the westernmost major centre of the Mississippian Southeastern Ceremonial Complex, a ceremonial site of extraordinary significance that served as a mortuary and ritual hub for a vast regional network spanning the Southern Plains and the Southeast. The Craig Mound at Spiro contained one of the richest concentrations of Mississippian ceremonial objects ever found — carved shell cups, engraved conch shells, copper plates, effigy pipes, and cedar litter poles — but it was catastrophically looted by commercial diggers between 1933–1935 before scientific excavation could begin, destroying irreplaceable archaeological context. What survived demonstrated that Spiro was a major redistribution centre for prestige goods and a site of intense religious activity connecting the Plains world to the broader Mississippian system, challenging assumptions about the cultural boundaries between these two traditions." },

  { id:413, n:"Zapotec Civilisation", r:"Americas", t:"confirmed",
    s:-500, e:700, p:25000, lang:"zapotec", gov:"city-state",
    d:"The Zapotec civilisation of the Valley of Oaxaca in southern Mexico (~500 BCE–700 CE) developed one of Mesoamerica's earliest writing systems — still incompletely deciphered — and built Monte Albán, a hilltop urban centre of extraordinary ambition that dominated Oaxacan politics for over a millennium. The Zapotecs were among the first Mesoamerican peoples to use a 365-day solar calendar alongside a 260-day ritual calendar, anticipating the Calendar Round system later elaborated by the Maya. Monte Albán's Building J, an arrow-shaped structure aligned to the setting of the star Capella, demonstrates sophisticated astronomical observation. The Zapotecs also developed distinctive funerary urn traditions and a religion centred on the deity Cocijo, god of lightning and rain. Their civilisation preceded and in some respects influenced Teotihuacan, with evidence of diplomatic and trade contact between the two major powers." },

  { id:414, n:"Mixtec Civilisation", r:"Americas", t:"confirmed",
    s:900, e:1521, p:150000, lang:"mixtec", gov:"city-state",
    d:"The Mixtec civilisation of highland Oaxaca and the Mixteca Alta (~900–1521 CE) produced some of the finest manuscript painting in the pre-Columbian world — the Mixtec codices (screenfold books) including the Codex Zouche-Nuttall and Codex Vindobonensis record detailed dynastic histories, genealogies, and ritual calendars stretching back centuries. Mixtec goldwork, turquoise mosaic, and carved bone achieved technical standards that astonished the Spanish conquistadors, and many of the finest objects in early colonial European collections of 'Mexican' art are Mixtec in origin or heavily Mixtec-influenced. The historical figure Lord Eight Deer Jaguar Claw, whose life and military career are recorded in multiple codices, represents one of the most fully documented individuals in pre-Columbian American history. The Mixtecs were never fully conquered by the Aztec Triple Alliance and maintained considerable political autonomy until Spanish contact." },

  { id:415, n:"Aksumite Predecessor — D'mt Kingdom", r:"Africa", t:"debated",
    s:-800, e:-400, p:100000, lang:"ge-ez-proto", gov:"monarchy",
    d:"The D'mt Kingdom of the northern Ethiopian Highlands and Eritrea (~800–400 BCE) is one of the earliest known complex states in sub-Saharan Africa and the least understood predecessor to the Aksumite civilisation, with which it shares geographic space and possibly cultural continuity. D'mt inscriptions in a South Arabian script and the presence of South Arabian material culture have generated significant debate about whether D'mt was a South Arabian colony, an indigenous African state that adopted South Arabian writing, or a hybrid polity arising from sustained contact across the Red Sea. Archaeological sites including Yeha — with its remarkable pre-Aksumite temple of possibly 7th century BCE date — demonstrate architectural and cultural sophistication well beyond what colonial-era scholarship attributed to the region. Mainstream scholarship continues to reassess D'mt's relationship to Aksumite origins and the broader question of Red Sea cross-cultural interaction." },

  { id:416, n:"Garamantian Civilisation", r:"Africa", t:"confirmed",
    s:-500, e:700, p:100000, lang:"berber-garamantian", gov:"monarchy",
    d:"The Garamantes of the central Sahara (present-day Fezzan, Libya) built one of the ancient world's most extraordinary hydraulic engineering feats entirely beneath the Saharan desert: a network of underground irrigation tunnels (foggaras) stretching over 3,500km total length, tapping fossil water aquifers to irrigate oasis agriculture in one of Earth's most hostile environments. At the height of their power (~1st–3rd century CE) the Garamantes controlled trans-Saharan trade routes connecting sub-Saharan Africa to the Roman Mediterranean, trading in gold, slaves, exotic animals, and precious stones. Roman military expeditions against the Garamantes document them as a major regional power, not a simple tribal society. Their civilisation collapsed as the fossil aquifers were depleted, a cautionary case study in non-renewable resource dependency that has resonances with modern desert agriculture." },

  { id:417, n:"Nok Civilisation", r:"Africa", t:"confirmed",
    s:-1000, e:300, p:150000, lang:"benue-congo-proto", gov:"chiefdom",
    d:"The Nok culture of central Nigeria (~1000 BCE–300 CE) produced the earliest known sub-Saharan African terracotta sculpture tradition — life-sized and near-life-sized human heads and figures of striking naturalism and technical sophistication, fired at temperatures requiring considerable ceramic expertise. The Nok people also practised iron smelting from approximately 500 BCE, making them among the earliest iron-using cultures in Africa, though debate continues about whether their metallurgical knowledge was independently developed or transmitted from North Africa. Despite a century of scholarship, fundamental questions about Nok political organisation, language, and relationship to later Nigerian cultures including the Ife and Benin bronze traditions remain open. Many Nok terracottas have been illegally excavated and traded on the international art market, severely limiting archaeological context for what survive in institutional collections." },

  { id:418, n:"Swahili City-States", r:"Africa", t:"confirmed",
    s:800, e:1500, p:200000, lang:"swahili-proto", gov:"merchant-republic",
    d:"The Swahili city-states of the East African coast — including Kilwa Kisiwani, Mombasa, Malindi, Pate, and Zanzibar — formed between approximately 800–1500 CE one of the Indian Ocean world's most prosperous commercial networks, linking the gold and ivory of inland Africa to Arabia, Persia, India, and eventually China. Ibn Battuta, visiting Kilwa in 1331 CE, described it as one of the most beautiful cities in the world. Chinese Ming Dynasty records document the famous 1418–1422 voyages of Zheng He reaching the East African coast, with East African envoys bringing giraffes to the Chinese imperial court. Swahili material culture is a genuine synthesis of African, Arab, Persian, and Indian influences, producing a distinctive architectural tradition of coral-stone towns, carved wooden doors, and mosque typologies. The Portuguese arrival in 1498 began the violent disruption of this system." },

  { id:419, n:"Great Zimbabwe — Extended Kingdom", r:"Africa", t:"confirmed",
    s:1100, e:1420, p:18000, lang:"shona-proto", gov:"monarchy",
    d:"The Great Zimbabwe kingdom — centred on the remarkable dry-stone walled enclosure complex of Great Zimbabwe in present-day Zimbabwe, the largest pre-colonial stone structure south of the Sahara — controlled the gold trade routes between the interior of southern Africa and the Swahili Coast ports at its height between approximately 1250–1420 CE. The Great Enclosure's massive walls, some reaching 11 metres in height and 5 metres thick, were constructed without mortar using a sophisticated interlocking granite block technique. Colonial-era scholars systematically denied African origins for the structure, attributing it variously to Phoenicians, Arabs, or the Queen of Sheba — attributions now entirely rejected by archaeology. The kingdom's collapse around 1420 CE appears linked to the southward migration of political and trade power toward the emerging Mutapa state and possibly to resource depletion in the surrounding region." },

  { id:420, n:"Hyperborea", r:"Europe", t:"theorized",
    s:-50000, e:-10000, p:0, lang:"unknown", gov:"unknown",
    d:"Hyperborea — literally 'Beyond the North Wind' — appears in ancient Greek tradition as a land of perfect climate and immortal, blessed people located far to the north, beyond Boreas the north wind. Pindar, Herodotus, Hecataeus of Abdera, and Pliny all mention Hyperborea in varying degrees of literalism, and the Hyperboreans are associated with the worship of Apollo, whose mythology contains strong northern elements suggesting possible origins in an older tradition. In alternative archaeology, Hyperborea is proposed as a memory of a pre-Younger Dryas Arctic or sub-Arctic civilisation made habitable by a different climate regime or crustal configuration. Charles Hapgood's crustal displacement hypothesis specifically links Hyperborea to a pre-displacement polar configuration. The mainstream scholarly consensus treats Hyperborea as mythological. The persistence and consistency of the tradition across multiple ancient cultures raises questions about what historical kernel, if any, underlies it." },

  { id:421, n:"Tartaria / Proto-Writing Culture", r:"Europe", t:"debated",
    s:-5500, e:-3500, p:0, lang:"unknown", gov:"unknown",
    d:"The Tartaria tablets — three clay tablets bearing inscribed signs discovered at Tartaria in Romania in 1961, radiocarbon-dated to approximately 5300 BCE — are among the most contested objects in the archaeology of writing, predating the earliest accepted Sumerian writing by over a millennium if their dates are genuine. Romanian archaeologist Nicolae Vlassa, who excavated the tablets, claimed they bore resemblance to early Sumerian proto-cuneiform. Subsequent scholars have argued the signs represent a local Vinča culture symbolic system (sometimes called the Danube Script or Old European Script) rather than true writing, and that no phonetic or semantic decoding is possible. The broader Vinča culture of southeastern Europe (~5700–4500 BCE) produced hundreds of incised signs on pottery that some researchers — including Marija Gimbutas and Harald Haarmann — argue constitute an independent writing system predating Near Eastern writing. The debate remains unresolved and has significant implications for our understanding of cognitive development and cultural transmission in prehistoric Europe." },

  { id:422, n:"Mu / Lemuria", r:"Oceania", t:"theorized",
    s:-200000, e:-10000, p:0, lang:"unknown", gov:"unknown",
    d:"Lemuria was coined as a geological hypothesis by zoologist Philip Sclater in 1864 to explain the distribution of lemur fossils across India, Madagascar, and southeastern Africa — proposing a now-sunken landmass connecting these regions. The geological basis was superseded by plate tectonics. The concept was subsequently taken up by Madame Blavatsky in The Secret Doctrine (1888) as the realm of humanity's third 'root race,' and by Colonel James Churchward in The Lost Continent of Mu (1926) as an advanced Pacific civilisation. In alternative archaeology, Mu/Lemuria is proposed as a Pacific or Indian Ocean precursor civilisation destroyed by geological or cosmic catastrophe. Stephen Oppenheimer's Sundaland thesis offers a geologically defensible version of a significant Indo-Pacific landmass lost to post-glacial sea-level rise. The concept of Lemuria as an advanced civilisation rests on no archaeological evidence, though the genuine submergence of vast coastal and island territories during deglaciation remains an important context for evaluating origin myths across Pacific and Indian Ocean cultures." },

  { id:423, n:"Vedic Golden Age / Satya Yuga", r:"Asia", t:"theorized",
    s:-3900000, e:-1200000, p:0, lang:"vedic-sanskrit", gov:"unknown",
    d:"The Vedic conception of cyclical time — the Yuga system recorded in the Mahabharata, Puranas, and other Sanskrit texts — describes the Satya Yuga (Golden Age) as a period of perfect dharma, longevity, and spiritual achievement lasting 1,728,000 years, followed by progressively declining ages culminating in the current Kali Yuga of darkness and moral decline. Sri Yukteswar in The Holy Science (1894) proposed an alternative calculation placing the current era at the beginning of an ascending Dwapara Yuga rather than deep within the Kali Yuga, based on a different interpretation of the astronomical cycle. David Frawley's work in Gods, Sages and Kings (1991) argues that Vedic astronomical references encode genuine observations from the third and fourth millennia BCE, suggesting a much older origin for Sanskrit astronomical knowledge than mainstream Indology accepts. Giorgio de Santillana's Hamlet's Mill (1969) connects Vedic mythological cycles to precessional astronomy. Whether the Yuga system encodes genuine astronomical cycles, historical memory, or purely spiritual symbolism remains a central question in Vedic studies." },

  { id:424, n:"Polynesian Navigation Civilisation", r:"Oceania", t:"confirmed",
    s:-1000, e:1300, p:300000, lang:"proto-polynesian", gov:"chiefdom-network",
    d:"The Polynesian expansion across the Pacific Ocean (~1000 BCE–1300 CE) represents the greatest maritime achievement in human history prior to European oceanic exploration — a deliberate, systematic colonisation of the largest ocean on Earth using only double-hulled canoes, traditional navigation knowledge, and the stars. From a homeland in western Polynesia, Polynesian navigators settled Hawaii (~300–500 CE), Easter Island/Rapa Nui (~300–500 CE), and New Zealand (~1250–1300 CE), as well as hundreds of island groups across 10 million square kilometres of open ocean. Polynesian wayfinding used star paths, ocean swell patterns, cloud formations, bird behaviour, bioluminescence, and wind direction — a comprehensive environmental reading system maintained entirely in oral and embodied tradition. Thor Heyerdahl's Kon-Tiki experiment proposed significant South American contact with Polynesia, a claim now supported by genetic evidence of pre-Columbian Polynesian-South American admixture in eastern Polynesian populations." },

  { id:425, n:"Chamorro / Mariana Islands Civilisation", r:"Oceania", t:"confirmed",
    s:-1500, e:1668, p:50000, lang:"chamorro", gov:"chiefdom",
    d:"The Chamorro people of the Mariana Islands in the western Pacific developed one of the most distinctive architectural traditions in Oceania — the latte stone structures, consisting of pairs of massive limestone or coral stone pillars topped with hemispherical capstones, which served as foundation supports for elite residences and communal structures. The largest latte stones at the House of Taga on Tinian stand over 4.5 metres tall and weigh up to 30 tonnes, requiring significant collective engineering capability. The Chamorros maintained a stratified society with a hereditary noble class (matao) and complex kinship and ritual systems. Spanish colonial contact from 1668 brought devastating population collapse through introduced disease and deliberate military violence — the Chamorro population fell from an estimated 50,000–100,000 to fewer than 5,000 within decades, one of history's most catastrophic colonial depopulations." },

  { id:426, n:"Mississippian Culture — Angel Mounds", r:"Americas", t:"confirmed",
    s:1100, e:1450, p:3000, lang:"various-ohio-valley", gov:"chiefdom",
    d:"Angel Mounds in present-day Indiana was one of the largest Mississippian settlements in the Ohio River valley, with a peak population of approximately 3,000 people within a 103-acre palisaded town containing 11 earthen mounds of varying sizes. The site demonstrates the remarkable standardisation of Mississippian town planning — a central plaza flanked by platform mounds for elite and ceremonial use, surrounded by domestic areas and enclosed by a defensive wooden palisade — replicated with local variations across hundreds of sites from Wisconsin to Florida. Angel Mounds was occupied from approximately 1100–1450 CE and its abandonment, like that of Cahokia and other major Mississippian centres, coincides with a period of regional climate instability associated with the transition out of the Medieval Warm Period, suggesting environmental stress as a contributing factor to Mississippian civilisational reorganisation." },

  { id:427, n:"Wari Empire", r:"Americas", t:"confirmed",
    s:600, e:1000, p:200000, lang:"proto-quechuan", gov:"empire",
    d:"The Wari Empire of the Peruvian highlands (~600–1000 CE) was the first true expansionist state in Andean South America, developing administrative techniques — including road systems, storage facilities (qollqas), and provincial centres — that the Inca later adopted and scaled to create their own empire. Wari influence extended across much of modern Peru, from the north coast to the Lake Titicaca basin, and the iconographic system they shared with Tiwanaku (the Staff God complex) suggests intense interaction with that contemporaneous Altiplano state, though the nature of the Wari-Tiwanaku relationship — complementary, competitive, or synergistic — remains debated. The Wari administrative system, particularly their use of structured storage and standardised architecture to project state power across diverse ecological zones, represents a genuinely original political innovation that shaped Andean civilisation for the next five centuries." },

  { id:428, n:"Ancestral Puebloans — Chaco Canyon Extended", r:"Americas", t:"confirmed",
    s:850, e:1150, p:5000, lang:"proto-puebloan", gov:"theocracy",
    d:"Chaco Canyon in present-day New Mexico served as the ritual and administrative centre of the Ancestral Puebloan world at its height (~850–1150 CE), with Great Houses — massive multi-storey stone buildings of extraordinary precision including Pueblo Bonito's 650+ rooms — connected to a 650-kilometre network of engineered roads radiating across the Colorado Plateau. The roads, running in mathematically straight lines regardless of topography and sometimes leading to no obvious destination, suggest a ceremonial rather than purely logistical function. Astronomical alignments at Chaco — including the famous Sun Dagger site on Fajada Butte and solar and lunar alignments built into the great house architecture — demonstrate sophisticated astronomical observation integrated into political-religious authority. The depopulation of Chaco around 1150 CE, coinciding with a prolonged drought documented in tree-ring records, has become a widely-cited case study in civilisational climate vulnerability." },

  { id:429, n:"Mississippian Culture — Etowah", r:"Americas", t:"confirmed",
    s:1000, e:1550, p:5000, lang:"muskogean-proto", gov:"chiefdom",
    d:"Etowah Mounds in present-day Georgia was one of the most important political and ceremonial centres of the Mississippian world, featuring six earthen mounds including Mound A — the third-largest Mississippian mound in North America at 19 metres tall — surrounding a central plaza in the classic Mississippian town plan. Etowah is particularly renowned for the quality of its Southeastern Ceremonial Complex objects: marble statues of seated male and female figures of extraordinary technical refinement, embossed copper plates depicting costumed ritual performers, and engraved shell gorgets displaying a complex iconographic vocabulary shared across the Mississippian world. The site experienced multiple occupation phases, with evidence of deliberate burning and rebuilding between periods suggesting cyclical political reorganisation. European contact and the diseases that preceded it likely contributed to the final abandonment of the site in the mid-16th century." },

  { id:430, n:"Dorset / Pre-Dorset Arctic Culture", r:"Americas", t:"confirmed",
    s:-2500, e:1500, p:20000, lang:"paleo-eskimo", gov:"band",
    d:"The Dorset culture (~500 BCE–1500 CE) and its predecessor the Pre-Dorset (~2500–500 BCE) represent the primary human occupation of the Canadian Arctic and Greenland before the arrival of Thule Inuit ancestors from Alaska around 1000 CE. The Dorset people — known as the Tunit in Inuit oral tradition, described as a race of giants of great strength — were highly specialised Arctic hunters who subsisted primarily on ringed seals, walrus, and caribou in one of Earth's most demanding environments. Their material culture shows no evidence of dog sleds (they pulled sleds themselves), bows and arrows, or boats capable of open-water hunting — technological absences that made them vulnerable to Thule replacement. Ancient DNA analysis has confirmed Dorset people were genetically distinct from all living Arctic populations, representing a separate migration wave from Siberia. Their oral memory preservation in Inuit tradition as the Tunit represents one of the few cases of documented Indigenous memory of a now-extinct human population." },
  // END PHASE 5z
];
