// ════════════════════════════════════════════════════════════════════════════
// PHASE 5aa — APPEND TO data.js
// Civilizations 431–460
// ════════════════════════════════════════════════════════════════════════════
//
// INSTRUCTIONS (owner):
//   1. Open your local data.js
//   2. Find the very last closing  ];  at the bottom
//   3. Replace that  ];  with a comma, then paste ALL lines below it
//      (these entries already end with the correct closing bracket)
//
// ════════════════════════════════════════════════════════════════════════════

// ── PHASE 5aa — Civilizations 431–460 ─────────────────────────────────────
// Append these entries to the end of the CIVS array in data.js
// APPEND-ONLY — do not modify any existing records

  { id:431, n:"Timurid Empire", r:"Asia", t:"confirmed",
    s:1370, e:1507, p:5000000, lang:"chagatai-turkic", gov:"empire",
    d:"The Timurid Empire (~1370–1507 CE), founded by Timur (Tamerlane) and centred on Samarkand in present-day Uzbekistan, was simultaneously one of the most destructive military forces in history and one of its most extraordinary patrons of art, architecture, and learning. Timur's campaigns killed an estimated 17 million people — roughly 5% of the world's population at the time — yet his capital Samarkand became the intellectual and artistic capital of the Islamic world, with the Registan complex representing the pinnacle of Timurid architectural achievement. His descendant Babur founded the Mughal Empire in India, and Timurid court culture directly shaped Mughal aesthetics. The astronomical observatory of Ulugh Beg at Samarkand produced star catalogues of extraordinary precision that were not surpassed in Europe for over a century." },

  { id:432, n:"Majapahit Empire", r:"Asia", t:"confirmed",
    s:1293, e:1527, p:1000000, lang:"old-javanese", gov:"empire",
    d:"The Majapahit Empire (~1293–1527 CE) of Java was the last and greatest of the Hindu-Buddhist maritime empires of Southeast Asia, at its height controlling or receiving tribute from much of the Indonesian archipelago, the Malay Peninsula, and parts of the Philippines — an empire of islands and sea lanes rather than contiguous territory. The 14th-century prime minister Gajah Mada's Palapa Oath — to unify the archipelago before tasting spiced coconut — is still invoked in Indonesian national identity, and the modern Indonesian satellite system is named Palapa in his honour. Majapahit's decline in the 15th century, linked to the spread of Islam through Malaccan trade networks, produced the diaspora of Hindu-Javanese court culture to Bali, where it survives to the present day. The degree to which Majapahit constituted a true empire versus a tribute-receiving hegemon remains debated by historians of Southeast Asia." },

  { id:433, n:"Khmer Empire", r:"Asia", t:"confirmed",
    s:802, e:1431, p:1000000, lang:"khmer", gov:"empire",
    d:"The Khmer Empire (~802–1431 CE) of mainland Southeast Asia built Angkor — the largest pre-industrial urban complex in the world, covering an area greater than modern Los Angeles — sustained by an extraordinarily sophisticated hydraulic system of reservoirs (barays), canals, and rice paddies that supported a population of perhaps one million in the Angkor region alone. Angkor Wat, built by Suryavarman II in the 12th century CE, remains the largest religious monument ever constructed. Recent lidar surveys have revealed the full extent of Greater Angkor's urban infrastructure, demonstrating a dispersed low-density urbanism of a type completely invisible to ground-level archaeology. The collapse of the Khmer Empire in the 15th century appears linked to the failure of this hydraulic system under climate stress, offering a well-documented case study in civilisational vulnerability to water management breakdown." },

  { id:434, n:"Srivijaya Empire", r:"Asia", t:"confirmed",
    s:650, e:1375, p:500000, lang:"old-malay", gov:"thalassocracy",
    d:"The Srivijaya Empire (~650–1375 CE), centred on Palembang in southern Sumatra, was the dominant maritime power of Southeast Asia for over seven centuries — not through territorial control but through command of the Strait of Malacca, the chokepoint through which virtually all seaborne trade between China and India passed. Srivijaya was also a major centre of Buddhist learning; the Chinese monk Yijing studied Sanskrit grammar there before travelling to India, and the empire maintained close diplomatic and religious ties with both the Tang Dynasty and the Pala Empire of Bengal. The Srivijayan model of power — controlling trade routes rather than agricultural hinterlands, projecting authority through tributary relationships rather than military garrisons — represents a distinct civilisational form that anticipates later Malaccan and colonial trading empire structures. The empire's core sites remain poorly excavated due to the tropical conditions that dissolve organic material and the continued occupation of its heartland." },

  { id:435, n:"Vijayanagara Empire", r:"Asia", t:"confirmed",
    s:1336, e:1646, p:2500000, lang:"kannada-telugu", gov:"empire",
    d:"The Vijayanagara Empire (~1336–1646 CE) of southern India was the last great Hindu empire of the subcontinent, acting for over two centuries as the primary bulwark against the southward expansion of the Deccan Sultanates and preserving a distinctive Dravidian cultural, religious, and artistic tradition. Its capital Hampi, on the banks of the Tungabhadra River, was one of the largest cities in the world at its height — a metropolitan centre of temples, market streets, elephant stables, and royal pavilions spread across a surreal landscape of giant granite boulders. The Battle of Talikota in 1565 CE brought a coalition of Deccan Sultanates against Vijayanagara; the capital was sacked and largely destroyed within months, ending the empire's political dominance. Hampi's ruins are now a UNESCO World Heritage Site, their scale still communicating the extraordinary ambition of the civilisation that built them." },

  { id:436, n:"Mississippian Culture — Cahokia Monks Mound", r:"Americas", t:"confirmed",
    s:900, e:1350, p:20000, lang:"various-siouan", gov:"chiefdom",
    d:"Monks Mound at Cahokia in present-day Illinois is the largest pre-Columbian earthwork in North America — a four-terraced platform mound covering 5.6 hectares at its base and standing 30 metres tall, built entirely of basket-carried earth over several centuries of construction beginning around 900 CE. The mound supported a large wooden structure at its summit, almost certainly the residence of Cahokia's paramount chief or priest-king. Timothy Pauketat's excavations and synthesis in Cahokia (2009) have reconstructed a sophisticated political and religious system centred on Monks Mound, with the city's layout encoding astronomical alignments and a cosmological programme. A massive wooden post circle (Woodhenge) to the west of Monks Mound functioned as a solar calendar. The mound complex is directly comparable in engineering effort to the construction of the smaller Egyptian pyramids, achieved without metal tools, wheeled vehicles, or draft animals." },

  { id:437, n:"Toltec Civilisation", r:"Americas", t:"confirmed",
    s:800, e:1150, p:60000, lang:"nahuatl-proto", gov:"city-state",
    d:"The Toltec civilisation (~800–1150 CE) centred at Tula (Tollan) in the Valley of Mexico was the dominant Mesoamerican political power in the early post-Classic period and exerted a cultural influence far beyond its immediate territory. The Toltecs are credited in later Aztec tradition as the originators of civilisation itself — craftsmen, astronomers, and warriors of legendary skill — though archaeology reveals a more ambiguous picture of a militaristic city-state whose imagery of warriors, sacrifice, and feathered serpents was adopted and transformed by both the Maya at Chichén Itzá and the later Aztec empire. The apparent presence of Toltec-style warrior columns and feathered serpent imagery at Chichén Itzá in the Yucatán — 1,500km from Tula — is one of Mesoamerican archaeology's most discussed long-distance cultural connections. The mechanism — migration, elite exchange, or parallel development — remains contested." },

  { id:438, n:"Mississippian Culture — Kincaid", r:"Americas", t:"confirmed",
    s:1000, e:1450, p:2000, lang:"various-ohio-valley", gov:"chiefdom",
    d:"Kincaid Mounds in present-day southern Illinois was one of the northernmost major Mississippian centres, a significant regional capital featuring at least 19 platform mounds arranged around multiple plazas within a palisaded town. Kincaid's position at the confluence of the Ohio, Tennessee, and Cumberland rivers placed it at one of the most strategically valuable locations in the Mississippian world for controlling river-borne trade across the Eastern Woodlands. Archaeological evidence suggests Kincaid maintained exchange relationships with Cahokia to the north and with Southeastern Ceremonial Complex centres to the south, serving as a redistribution node for prestige goods. Like most major Mississippian centres, Kincaid was abandoned well before European contact, and the exact causes — whether demographic, climatic, or political — remain subjects of active research. The site represents the northernmost extent of the classic Mississippian town planning formula." },

  { id:439, n:"Aksumite Civilisation (Extended)", r:"Africa", t:"confirmed",
    s:-100, e:940, p:300000, lang:"ge-ez", gov:"empire",
    d:"The Aksumite civilisation of the northern Ethiopian Highlands and Eritrea (~100 BCE–940 CE) was one of the great empires of the ancient and medieval world — a major commercial hub on the Red Sea trade routes linking Rome, Arabia, India, and sub-Saharan Africa, and the first sub-Saharan African state to mint its own coins. Under King Ezana in the 4th century CE, Aksum became one of the earliest states in history to adopt Christianity as a state religion, preceding the Roman Empire's full Christianisation and establishing the Ethiopian Orthodox Church that continues to the present. Aksumite stelae — massive carved obelisks, the tallest of which stood 33 metres — are among the most extraordinary monuments of the ancient world. The Ark of the Covenant is claimed by Ethiopian Orthodox tradition to rest in the Chapel of the Tablet in Aksum, a claim taken seriously by some scholars and dismissed by others but central to Ethiopian Christian identity." },

  { id:440, n:"Dahomey Kingdom", r:"Africa", t:"confirmed",
    s:1600, e:1894, p:250000, lang:"fon", gov:"monarchy",
    d:"The Kingdom of Dahomey (~1600–1894 CE) in present-day Benin was one of West Africa's most powerful and distinctive states, known for its highly centralised administration, its professional standing army, and most remarkably its corps of female soldiers — the Agojie (known to Europeans as the Dahomey Amazons) — an elite military unit of thousands of women who served as the king's personal bodyguard and front-line troops for over two centuries. Dahomey's economy was deeply entangled with the transatlantic slave trade; the kingdom raided neighbouring peoples and sold captives to European traders, accumulating the wealth that funded its military and architectural ambitions. The annual customs ceremony involved lavish gift distribution and human sacrifice, documented by European observers. Dahomey was conquered by France in 1894 after two military campaigns that the Agojie fiercely contested. The kingdom's complex legacy — militarily sophisticated African statehood intertwined with its role in the slave trade — continues to generate significant historical debate." },

  { id:441, n:"Kingdom of Kongo", r:"Africa", t:"confirmed",
    s:1390, e:1914, p:2000000, lang:"kikongo", gov:"monarchy",
    d:"The Kingdom of Kongo (~1390–1914 CE), centred in present-day northern Angola, western DRC, and the Republic of Congo, was one of the largest and most sophisticated states in sub-Saharan African history, with a complex administrative system, a currency based on nzimbu shells, a professional diplomatic corps, and an extensive road network radiating from the capital Mbanza Kongo. When Portuguese explorers arrived in 1483, they encountered a state sophisticated enough to engage as a diplomatic equal — King João I of Kongo converted to Christianity, sent ambassadors to Lisbon and Rome, and maintained a multilingual royal court. The Kingdom of Kongo was not conquered in the conventional sense; it was progressively undermined by the slave trade, internal succession conflicts partly fomented by Portuguese interference, and eventual colonial partition in the late 19th century. Its history challenges the colonial narrative of pre-contact sub-Saharan Africa as stateless and primitive." },

  { id:442, n:"Mississippian Culture — Lake Jackson", r:"Americas", t:"confirmed",
    s:1050, e:1500, p:2000, lang:"muskogean-proto", gov:"chiefdom",
    d:"Lake Jackson Mounds in present-day Tallahassee, Florida, was the paramount Mississippian centre of the Apalachee chiefdom — the most powerful political entity in the Florida panhandle region and the southeastern extent of the classic Mississippian cultural tradition. The site features six platform mounds arranged around a central plaza, with Mound 3 producing one of the richest collections of Southeastern Ceremonial Complex copper objects ever excavated from a single context, including elaborately embossed copper plates depicting falcon warriors and other iconographic elements shared across the Mississippian world. Apalachee oral traditions, recorded after Spanish contact in the 16th and 17th centuries, preserve accounts of chiefs, ceremonies, and political structures that provide one of the rare windows into the living political culture of the Mississippian world from an Indigenous perspective." },

  { id:443, n:"Mississippian Culture — Ocmulgee", r:"Americas", t:"confirmed",
    s:900, e:1600, p:1000, lang:"muskogean-proto", gov:"chiefdom",
    d:"Ocmulgee Mounds in present-day Macon, Georgia, preserves one of the most complete sequences of human occupation in the American Southeast, with evidence of habitation from Paleo-Indian times through the historic Creek Nation period. The Mississippian occupation (~900–1150 CE) produced a major platform mound complex and the remarkable Earth Lodge — a circular council chamber dug into the ground with a moulded clay eagle platform for the chief's seat, still intact and one of the only Mississippian structures surviving in anything close to its original form. The site's long occupation sequence makes it uniquely valuable for understanding the transitions between pre-Mississippian Woodland cultures, the Mississippian fluorescence, and the historic period Muscogee (Creek) people who claim cultural continuity with the site's builders. The Muscogee Nation has been actively involved in site management and interpretation, representing one of the more successful examples of Indigenous-federal collaboration in American archaeology." },

  { id:444, n:"Etruscan Civilisation", r:"Europe", t:"confirmed",
    s:-800, e:-90, p:1000000, lang:"etruscan", gov:"city-state",
    d:"The Etruscan civilisation of central Italy (~800–90 BCE) was Rome's immediate predecessor and in many respects its cultural parent — the Romans adopted Etruscan architecture, religious divination (haruspicy), the toga, the fasces symbol of authority, gladiatorial combat, and crucial elements of their alphabet from the Etruscans. Yet the Etruscans remain deeply mysterious: their language, while written in a Greek-derived alphabet and partially readable, is a linguistic isolate with no known relatives, and the majority of Etruscan texts are short funerary inscriptions that reveal little of their literary or philosophical tradition. Etruscan women enjoyed a social freedom — attending banquets alongside men, owning property, being named in inscriptions by their own names — that shocked Greek and Roman observers and has no parallel in contemporary Mediterranean cultures. Their origins — indigenous Italian development, migration from Anatolia as Herodotus claimed, or Alpine descent as Livy suggested — was debated in antiquity and remains contested, with ancient DNA analysis suggesting Anatolian ancestry consistent with Neolithic farmer migration rather than a specific Bronze Age movement." },

  { id:445, n:"Minoan Civilisation (Neopalatial)", r:"Europe", t:"confirmed",
    s:-1700, e:-1450, p:100000, lang:"minoan-linear-a", gov:"palace-state",
    d:"The Neopalatial period of Minoan Crete (~1700–1450 BCE) represents the height of what is arguably Europe's first literate urban civilisation — the great palace complexes of Knossos, Phaistos, Malia, and Zakros, with their multi-storey architecture, indoor plumbing, sophisticated drainage, elaborate fresco programmes, and an administrative writing system (Linear A) still undeciphered. Minoan art — acrobats leaping over bulls, women in elaborate flounced skirts, dolphins swimming in blue seas — is among the most joyful and technically accomplished of any Bronze Age culture. The nature of Minoan governance remains debated: the absence of obvious fortifications and weapon imagery in early Minoan iconography led Arthur Evans to propose a peaceful 'thalassocracy,' while more recent scholarship identifies elite competition, redistributive economies, and increasing complexity. The civilisation's apparent collapse around 1450 BCE, coinciding approximately with the Thera eruption, connects Minoan Crete to debates about the Atlantis tradition that Plato recorded." },

  { id:446, n:"Scythian / Pazyryk Culture", r:"Asia", t:"confirmed",
    s:-600, e:-200, p:100000, lang:"scythian-iranian", gov:"tribal-confederation",
    d:"The Pazyryk culture of the Altai Mountains (~600–200 BCE) represents the easternmost and best-preserved branch of the broader Scythian world, with frozen burial mounds (kurgans) at altitude preserving organic materials — textiles, wood, leather, human bodies, horses — that survive nowhere else in the ancient world. The Pazyryk mummies include individuals with elaborate tattooing across their bodies — swirling animals, mythological creatures — executed with extraordinary skill and representing the earliest well-documented tradition of complex tattooing in human history. Persian-style pile carpets, Chinese silk, and Greek gold found in Pazyryk kurgans document trade connections spanning the entire Eurasian continent. The 'Ice Maiden' of Ukok, excavated by Russian archaeologist Natalia Polosmak in 1993 — a young woman buried with horses, elaborate grave goods, and extensive tattoos — became both a celebrated archaeological discovery and the subject of a political controversy when the Altai people sought repatriation of her remains." },

  { id:447, n:"Harappan Late Phase / Post-Urban", r:"Asia", t:"debated",
    s:-1900, e:-1300, p:500000, lang:"indus-unknown", gov:"unknown",
    d:"The Late Harappan or Post-Urban phase (~1900–1300 BCE) represents the poorly-understood dissolution and transformation of the Indus Valley Civilisation following the apparent abandonment of major urban centres like Mohenjo-daro and Harappa. Rather than a simple 'collapse,' current scholarship increasingly interprets this period as a spatial reorganisation — populations dispersing into smaller settlements across a wider area including the Gangetic plain, potentially carrying Harappan cultural elements that contributed to later Vedic and Early Historic Indian civilisation. The causes of urban abandonment remain debated: climate aridification and the drying of the Ghaggar-Hakra river system, internal social restructuring, or gradual demographic shift are all proposed. The continuity or discontinuity between Harappan and Vedic cultures — and the question of what the Harappan language was and whether it underlies the Dravidian languages of South India — are among the most consequential unresolved questions in South Asian prehistory." },

  { id:448, n:"Linear A / Minoan Script Culture", r:"Europe", t:"debated",
    s:-1800, e:-1450, p:0, lang:"minoan-linear-a", gov:"palace-state",
    d:"Linear A is the undeciphered writing system used in Minoan Crete from approximately 1800–1450 BCE — a syllabic script used for administrative records, religious inscriptions, and votive offerings across the Minoan palace system. Unlike its descendant Linear B (Mycenaean Greek, deciphered by Michael Ventris in 1952), Linear A has resisted all decipherment attempts because the underlying language remains unknown. Attempts to read Linear A using Linear B phonetic values — the 'same script, different language' approach — have produced suggestive but unconfirmed partial readings. The language appears unrelated to any known language family, making Minoan a linguistic isolate alongside Sumerian and Elamite. The content of Linear A tablets — predominantly administrative accounts of goods — offers little semantic context for phonetic reconstruction. Deciphering Linear A would unlock the only surviving records of Bronze Age Crete in the Minoans' own words, potentially transforming our understanding of Aegean prehistory and the origins of the Atlantis tradition." },

  { id:449, n:"Dilmun Civilisation", r:"Middle East", t:"debated",
    s:-3200, e:-600, p:100000, lang:"dilmunite-unknown", gov:"city-state",
    d:"Dilmun — identified with the island of Bahrain and the adjacent Arabian mainland — appears in Sumerian texts as a sacred land, a paradise where 'the raven does not croak' and death and disease are unknown, associated with the story of Ziusudra (the Sumerian flood hero) and with the divine smith Enki. Archaeological excavations on Bahrain have revealed a substantial Bronze Age civilisation, the Dilmun culture (~3200–600 BCE), serving as the critical entrepôt for trade between Mesopotamia and the Indus Valley — a function confirmed by Indus Valley seal types found in Dilmun contexts and Dilmun mention in Mesopotamian commercial records. The identification of Dilmun with paradise in Sumerian myth, combined with its real role as a wealthy trading hub between civilisations, raises the question of whether ancient paradise traditions encode memory of specific prosperous and peaceful places rather than purely mythological constructs. Jeffrey Rose has proposed that Dilmun mythology may encode memory of the Persian Gulf basin before its flooding ~8000 BCE." },

  { id:450, n:"Jiroft Civilisation", r:"Middle East", t:"debated",
    s:-3000, e:-2000, p:50000, lang:"proto-elamite-related", gov:"city-state",
    d:"The Jiroft civilisation of the Halil River basin in present-day Kerman Province, Iran, came to scholarly attention following massive illegal looting of its sites after floods exposed graves in 2001 — thousands of artefacts entered the international antiquities market before excavations began. Jiroft produced remarkable chlorite (soapstone) vessels carved with elaborate architectural and mythological scenes — buildings with distinctive arched windows, human and animal figures, and composite creatures — of a type found across a wide arc from Mesopotamia to Central Asia, suggesting a major production and export centre. Yousef Majidzadeh, the primary excavator, proposed identifying Jiroft with the legendary Sumerian city of Aratta, described in Sumerian texts as a distant, wealthy city of craftsmen. Mainstream archaeology treats this identification as unproven. The civilisation's script — if it had one — has not been identified, and its relationship to the Indus Valley, proto-Elamite, and Mesopotamian cultural spheres remains unclear." },

  { id:451, n:"Mississippian Culture — Town Creek", r:"Americas", t:"confirmed",
    s:1100, e:1400, p:500, lang:"siouan-proto", gov:"chiefdom",
    d:"Town Creek Indian Mound in present-day North Carolina represents the northeasternmost outpost of the Mississippian cultural tradition, a small but archaeologically significant platform mound complex that documents the extraordinary geographic reach of Mississippian religious and political ideas from their heartland in the Mississippi Valley to the eastern seaboard. The site features a single major platform mound, a reconstructed mortuary temple, and a palisaded precinct, occupied from approximately 1100–1400 CE by a people whose ceramic and architectural traditions show strong Mississippian influences despite the site's distance from the cultural core. Town Creek's excavation and reconstruction in the mid-20th century was one of North Carolina's first major state archaeological projects. Its existence at this geographic extreme raises questions about the mechanisms by which Mississippian cultural packages spread — whether through migration, elite emulation, religious conversion, or trade network adoption." },

  { id:452, n:"Mycenaean Civilisation (Extended)", r:"Europe", t:"confirmed",
    s:-1600, e:-1100, p:500000, lang:"mycenaean-greek", gov:"palace-state",
    d:"The Mycenaean civilisation of mainland Greece (~1600–1100 BCE) was the first Greek-speaking literate culture, operating palace bureaucracies recorded in Linear B — the earliest surviving written Greek, deciphered by Michael Ventris in 1952 — from great citadels at Mycenae, Tiryns, Pylos, and Thebes. The Mycenaeans were active warriors and traders across the eastern Mediterranean, almost certainly the Greeks described in Egyptian records as the Ekwesh, and their expeditionary culture may underlie the historical kernel of the Trojan War tradition. The Mycenaean palaces collapsed catastrophically around 1200–1150 BCE as part of the broader Late Bronze Age Collapse that destroyed or severely damaged nearly every complex society from Greece to Mesopotamia. The causes — climate drought, internal revolt, earthquake, the Sea Peoples, or systemic trade network failure — remain actively debated, and the collapse represents one of history's most dramatic civilisational discontinuities, inaugurating a Greek Dark Age of 400 years." },

  { id:453, n:"Göbekli Tepe / Karahan Tepe Network", r:"Middle East", t:"debated",
    s:-10000, e:-8000, p:5000, lang:"unknown", gov:"unknown",
    d:"The broader Taş Tepeler (Stone Hills) network of which Göbekli Tepe is the most famous site encompasses at least a dozen major enclosure complexes in the Şanlıurfa region of southeastern Turkey, all dating to the Pre-Pottery Neolithic A and B periods (~10000–8000 BCE). Karahan Tepe, now under systematic excavation, appears to rival or exceed Göbekli Tepe in size and complexity, with anthropomorphic pillars of a different and arguably more sophisticated style. The emerging picture is not of a single extraordinary site but of an entire regional tradition of monumental enclosure-building by late hunter-gatherer populations across a landscape of perhaps 200km. Andrew Collins argues in Göbekli Tepe: Genesis of the Gods (2014) that the network's Cygnus astronomical alignments and sculptural programmes encode a coherent cosmology potentially transmitted to later Mesopotamian and Egyptian religious traditions. The full extent of this network — and the population it implies — continues to expand with each new survey season, consistently exceeding prior expectations." },

  { id:454, n:"Indus Valley — Rakhigarhi", r:"Asia", t:"confirmed",
    s:-2800, e:-1900, p:80000, lang:"indus-unknown", gov:"city-state",
    d:"Rakhigarhi in present-day Haryana, India, is now recognised as the largest known site of the Indus Valley Civilisation — larger than Mohenjo-daro — covering an estimated 550 hectares, though less than 10% has been excavated. Its location in the now-dry Ghaggar-Hakra river basin places it at the heart of the debate about whether this river system is the Vedic Sarasvati, a question with profound implications for the dating of Vedic culture and its relationship to the Harappan civilisation. Ancient DNA analysis of Rakhigarhi skeletal material, published in 2019 by Vasant Shinde and colleagues, found no steppe ancestry in the Harappan genome — directly challenging the Aryan Migration Theory in its strongest form and supporting an indigenous origin for Harappan populations. The paper generated intense scientific and political controversy in India. Rakhigarhi's scale suggests it may have been the administrative capital of the Harappan civilisation, though without decipherment of the Indus script this remains speculative." },

  { id:455, n:"Mississippian Culture — Shiloh", r:"Americas", t:"confirmed",
    s:1000, e:1450, p:2000, lang:"muskogean-proto", gov:"chiefdom",
    d:"Shiloh Indian Mounds in present-day Tennessee, overlooking the Tennessee River, is a significant Mississippian centre whose platform mounds and residential areas were partially obscured and preserved by their location on what became the Shiloh Civil War battlefield — one of the bloodiest engagements of the American Civil War, fought in April 1862. The juxtaposition of a pre-Columbian Native American town site and one of the defining battles of 19th-century American history at the same location creates a layered landscape of historical significance rarely paralleled in the American Southeast. Archaeological work at Shiloh has been constrained by its battlefield preservation status, leaving much of the Mississippian occupation unexcavated. What has been investigated confirms a typical Mississippian town plan with platform mounds, plaza, and residential areas, occupied from approximately 1000–1450 CE." },

  { id:456, n:"Urartian Kingdom", r:"Middle East", t:"confirmed",
    s:-860, e:-585, p:300000, lang:"urartian", gov:"monarchy",
    d:"The Kingdom of Urartu (~860–585 BCE), centred around Lake Van in present-day eastern Turkey and Armenia, was the major rival of the Assyrian Empire for dominance of the ancient Near East and one of the most technically accomplished metalworking cultures of the Iron Age. Urartian bronze cauldrons, helmets, and shields — decorated with intricate animal friezes — were traded or captured across the Mediterranean world and influenced Greek, Etruscan, and Phrygian metalwork. The Urartians built extraordinary citadels on near-vertical rock faces, irrigated mountain valleys with canals and aqueducts, and maintained a cuneiform writing system closely related to Hurrian. The biblical 'Mountains of Ararat' where Noah's Ark came to rest are the mountains of Urartu — the country itself is preserved in the toponym. Urartu's collapse, coinciding with the fall of Assyria and the arrival of Scythian and Cimmerian raiders, ended one of antiquity's most remarkable mountain civilisations." },

  { id:457, n:"Mississippian Culture — Moundville Phase II", r:"Americas", t:"confirmed",
    s:1300, e:1500, p:1000, lang:"muskogean", gov:"ceremonial-centre",
    d:"The Phase II occupation of Moundville (~1300–1500 CE) represents a fascinating transformation: the site's population apparently largely departed to surrounding smaller villages, while Moundville itself became primarily a mortuary and ceremonial precinct — a city of the dead rather than the living. This reorganisation, documented through decades of excavation by the University of Alabama, challenges simple models of Mississippian decline and suggests instead a deliberate ceremonial restructuring in which Moundville's symbolic power was maintained and perhaps amplified even as its residential population contracted. The quality and quantity of mortuary goods during this phase actually increases, suggesting that Moundville's role as a regional religious centre intensified even as it depopulated. This pattern — urban contraction combined with intensified ceremonialism — may offer a model for understanding similar transformations at other Mississippian sites and raises broader questions about what 'abandonment' actually means in the context of sacred landscapes." },

  { id:458, n:"Tartessian Civilisation", r:"Europe", t:"debated",
    s:-900, e:-500, p:200000, lang:"tartessian", gov:"monarchy",
    d:"Tartessos — a civilisation or kingdom of the southwestern Iberian Peninsula (present-day Andalusia and Portugal) known from Greek and Phoenician written sources and from a corpus of inscriptions in an undeciphered script — is one of the most tantalising and poorly understood cultures of the ancient western Mediterranean. Greek sources describe Tartessos as a wealthy kingdom controlling metal trade routes — silver, tin, copper — and as a far western land at or near the Pillars of Hercules. Richard Freund and colleagues have proposed the Doñana marshes of southwestern Spain as the location of Atlantis, identifying Tartessos with Plato's sunken civilisation. Sergio Frau controversially proposed placing the Pillars of Hercules at the Strait of Sicily rather than Gibraltar, which would make Sardinia a candidate for Atlantis rather than any Atlantic location. The Tartessian script remains undeciphered, making it alongside Linear A and the Indus script one of the three major undeciphered ancient writing systems of the Old World. What would finding a Tartessian bilingual inscription change about our understanding of Atlantic prehistory?" },

  { id:459, n:"Ancient Astronaut Hypothesis", r:"Middle East", t:"theorized",
    s:-450000, e:-10000, p:0, lang:"unknown", gov:"unknown",
    d:"The Ancient Astronaut Hypothesis — systematically proposed by Erich von Däniken in Chariots of the Gods (1968) and subsequently extended by Zecharia Sitchin, Robert Temple, and others — holds that extraterrestrial beings visited Earth in prehistoric or ancient times and that their presence explains features of ancient cultures that proponents argue cannot be accounted for by human capability alone: the precision engineering of the Giza pyramids, the Nazca lines, the megalithic structures of Puma Punku, Olmec colossal heads, and the Anunnaki of Sumerian mythology. Mainstream archaeology and physics reject the hypothesis on multiple grounds: the claimed engineering impossibilities are demonstrably achievable with ancient technology; the interpretation of ancient iconography as depicting spacecraft or astronauts is culturally anachronistic; and the hypothesis implicitly denies the ingenuity and capability of ancient non-Western peoples. The hypothesis nonetheless has extraordinary popular reach and persistently shapes public engagement with ancient history. Its cultural significance — as a symptom of what it says about modern assumptions regarding ancient human capability — is itself worthy of serious analysis." },

  { id:460, n:"Younger Dryas Megaflood Network", r:"Americas", t:"theorized",
    s:-12800, e:-11500, p:0, lang:"unknown", gov:"unknown",
    d:"The network of catastrophic megafloods associated with the Younger Dryas Boundary event (~12,800–11,500 BCE) — including the Missoula Megafloods of the Pacific Northwest, the Lake Agassiz outburst floods into the North Atlantic, and possible Gulf of Mexico flood pulses — represents the largest freshwater flood events in the last 100,000 years of Earth history, reshaping continents and almost certainly triggering the Younger Dryas cooling through disruption of Atlantic thermohaline circulation. Randall Carlson's geological fieldwork across the Channeled Scablands of Washington State has documented flood features — gravel bars the size of hills, dry falls, coulees — of a scale that requires floodwaters of almost incomprehensible volume. The relevance to ancient history is direct: these floods drowned the coastal and riverine zones where any pre-Younger Dryas complex culture would most likely have been located, explaining the absence of physical evidence that mainstream archaeology uses to reject the pre-Flood civilisation hypothesis. Graham Hancock's thesis and Carlson's geology are intellectually interdependent in this specific respect." },
  // END PHASE 5aa
];
