// ════════════════════════════════════════════════════════════════════════════
// PHASE 5ac — APPEND TO data.js
// Civilizations 491–520
// ════════════════════════════════════════════════════════════════════════════
//
// INSTRUCTIONS (owner):
//   1. Open your local data.js
//   2. Find the very last closing  ];  at the bottom
//   3. Replace that  ];  with a comma, then paste ALL lines below
//      (these entries already end with the correct closing bracket)
//
// ════════════════════════════════════════════════════════════════════════════

// ── PHASE 5ac — Civilizations 491–520 ─────────────────────────────────────
// Append to CIVS array in data.js — APPEND-ONLY

  { id:491, n:"Mississippian Culture — Shiloh Phase II", r:"Americas", t:"confirmed",
    s:1200, e:1450, p:3000, lang:"muskogean-proto", gov:"chiefdom",
    d:"The later Shiloh phase occupation in the Tennessee River valley represents the development of a more complex regional Mississippian polity drawing together communities across the Tennessee Valley into a tribute-paying hierarchy. Archaeological evidence from the Shiloh site complex and its satellite communities documents the redistribution of prestige goods — shell gorgets, copper plates, ceramic vessels in distinctive Mississippian styles — across a network of smaller sites dependent on the platform mound centre. The Tennessee Valley's position as a corridor between the Mississippian heartland of the central Mississippi Valley and the Appalachian Highlands gave Shiloh and related sites a strategic role in channelling exchange between these different environmental and cultural zones. The gradual contraction and eventual abandonment of the Shiloh complex mirrors the broader pattern of Mississippian reorganisation in the 14th and 15th centuries." },

  { id:492, n:"Solutrean Culture", r:"Europe", t:"confirmed",
    s:-22000, e:-17000, p:5000, lang:"unknown-upper-palaeolithic", gov:"band",
    d:"The Solutrean culture of southwestern Europe (~22,000–17,000 BCE) represents one of the most technically sophisticated flint-knapping traditions in the entire Palaeolithic record — their pressure-flaked bifacial points, laurel leaves, and shouldered points achieved thinness and symmetry that modern knappers struggle to replicate, and their finest pieces appear to be non-functional prestige objects rather than tools. The Solutreans also produced some of the earliest known needle technology, enabling tailored clothing essential for survival in glacial maximum Europe. Dennis Stanford and Bruce Bradley's controversial Solutrean Hypothesis (Across Atlantic Ice, 2012) proposes that Solutrean people crossed the glacial North Atlantic on the ice edge — using skin boats and surviving on marine mammals as Inuit do — and became ancestral to the Clovis culture of North America, explaining perceived similarities in flint-knapping technology across the Atlantic. Mainstream archaeology firmly rejects this hypothesis based on chronology, genetics, and the absence of diagnostic Solutrean tools in any North American context, but the debate continues." },

  { id:493, n:"Bell Beaker Culture", r:"Europe", t:"confirmed",
    s:-2800, e:-1800, p:200000, lang:"proto-celtic-italic", gov:"chiefdom",
    d:"The Bell Beaker culture (~2800–1800 BCE), named for its distinctive inverted-bell-shaped pottery found across western and central Europe from Ireland to Hungary, represents one of the most significant cultural and demographic episodes in European prehistory. Ancient DNA analysis published in 2018 by David Reich's group revealed that the spread of Bell Beaker culture into Britain was accompanied by a near-total replacement of the existing Neolithic farming population — up to 90% genetic turnover within a few centuries, one of the most dramatic demographic replacements in European prehistory. These Bell Beaker migrants brought Yamnaya-related steppe ancestry into western Europe, and their descendants are the primary ancestors of Bronze Age and subsequently Iron Age Celtic-speaking populations. Stonehenge's final construction phase is associated with Bell Beaker culture, and the famous Amesbury Archer — buried near Stonehenge with the richest Bell Beaker assemblage known in Britain — originated from the Alpine region of Europe based on isotope analysis." },

  { id:494, n:"Corded Ware Culture", r:"Europe", t:"confirmed",
    s:-3000, e:-2350, p:500000, lang:"proto-indo-european", gov:"chiefdom",
    d:"The Corded Ware culture (~3000–2350 BCE) of central and northern Europe represents the primary vector by which Yamnaya steppe ancestry and proto-Indo-European language spread into the heart of Europe, transforming the genetic and linguistic landscape of the continent within just a few centuries. Named for the characteristic cord-impressed decoration on its pottery, Corded Ware society appears to have been patrilineal, highly mobile, and organised around herding and raiding rather than settled agriculture — a social structure that ancient DNA confirms spread at the expense of the existing European Neolithic farmer populations. The speed and scale of the Corded Ware expansion — from the steppe to Scandinavia within perhaps 300 years — implies a process more like conquest or plague-facilitated replacement than peaceful cultural diffusion. Corded Ware is the ancestor culture of the Battle Axe and Single Grave traditions and ultimately of the Bronze Age cultures from which Celtic, Germanic, Baltic, and Slavic language families emerged." },

  { id:495, n:"Linear Pottery Culture / LBK", r:"Europe", t:"confirmed",
    s:-5500, e:-4500, p:100000, lang:"proto-european-farmer", gov:"village",
    d:"The Linear Pottery Culture (Linearbandkeramik or LBK, ~5500–4500 BCE) was the first farming culture of central Europe, spreading from Hungary to the Paris Basin within a few centuries as Anatolian-origin Neolithic farmers moved northwest across the continent. The LBK expansion replaced or marginalised the existing Mesolithic hunter-gatherer populations of central Europe with remarkable speed, establishing a template of village-based cereal agriculture that would define European subsistence for millennia. LBK settlements were characterised by large longhouses — up to 45 metres long — housing extended family units, arranged in small villages near light loess soils suitable for simple hoe agriculture. The Talheim Death Pit (~5000 BCE) and the Asparn-Schletz massacre site document episodes of mass violence in the LBK world, suggesting that the Neolithic transition in Europe was accompanied by significant inter-group conflict. The LBK represents the first wave of a demographic transformation of Europe that ancient DNA has now documented in extraordinary detail." },

  { id:496, n:"Funnel Beaker Culture / TRB", r:"Europe", t:"confirmed",
    s:-4000, e:-2800, p:150000, lang:"proto-european-farmer", gov:"chiefdom",
    d:"The Funnel Beaker culture (Trichterbecherkultur or TRB, ~4000–2800 BCE) of northern Europe was the first megalith-building culture of Scandinavia and the North European Plain, responsible for the construction of thousands of dolmens, passage graves, and long barrows across Denmark, Sweden, northern Germany, the Netherlands, and Poland. The TRB people were Anatolian-origin farmers who had developed the social organisation and religious motivation to invest enormous collective labour in stone monuments for the dead, several centuries before the better-known megalithic traditions of western Europe reached their peak. TRB society appears to have been relatively egalitarian compared to the later Corded Ware and Bell Beaker cultures that replaced it, with collective burial monuments suggesting communal rather than individual elite commemoration. The TRB is also associated with the earliest evidence of dairying in northern Europe, a dietary adaptation that required genetic evolution of lactase persistence in adult populations." },

  { id:497, n:"Beaker People — British Isles", r:"Europe", t:"confirmed",
    s:-2500, e:-1800, p:100000, lang:"proto-celtic", gov:"chiefdom",
    d:"The Bell Beaker migration into the British Isles (~2500–1800 BCE) produced one of the most thoroughly documented demographic replacements in ancient DNA science — within 400–500 years of the Beaker people's arrival, approximately 90% of the genetic ancestry of the British Neolithic population had been replaced by steppe-related ancestry brought by Beaker migrants, making it the most complete population replacement in British prehistory. The famous Amesbury Archer, buried ~2300 BCE near Stonehenge with gold hair ornaments, copper knives, and the largest known Bell Beaker grave assemblage in Britain, had grown up in the Alpine region of central Europe based on his tooth enamel isotopes — a long-distance migrant who died in southern England. The Beaker people in Britain are associated with the final construction phases of Stonehenge, the introduction of copper and then bronze metallurgy, and the cultural transition from the Neolithic to the Bronze Age. Their descendants include the Bronze Age and Iron Age populations from whom modern British and Irish people are substantially descended." },

  { id:498, n:"Catalhoyuk — Extended Analysis", r:"Middle East", t:"confirmed",
    s:-7500, e:-5700, p:8000, lang:"unknown-anatolian", gov:"egalitarian-town",
    d:"Çatalhöyük in present-day Turkey (~7500–5700 BCE) remains one of the most extensively studied Neolithic sites in the world, and four decades of excavation have produced a picture of an urban-scale community of extraordinary social complexity whose governance system defies conventional categories. The settlement had no streets — houses were accessed through roof openings — and no evidence of central authority, temples, or palaces. Burials under house floors show no consistent pattern of individual wealth accumulation. Ian Hodder's decades-long excavation project has documented radical equality between male and female skeletal remains in terms of diet, health, and mobility. The community's wall paintings — leopards, hunting scenes, vultures consuming headless human figures — and its apparent obsession with cattle skulls plastered into walls suggest a rich symbolic and ritual life. Çatalhöyük challenges the assumption that urban scale requires hierarchical governance, and its egalitarian social organisation has become a touchstone in debates about alternative models of human social organisation." },

  { id:499, n:"Uruk Expansion", r:"Middle East", t:"confirmed",
    s:-4000, e:-3100, p:50000, lang:"sumerian", gov:"city-state",
    d:"The Uruk Expansion (~4000–3100 BCE) represents the first known case of economic and cultural globalisation in human history — a period in which the city of Uruk in southern Mesopotamia grew to an estimated 40,000–80,000 inhabitants and simultaneously established trading colonies, outposts, and culturally influenced settlements across an enormous arc from the Nile Delta to the Iranian plateau and the Caucasus. Uruk-period material culture — distinctive bevelled-rim bowls (probably ration vessels for dependent labourers), cylinder seals, and administrative clay tokens — appears simultaneously across this entire zone. Whether this represents Uruk colonisation, trade diaspora, cultural emulation, or some combination remains debated. Crucially, the Uruk period also sees the emergence of the earliest known writing — proto-cuneiform clay tablets recording administrative transactions — making Uruk's expansion the context in which humanity's most transformative intellectual technology was invented. The collapse of the Uruk network around 3100 BCE, as peripheral regions abandoned Uruk material culture, remains one of the first documented cases of a globalised system's breakdown." },

  { id:500, n:"Proto-Indo-European Homeland", r:"Europe", t:"debated",
    s:-4500, e:-2500, p:100000, lang:"proto-indo-european", gov:"chiefdom",
    d:"Proto-Indo-European (PIE) — the reconstructed ancestor language of a family spoken today by over three billion people from Iceland to Sri Lanka, including English, Russian, Persian, Hindi, Greek, Latin, and hundreds of other languages — must have had a homeland from which it spread. The Pontic-Caspian steppe hypothesis, championed by Marija Gimbutas and now strongly supported by ancient DNA evidence from David Reich's group, identifies the Yamnaya culture of the Ukrainian and Russian steppes (~3500–2500 BCE) as the primary PIE-speaking population whose expansion carried the language family across Eurasia. A competing Anatolian hypothesis, associated with Colin Renfrew, proposes that PIE spread with the Neolithic farming expansion from Anatolia ~7000 BCE, a timeline now largely contradicted by ancient DNA evidence. A minority Armenian Highland hypothesis places the PIE homeland in eastern Anatolia or the South Caucasus. The identification of the PIE homeland is one of historical linguistics' most consequential questions, with implications for the origins of European, Iranian, and South Asian civilisations." },

  { id:501, n:"Mississippian Culture — Moundville Hinterland", r:"Americas", t:"confirmed",
    s:1100, e:1400, p:10000, lang:"muskogean", gov:"chiefdom",
    d:"The Moundville hinterland — the dispersed rural communities of the Black Warrior Valley that surrounded and supported the Moundville paramount centre — provides essential context for understanding how the Moundville chiefdom actually functioned as a political and economic system. Survey archaeology across the valley has documented a landscape densely settled with farmsteads, hamlets, and small mound centres at distances of a few kilometres from each other, all oriented toward Moundville as the redistributive and ceremonial capital. The agricultural surplus generated by these hinterland communities — primarily maize, supplemented by hunting, fishing, and gathered resources — supported the non-agricultural specialist population at Moundville itself and the labour needed for ongoing mound construction and maintenance. The spatial relationship between Moundville and its hinterland is one of the most thoroughly documented examples of the economic geography of a Mississippian chiefdom anywhere in the archaeological record, providing a model applicable to interpreting other, less-surveyed Mississippian regional systems." },

  { id:502, n:"Yamnaya — Afanasievo Branch", r:"Asia", t:"confirmed",
    s:-3300, e:-2500, p:20000, lang:"proto-tocharian", gov:"pastoral-nomad",
    d:"The Afanasievo culture of the Altai Mountains and the Minusinsk Basin in southern Siberia (~3300–2500 BCE) represents the easternmost early branch of the Yamnaya expansion, now confirmed by ancient DNA to be descended from Pontic-Caspian steppe populations. The Afanasievo people were the first steppe pastoralists to reach Central Asia and the Altai, and their descendants almost certainly include the proto-Tocharian speakers whose language — the easternmost branch of the Indo-European family — eventually appeared in the Tarim Basin 1,000 years later. The migration of Afanasievo people thousands of kilometres east of the Yamnaya heartland, at dates contemporary with the main Yamnaya westward expansion into Europe, demonstrates that the steppe pastoral economy was expanding in multiple directions simultaneously. The Afanasievo culture thus connects the Yamnaya revolution directly to the Tocharian mummies of the Tarim Basin, bridging what previously appeared to be an inexplicable gap in the distribution of early Indo-European languages." },

  { id:503, n:"Andronovo Culture", r:"Asia", t:"confirmed",
    s:-2000, e:-900, p:200000, lang:"proto-iranian", gov:"pastoral-nomad",
    d:"The Andronovo cultural horizon (~2000–900 BCE) of the Eurasian steppe from the Urals to the Yenisei River represents the stage in steppe prehistory when the synthesis of horse riding, chariot technology, and bronze metallurgy produced a mobile warrior culture capable of transforming the ancient world at scale. Andronovo-related populations are the primary ancestors of the Indo-Iranian language branch — the languages that became Vedic Sanskrit, Avestan, Persian, and their descendants spoken today from Iran to Bangladesh. The migration of Andronovo-related peoples into the Indian subcontinent as the Vedic culture (~1500 BCE) and into Iran as the Avestan Iranians represents the final stage of the Indo-European expansion, completing a transformation that had begun on the Pontic steppe two millennia earlier. The Sintashta culture, an early Andronovo variant of the southern Urals (~2100–1800 BCE), is specifically identified as the origin of the spoke-wheeled war chariot — one of antiquity's most consequential military technologies." },

  { id:504, n:"Harappan — Mohenjo-daro", r:"Asia", t:"confirmed",
    s:-2600, e:-1900, p:40000, lang:"indus-unknown", gov:"city-state",
    d:"Mohenjo-daro ('Mound of the Dead') on the Indus River in present-day Pakistan was one of the two great urban centres of the Harappan civilisation — a planned city of extraordinary sophistication covering at least 250 hectares, with a population estimated at 40,000–50,000 people, laid out on a grid of streets with standardised brick dimensions, covered sewerage channels running beneath the streets, and public buildings including the famous Great Bath — a large watertight tank that may have served ritual purification functions. The city was rebuilt at least nine times on the same grid plan after periodic flooding, demonstrating a remarkable civic commitment to urban continuity. Mohenjo-daro shows no evidence of palaces, temples, or royal burials in the Egyptian or Mesopotamian sense, suggesting either a different model of governance — possibly theocratic, mercantile, or collective — or that such structures remain unexcavated. The city's abandonment around 1900 BCE and the skeletal remains found in its streets have generated persistent speculation about a catastrophic ending, though mainstream archaeology points to gradual decline linked to river course changes and climate aridification." },

  { id:505, n:"Harappan — Harappa City", r:"Asia", t:"confirmed",
    s:-2600, e:-1900, p:23000, lang:"indus-unknown", gov:"city-state",
    d:"Harappa, the type site of the Indus Valley Civilisation in present-day Pakistan's Punjab province, gave its name to the entire civilisation and was the first Harappan site excavated scientifically, beginning with John Marshall's work in the 1920s. The city featured massive granaries, standardised brick construction, a citadel mound, and the full repertoire of Harappan urban infrastructure — covered drains, street grids, and standardised weights and measures used across the entire civilisation's trade network. Harappa is particularly significant for the discovery of the earliest Harappan script examples and for evidence of craft specialisation in bead-making, shell-working, and metalworking. The site's earlier phases, now called the Ravi phase (~3300–2800 BCE), preserve evidence of the gradual development of Harappan urbanism from its village antecedents, providing crucial insight into how one of the ancient world's most remarkable city-building traditions actually emerged. Unfortunately, significant portions of Harappa were destroyed by 19th-century brick robbers who used the ancient fired bricks as ballast for the Lahore-Multan railway." },

  { id:506, n:"Etruscan — Villanovan Phase", r:"Europe", t:"confirmed",
    s:-900, e:-700, p:200000, lang:"proto-etruscan", gov:"chiefdom",
    d:"The Villanovan culture (~900–700 BCE) of central Italy represents the formative phase of Etruscan civilisation, the period in which the distinctive cultural and genetic population that would become the Etruscans developed its characteristic traditions of cremation burial in biconical urns, iron and bronze metallurgy, and the dense settlement of the Tyrrhenian coastal zone of Italy. The Villanovans were part of the broader Urnfield cultural horizon of late Bronze Age and early Iron Age Europe, but developed rapidly toward urban complexity as they exploited the rich metal ores of the Colline Metallifere in Tuscany. Ancient DNA from Villanovan and Etruscan cemetery sites, published in 2023, confirmed that the Etruscans were genetically similar to other European Iron Age populations with no significant Anatolian-specific ancestry, definitively settling the long-running debate about Etruscan origins in favour of an indigenous Italian rather than Anatolian or Alpine origin — contra Herodotus's famous claim that the Etruscans migrated from Lydia." },

  { id:507, n:"Thracian Civilisation", r:"Europe", t:"confirmed",
    s:-700, e:46, p:2000000, lang:"thracian", gov:"tribal-confederation",
    d:"The Thracians of the eastern Balkans (~700 BCE–46 CE) were one of the most populous and militarily powerful peoples of the ancient Aegean world — Herodotus called them the most numerous people in the world after the Indians — yet they left no literate culture and are known primarily through Greek and Roman sources and through the extraordinary richness of their burial traditions. Thracian royal tombs, particularly those of the Odrysian Kingdom in present-day Bulgaria, contain some of the finest gold and silver metalwork of the ancient world: the Panagyurishte treasure, the Rogozen treasure, and the Valchitran treasure demonstrate a toreutic tradition of extraordinary skill. The Thracians gave the ancient world the god Dionysus — almost certainly a Thracian deity adopted by the Greeks — and the legendary musician Orpheus, whose mythological tradition preserves Thracian religious concepts of the soul's journey. Spartacus, leader of the most significant slave rebellion in Roman history, was Thracian." },

  { id:508, n:"Illyrian Civilisation", r:"Europe", t:"confirmed",
    s:-800, e:9, p:1000000, lang:"illyrian", gov:"tribal-confederation",
    d:"The Illyrians of the western Balkans (~800 BCE–9 CE) were a group of Indo-European-speaking tribal peoples occupying the coastal and mountainous regions of present-day Albania, Croatia, Bosnia, and Montenegro, whose collective designation 'Illyrian' is a Greek and Roman simplification of what were likely dozens of distinct tribal identities. The Illyrian tribes periodically unified under powerful leaders — most notably Queen Teuta of the Ardiaei, whose naval power threatened Roman Adriatic trade and provoked the First Illyrian War (229 BCE) — demonstrating the capacity for large-scale political organisation when motivated by external pressure or strong leadership. The Illyrian language is a linguistic isolate within Indo-European whose only possible surviving descendant is Albanian, making the Albanians potentially the most direct descendants of any ancient Balkans population. The Roman conquest of Illyricum was completed by Augustus after the Pannonian revolt of 6–9 CE, but Illyrian cultural identity persisted under Roman rule." },

  { id:509, n:"Celtic La Tène Culture", r:"Europe", t:"confirmed",
    s:-450, e:-50, p:3000000, lang:"celtic", gov:"tribal-confederation",
    d:"The La Tène culture (~450–50 BCE) of central Europe represents the florescence of Celtic civilisation — the period in which the characteristic art style of swirling, interlaced, zoomorphic patterns that defines Celtic artistic identity reached its peak, and in which Celtic peoples expanded across an enormous arc from Ireland to Galatia in modern Turkey. La Tène Celts sacked Rome (~390 BCE), invaded Greece and plundered Delphi (~279 BCE), settled Galatia in central Anatolia, and established oppida — large fortified urban centres — across temperate Europe. The Druids, described by Julius Caesar and other Roman sources, constituted a pan-Celtic intellectual and religious elite who transmitted enormous bodies of learning, law, and genealogy entirely through oral tradition, deliberately refusing to commit knowledge to writing. The gradual Roman conquest of the Celtic world between 58 BCE and 43 CE, combined with Germanic pressure from the east, ended La Tène culture as a political force while its art traditions, languages, and mythological heritage survived in the Atlantic fringe — Ireland, Wales, Scotland, Brittany." },

  { id:510, n:"Mississippian Culture — Summerville", r:"Americas", t:"confirmed",
    s:1200, e:1550, p:2000, lang:"muskogean-proto", gov:"chiefdom",
    d:"The Summerville phase of the Tombigbee River valley in present-day Alabama and Mississippi represents a regional Mississippian tradition within the broader Moundville political sphere, documenting how Mississippian cultural and political systems were adapted to the specific environmental and demographic conditions of the Tombigbee drainage. Summerville phase sites cluster along the river's natural levees, exploiting the rich bottomland soils for maize agriculture while maintaining access to the river for transport and exchange. The ceramic tradition of the Summerville phase shows both local innovation and strong connections to Moundville's prestige goods network, indicating participation in the regional exchange system while maintaining a degree of local cultural distinctiveness. The phase's persistence into the early historic period connects it potentially to the Alabama and Choctaw peoples encountered by European colonists in the 17th century." },

  { id:511, n:"Mississippian Culture — Dallas Phase", r:"Americas", t:"confirmed",
    s:1300, e:1600, p:3000, lang:"muskogean-cherokee-proto", gov:"chiefdom",
    d:"The Dallas phase of the upper Tennessee Valley (~1300–1600 CE) was a major Mississippian regional tradition centred on sites including Hiwassee Island and Dallas, featuring platform mound complexes, a distinctive ceramic tradition, and participation in the Southeastern Ceremonial Complex exchange network. Dallas phase communities occupied the transitional zone between the Mississippian heartland to the west and the Appalachian Highlands to the east, a position that made them cultural intermediaries between the lowland Mississippian world and the upland communities of the Ridge and Valley province. The late survival of the Dallas phase into the 16th century means it was potentially encountered by the Hernando de Soto expedition of 1540, and some scholars have proposed connections between Dallas phase peoples and the ancestors of the historic Cherokee Nation, though this remains debated. The site of Toqua, a major Dallas phase centre, was excavated before its inundation by the Little Tennessee River reservoir in the 1970s." },

  { id:512, n:"Woodland Culture — Adena", r:"Americas", t:"confirmed",
    s:-1000, e:100, p:10000, lang:"various-eastern-woodlands", gov:"chiefdom",
    d:"The Adena culture (~1000 BCE–100 CE) of the Ohio Valley represents the first elaborated mound-building tradition of the Eastern Woodlands — the cultural foundation on which the later Hopewell Interaction Sphere was built. Adena burial mounds, typically circular and built over log-lined burial chambers, contain the earliest evidence of the exchange of exotic prestige goods across the Eastern Woodlands: copper from the Great Lakes, mica from the Appalachians, marine shell from the Gulf Coast. The Adena Great Serpent Mound in Ohio — a 411-metre effigy mound in the form of a coiling serpent, the largest known serpent effigy in the world — is the most spectacular surviving expression of Adena-related ceremonialism, though its precise dating and cultural attribution remain debated. Adena society was transitional between the fully nomadic Archaic hunter-gatherers that preceded it and the more sedentary, horticulturally-based Hopewell that followed, representing an intermediate stage of social complexity in which mound building and long-distance exchange emerged without fully sedentary agriculture." },

  { id:513, n:"Choctaw Nation — Prehistoric Phase", r:"Americas", t:"confirmed",
    s:1000, e:1540, p:20000, lang:"choctaw-muskogean", gov:"chiefdom",
    d:"The prehistoric Choctaw and their direct ancestors in present-day Mississippi and Alabama represent one of the best-documented cases of cultural continuity between the Mississippian archaeological tradition and a historically known Indigenous nation. The Choctaw oral tradition of Nanih Waiya — a sacred mound that the Choctaw identify as their place of emergence and which corresponds to a genuine Mississippian platform mound in Winston County, Mississippi — provides a rare Indigenous perspective on the meaning and significance of the mound-building tradition that archaeology documents from the outside. The Choctaw Nation at European contact was one of the largest Indigenous nations east of the Mississippi, with a complex matrilineal clan system, town-based political organisation, and a diplomatic sophistication that allowed them to navigate European colonial competition for several centuries. Their forced removal to Oklahoma on the Trail of Tears in the 1830s is one of the most consequential acts of American ethnic cleansing." },

  { id:514, n:"Muscogee / Creek Nation — Prehistoric Phase", r:"Americas", t:"confirmed",
    s:900, e:1540, p:20000, lang:"muskogean", gov:"confederacy",
    d:"The prehistoric Muscogee (Creek) and their Mississippian-tradition ancestors in present-day Georgia and Alabama represent another well-documented case of continuity between the Mississippian archaeological record and a historically documented Indigenous confederacy. The Creek Confederacy that emerged in the historic period was a sophisticated political organisation uniting dozens of town-based communities under a loose federal structure — a model that some scholars have argued influenced American founding fathers' thinking about confederate governance. The green corn ceremony (Busk), documented in detail in colonial-era sources, preserves elements of Mississippian ceremonialism including sacred fires, ritual purification, and communal feasting that illuminate the living meaning of practices archaeologically documented at earlier sites. The Creek Confederacy's forced removal to Oklahoma in the 1830s, alongside the Choctaw, Cherokee, Chickasaw, and Seminole — the Five Civilised Tribes — ended their presence in their ancestral homeland." },

  { id:515, n:"Haida Civilisation", r:"Americas", t:"confirmed",
    s:-1000, e:1850, p:20000, lang:"haida", gov:"chiefdom",
    d:"The Haida people of Haida Gwaii (the Queen Charlotte Islands) and southern Alaska developed one of the most visually distinctive and artistically accomplished civilisations in the pre-Columbian Americas — a maritime culture of extraordinary sophistication whose monumental totem poles, carved canoes up to 20 metres long, and massive cedar plank houses represent a tradition of woodworking and visual art with no parallel on the Pacific coast. Haida society was organised around matrilineal clans (Eagles and Ravens) with a complex system of hereditary chiefly titles, wealth redistribution through potlatch ceremonies, and a prestige economy based on control of maritime resources — salmon, halibut, sea mammals — and the production of luxury goods including Argillite carvings and Chilkat blankets traded across the Northwest Coast. The devastating smallpox epidemic of 1862 killed approximately 70% of the Haida population within a few years, reducing a thriving civilisation of perhaps 20,000 people to fewer than 600, one of the most catastrophic disease-driven population collapses in recorded history." },

  { id:516, n:"Tlingit Civilisation", r:"Americas", t:"confirmed",
    s:-1000, e:1900, p:15000, lang:"tlingit", gov:"chiefdom",
    d:"The Tlingit people of coastal Alaska and northern British Columbia built one of the most complex non-agricultural societies in human history — a maritime civilisation whose social organisation, material culture, and ceremonial life rival in sophistication those of many agricultural states. Tlingit society was organised around matrilineal moieties (Raven and Eagle/Wolf), with elaborate clan systems, hereditary titles, and a potlatch ceremonial economy in which wealth was accumulated and then redistributed in competitive feasts that established and confirmed social rank. Tlingit warfare was conducted with sophisticated discipline and equipment — wooden armour, copper-bladed weapons, and coordinated tactical manoeuvres — and the Tlingit successfully resisted Russian colonial encroachment for decades, inflicting a major defeat on Russian forces at the Battle of Sitka in 1802. Their oral literature — particularly the Raven cycle of transformation stories — is among the richest in North America, encoding cosmological, historical, and moral knowledge across hundreds of generations of oral transmission." },

  { id:517, n:"Olmec — San Lorenzo Phase", r:"Americas", t:"confirmed",
    s:-1500, e:-900, p:10000, lang:"proto-mixe-zoquean", gov:"chiefdom",
    d:"San Lorenzo (~1500–900 BCE) was the first great Olmec centre and the earliest complex society in Mesoamerica, built on an artificially modified plateau in the lowland jungle of Veracruz, Mexico. San Lorenzo produced the first colossal heads — massive basalt portraits of individual rulers weighing up to 28 tonnes, transported from quarries 60–80km away with no wheeled vehicles or draft animals — establishing the Olmec tradition of monumental portraiture that would influence Mesoamerican art for two millennia. San Lorenzo was deliberately destroyed around 900 BCE — the colossal heads and other monuments were mutilated and buried in a pattern suggesting deliberate termination ritual — before the emergence of La Venta as the successor Olmec centre. Ivan Van Sertima's controversial They Came Before Columbus (1976) argued that the distinctly African-featured appearance of the colossal heads evidences trans-Atlantic contact with West Africa, a thesis rejected by mainstream archaeology but persistently discussed in alternative scholarship." },

  { id:518, n:"Olmec — La Venta Phase", r:"Americas", t:"confirmed",
    s:-900, e:-400, p:18000, lang:"proto-mixe-zoquean", gov:"chiefdom",
    d:"La Venta (~900–400 BCE) succeeded San Lorenzo as the dominant Olmec centre and produced the most elaborate known Olmec ceremonial complex — a series of mounds, plazas, and buried offerings arranged along a precise north-south axis that may encode astronomical alignments. The Great Pyramid of La Venta, a 34-metre earthen mound built in a fluted cone shape, is one of the earliest large-scale pyramidal constructions in the Americas. La Venta's massive buried offerings — mosaic pavements of serpentine blocks forming abstract jaguar masks, caches of jade axes arranged in geometric patterns — demonstrate a ritual life of extraordinary complexity and the long-distance sourcing of prestige materials from across Mesoamerica. The Olmec civilisation is often described as the 'mother culture' of Mesoamerica for the role of Olmec iconographic, calendrical, and political traditions in the development of later cultures including the Zapotec, Maya, and Aztec — though the precise mechanisms of this influence remain debated." },

  { id:519, n:"Chichimec / Northern Mexico Cultures", r:"Americas", t:"confirmed",
    s:-500, e:1600, p:500000, lang:"various-uto-aztecan", gov:"tribal-confederation",
    d:"The Chichimec peoples of northern Mexico — a collective designation used by Mesoamerican agriculturalists for the diverse hunter-gatherer and semi-nomadic cultures of the arid Gran Chichimeca region — maintained their independence against both the Aztec Empire and Spanish colonial power for longer than virtually any other Indigenous group in the Americas, conducting the Chichimec War (~1550–1590 CE) against Spanish forces in one of the longest armed conflicts of the colonial period. The term 'Chichimec' (roughly 'lineage of dogs' in Nahuatl) was a pejorative applied by sedentary Mesoamerican peoples to their mobile northern neighbours, obscuring the cultural diversity of what were actually dozens of distinct linguistic and cultural groups including the Zacatec, Guachichil, Pame, and Jonaz. The Chichimec peoples' resistance to both agricultural state expansion and European colonialism — enabled by their mobility, knowledge of the arid landscape, and social structures that did not depend on fixed settlements — represents a case study in the resilience of non-sedentary cultures against expansionist states." },

  { id:520, n:"Mississippian Culture — Hiwassee Island", r:"Americas", t:"confirmed",
    s:1300, e:1600, p:1500, lang:"muskogean-cherokee-proto", gov:"chiefdom",
    d:"Hiwassee Island at the confluence of the Hiwassee and Tennessee Rivers in present-day Tennessee was a major Dallas phase Mississippian centre whose excavation by the Tennessee Valley Authority in the 1930s — before the site was partially inundated by Chickamauga reservoir — produced one of the most complete stratigraphic records of a Mississippian platform mound site ever documented, revealing multiple construction stages and associated structures spanning the full Dallas phase occupation. The meticulous excavation records from Hiwassee Island, published by Thomas Lewis and Madeline Kneberg in 1946, remain a foundational reference for southeastern archaeology. The site's position at the confluence of two major rivers made it a strategic node in the exchange and communication networks of the upper Tennessee Valley Mississippian world. Its Dallas phase material culture and geographic position in the southern Appalachian foothills place it in the zone most likely connected to the emergence of the historic Cherokee Nation." },
  // END PHASE 5ac
];
