// ════════════════════════════════════════════════════════════════════════════
// PHASE 5af — APPEND TO data.js
// Civilizations 581–610
// ════════════════════════════════════════════════════════════════════════════
//
// INSTRUCTIONS (owner):
//   1. Open your local data.js
//   2. Find the very last closing  ];  at the bottom
//   3. Replace that  ];  with a comma, then paste ALL lines below
//      (these entries already end with the correct closing bracket)
//
// ════════════════════════════════════════════════════════════════════════════

// ── PHASE 5af — Civilizations 581–610 ─────────────────────────────────────
// Append to CIVS array in data.js — APPEND-ONLY

  { id:581, n:"Kingdom of Aksum — Axumite Christianity", r:"Africa", t:"confirmed",
    s:330, e:650, p:200000, lang:"ge-ez", gov:"theocracy",
    d:"The Aksumite Christianisation under King Ezana (~330 CE) represents one of the earliest and most consequential adoptions of Christianity by a major state, predating even the Roman Empire's full institutional Christianisation. Frumentius, a Syrian-born Christian shipwrecked on the Red Sea coast, became tutor to the Aksumite royal family and was eventually consecrated as the first Bishop of Aksum by Athanasius of Alexandria — establishing the direct connection between the Ethiopian church and the Alexandrian patriarchate that defines Ethiopian Orthodox Christianity to this day. Aksumite Christian material culture — churches, crosses, illustrated manuscripts, and the architectural tradition of monolithic rock-hewn churches that would reach its apex at Lalibela centuries later — represents a unique African Christian civilisational tradition entirely independent of European influence. The Aksumite church's claim to house the original Ark of the Covenant, in the Chapel of the Tablet in Aksum, is the centrepiece of Ethiopian Christian identity and a claim taken seriously by some scholars including Graham Hancock, whose The Sign and the Seal (1992) investigated it at length." },

  { id:582, n:"Nok — Iron Age West Africa", r:"Africa", t:"confirmed",
    s:-1000, e:300, p:100000, lang:"benue-congo-proto", gov:"chiefdom",
    d:"The Nok culture's iron smelting tradition, dating to at least 500 BCE and possibly earlier, places West Africa among the earliest iron-using regions in the world and raises enduring questions about whether African iron metallurgy was independently invented or diffused from North Africa or the Middle East. The evidence for independent invention has strengthened with archaeological dating: some Nok iron-smelting contexts predate the period when technology transfer from the north would have been feasible, and the African smelting techniques differ substantially from Near Eastern and European traditions in ways suggesting separate development. The social implications of early iron production in the Nok context — specialised craft production, controlled access to transformative technology, and the prestige associated with metalworking — may explain aspects of the social hierarchy visible in the Nok terracotta tradition, where some figures wear elaborate jewellery and headdresses suggesting elite status. West African iron technology subsequently spread southward with Bantu expansion, transforming agricultural and material capabilities across sub-Saharan Africa." },

  { id:583, n:"Bantu Expansion", r:"Africa", t:"confirmed",
    s:-3000, e:1000, p:500000, lang:"proto-bantu", gov:"chiefdom",
    d:"The Bantu Expansion — the spread of Bantu-speaking agricultural peoples from a homeland in the Cameroon-Nigeria borderland across virtually all of sub-Saharan Africa over approximately 4,000 years — is one of the most consequential demographic and cultural events in human history, transforming the linguistic, genetic, and agricultural landscape of an entire continent. From perhaps 3000 BCE, Bantu-speaking farmers spread eastward through the Congo Basin and southward along both the eastern and western coasts of Africa, carrying with them iron technology, cattle herding, yam and later sorghum agriculture, and characteristic pottery traditions. The Bantu Expansion displaced, absorbed, or marginalised the previous inhabitants of eastern and southern Africa — primarily Khoisan-speaking hunter-gatherer peoples — whose genetic signature survives in isolated pockets and in the admixed ancestry of some Bantu populations. The speed and geographic scale of the Bantu Expansion, reconstructed through linguistics, genetics, and archaeology, makes it the largest pre-modern expansion of a human cultural tradition across a single landmass." },

  { id:584, n:"Aksumite — Lalibela Rock Churches", r:"Africa", t:"confirmed",
    s:1181, e:1221, p:20000, lang:"ge-ez", gov:"theocracy",
    d:"The eleven monolithic rock-hewn churches of Lalibela in the Ethiopian Highlands — carved entirely from living volcanic rock during the reign of King Lalibela of the Zagwe dynasty (~1181–1221 CE) — constitute one of the most extraordinary architectural achievements in human history: not buildings constructed from quarried stone, but entire churches excavated from the bedrock, complete with windows, columns, drainage systems, and elaborate decorative carving, while remaining connected at their base to the surrounding rock. The largest, Bete Medhane Alem, is the largest monolithic rock-hewn church in the world, approximately 33 metres long and 11 metres tall. Ethiopian Christian tradition attributes the construction to divine intervention — angels working alongside human labourers at night to complete what the workforce could not achieve by day. Alternative scholars including Graham Hancock have examined the Lalibela churches in the context of possible Templar Knight involvement during the Crusader period. UNESCO designated the churches a World Heritage Site in 1978; they remain active places of worship." },

  { id:585, n:"Kingdom of Mali — Sundiata Period", r:"Africa", t:"confirmed",
    s:1235, e:1400, p:4000000, lang:"mande", gov:"empire",
    d:"The Kingdom of Mali under Sundiata Keita (~1235 CE onwards) and his successors — particularly the legendary Mansa Musa, whose 1324–1325 CE pilgrimage to Mecca with a retinue of 60,000 people and 80 camels carrying gold dust so disrupted the Egyptian and Mediterranean gold markets that it caused inflation lasting a decade — was the wealthiest state in the medieval world, controlling the trans-Saharan gold and salt trade routes that were the financial arteries of the medieval Mediterranean economy. The Malian capital of Niani and the great trading cities of Timbuktu and Djenné were centres of Islamic scholarship whose libraries and universities — particularly the Sankore Madrasah at Timbuktu — attracted scholars from across the Muslim world. The Epic of Sundiata, the foundational oral epic of the Mande peoples, is one of Africa's greatest literary works, transmitted across centuries by professional bards (griots) in a tradition that continues to the present. Mansa Musa remains by most estimates the wealthiest individual in recorded human history in inflation-adjusted terms." },

  { id:586, n:"Songhai Empire — Askia Period", r:"Africa", t:"confirmed",
    s:1464, e:1591, p:5000000, lang:"songhay", gov:"empire",
    d:"The Songhai Empire under Askia Muhammad I (~1493–1528 CE) reached its territorial and cultural apex — controlling the largest territory of any West African empire, stretching 2,000km along the Niger River and encompassing the great cities of Timbuktu, Djenné, and Gao. Askia Muhammad, who seized power from Sunni Ali's dynasty and legitimised his rule through a famous pilgrimage to Mecca in 1497, was a devout Muslim who established Islamic law courts, standardised weights and measures, and patronised Islamic scholarship on a scale that made Timbuktu one of the foremost intellectual centres of the 15th–16th century world. The Sankore University at its height may have enrolled 25,000 students and housed a library of one million manuscripts — more books than Europe's largest libraries of the same period. The Songhai Empire was destroyed by a Moroccan invasion in 1591, whose gunpowder weapons proved decisive against Songhai's larger but conventionally armed forces — one of the clearest early examples of gunpowder technology determining the outcome of sub-Saharan African history." },

  { id:587, n:"Kanem-Bornu Empire", r:"Africa", t:"confirmed",
    s:700, e:1900, p:1000000, lang:"kanuri", gov:"empire",
    d:"The Kanem-Bornu Empire (~700–1900 CE) centred on Lake Chad in present-day northeastern Nigeria, Chad, and Niger was one of the longest-lived political entities in African history — a state that maintained recognisable political continuity for approximately 1,200 years across enormous environmental, religious, and demographic changes. The empire's extraordinary longevity reflected both its strategic position controlling trans-Saharan trade routes between the Mediterranean and sub-Saharan Africa and the ideological legitimacy provided by its Islamic rulership from approximately the 11th century CE. The Mai (king) of Kanem-Bornu was regarded as a divine or semi-divine figure whose physical health was believed to determine the prosperity of the kingdom. At its height in the 16th century under Idris Alooma, the empire modernised its military with firearms obtained from the Ottoman Empire, demonstrating sophisticated engagement with the wider Islamic world's military technology. The empire's final collapse in the late 19th century resulted from the devastation of the Sudanese warlord Rabih az-Zubayr and subsequent French colonial conquest." },

  { id:588, n:"Great Zimbabwe — Mutapa State", r:"Africa", t:"confirmed",
    s:1420, e:1760, p:100000, lang:"shona-karanga", gov:"monarchy",
    d:"The Mutapa State (Mwenemutapa, ~1420–1760 CE) was the political successor to the Great Zimbabwe kingdom, relocating the centre of power northward to the Zambezi Valley as the southern gold trade routes shifted and as Great Zimbabwe's local resources became depleted. The Mutapa rulers maintained the Great Zimbabwe tradition of divine kingship and gold-based wealth while developing new trade relationships — first with the Swahili coast and subsequently, fatally, with the Portuguese who arrived in the Indian Ocean in 1498. Portuguese attempts to control the Mutapa's gold trade through military pressure and diplomatic manipulation progressively undermined the state's political independence throughout the 16th and 17th centuries. A Portuguese-backed succession dispute in 1629 installed a puppet ruler who ceded nominal sovereignty, though effective Mutapa political authority persisted in reduced form until the late 17th century. The Mutapa State represents the final phase of the Great Zimbabwe civilisational tradition before its absorption into the colonial economy of the Indian Ocean world." },

  { id:589, n:"Kuba Kingdom", r:"Africa", t:"confirmed",
    s:1625, e:1900, p:150000, lang:"kuba-bantu", gov:"monarchy",
    d:"The Kuba Kingdom of the Kasai region in present-day Democratic Republic of Congo (~1625–1900 CE) was renowned across central Africa for the extraordinary quality of its textile art — raffia cloth cut-pile velvets, geometric patterned prestige textiles, and embroidered garments of dazzling complexity that were among the most technically sophisticated textiles produced anywhere in the pre-industrial world. The Kuba political system was notable for its degree of constitutional complexity: a king (nyim) whose power was substantially checked by councils of nobles and age-grade associations, creating a more balanced power structure than the absolute monarchies of many neighbouring states. Kuba oral tradition credits the culture hero Shyaam aMbul aNgoong with introducing embroidery, new crops, and a new political order from outside — some scholars have speculated about connections to the broader Atlantic world through trade networks. Kuba art, particularly the carved wooden prestige objects and ndop royal portrait statues, was among the first African art to be seriously studied by Western artists and directly influenced Picasso and the Cubist movement." },

  { id:590, n:"Luba Empire", r:"Africa", t:"confirmed",
    s:1585, e:1889, p:2000000, lang:"luba-bantu", gov:"empire",
    d:"The Luba Empire (~1585–1889 CE) of the central Congo region in present-day southeastern DRC was a sophisticated state whose distinctive contribution to African political history was a system of memory devices — the lukasa memory board and the associated mbudye memory specialists — that encoded dynastic history, territorial geography, and political knowledge in material objects read by trained specialists, functioning as an alternative to writing for the storage and transmission of complex political information. Luba royal art — particularly the seated female figures that served as supports for headrests and other prestige objects — is among the most celebrated in African art history for its formal elegance and the sophistication with which it encoded cosmological and political meaning. The Luba system of sacred kingship, in which the king's body was a vessel for divine power that sustained the kingdom's prosperity, was the model that spread across a wide arc of central African states through the diaspora of Luba royals establishing new kingdoms in neighbouring territories." },

  { id:591, n:"Mississippian — Kolomoki", r:"Americas", t:"confirmed",
    s:350, e:750, p:2000, lang:"muskogean-proto", gov:"chiefdom",
    d:"Kolomoki Mounds in present-day Georgia is one of the oldest and largest platform mound complexes in the American Southeast — built and occupied primarily during the Swift Creek and Weeden Island cultural periods (~350–750 CE), several centuries before the full Mississippian tradition emerged. At its peak, Kolomoki may have been the largest site in the entire eastern United States, with a population of 2,000 or more and a mound complex including the seventh-largest platform mound in North America. The site's early date makes it a crucial link in the developmental sequence from Hopewell to Mississippian, demonstrating the continuity of mound-building and ceremonial traditions in the Southeast across a period of apparent cultural transition. The presence at Kolomoki of Swift Creek and Weeden Island ceramic traditions alongside evidence of long-distance exchange documents the persistence of Hopewell-derived ceremonial practices into the late Woodland period in the deep Southeast, bridging the gap between Hopewell and Mississippian." },

  { id:592, n:"Anatolian Neolithic — Göbekli Tepe Predecessors", r:"Middle East", t:"debated",
    s:-12000, e:-9600, p:1000, lang:"unknown-epipaleolithic", gov:"band",
    d:"The cultural tradition that produced Göbekli Tepe did not emerge from nothing — the Epipalaeolithic and Pre-Pottery Neolithic A cultures of the Fertile Crescent from which the Göbekli builders emerged had their own long development of symbolic behaviour, communal gathering, and increasingly complex social organisation stretching back to at least 12,000 BCE. Sites like Körtik Tepe, Nevalı Çori, and Jerf el Ahmar document the gradual intensification of sedentism, symbolic art, and communal architecture in the pre-Göbekli Fertile Crescent, providing the cultural substrate from which the extraordinary florescence at Göbekli Tepe and the Taş Tepeler network grew. The question of what specifically triggered the explosive complexity of Göbekli Tepe — whether a sudden social reorganisation, a specific environmental stress, a religious innovation, or the arrival of a distinct population with different cultural capacities — remains at the heart of debates about the Neolithic transition. Alternative scholars including Andrew Collins and Graham Hancock argue that the continuity model is insufficient to explain Göbekli Tepe's sophistication and propose a more ancient cultural ancestry." },

  { id:593, n:"Cucuteni-Trypillia — Mega-Site Network", r:"Europe", t:"confirmed",
    s:-4100, e:-3500, p:15000, lang:"unknown-european-farmer", gov:"egalitarian-town",
    d:"The Cucuteni-Trypillia mega-sites of the Ukrainian-Moldovan-Romanian borderland reached their maximum extent and complexity between approximately 4100–3500 BCE, with sites like Talianky covering up to 450 hectares and possibly housing 15,000–20,000 people — a population comparable to contemporary Uruk in Mesopotamia but organised on entirely different principles, with no evidence of central authority, temples, or elite quarters. The mega-sites appear to have been organised as concentric rings of houses, each ring containing hundreds of identical or near-identical structures suggesting a deliberate egalitarian spatial programme. The regular burning and rebuilding of the entire settlement every 60–80 years — with the new settlement built on the same plan adjacent to or overlapping the ash and debris of the previous — represents a cultural practice with no known parallel anywhere in the world. Whether the burning was ritual, practical, demographic, or epidemiological in motivation remains undetermined. The Trypillia mega-sites may represent the largest human settlements of the 4th millennium BCE — a fact that challenges Mesopotamia-centric accounts of early urbanism." },

  { id:594, n:"Linear A — Minoan Administrative System", r:"Europe", t:"confirmed",
    s:-1800, e:-1450, p:50000, lang:"minoan-linear-a", gov:"palace-state",
    d:"The Linear A administrative system of Minoan Crete — the bureaucratic infrastructure of the palace economies centred on Knossos, Phaistos, Malia, and Zakros — represents one of the earliest known examples of literacy being used primarily as an instrument of economic administration rather than royal propaganda or religious text, a pattern that also characterises the earliest Mesopotamian cuneiform and Egyptian hieratic writing. The Linear A tablets, found primarily in palace contexts, record transactions of agricultural commodities — olive oil, grain, wine, figs, wool — using a numerical and metrological system partially but not fully reconstructable from the related Linear B. The palace economy operated as a redistributive system: agricultural surplus flowed into the palace as taxation or tribute and was redistributed as rations, festival goods, and craft materials. The destruction of the palace archives in the fires that ended each palace period means we have only a fraction of the original Linear A corpus, making decipherment statistically challenging in addition to linguistically so." },

  { id:595, n:"Mycenaean — Palace of Nestor", r:"Europe", t:"confirmed",
    s:-1600, e:-1180, p:10000, lang:"mycenaean-greek", gov:"palace-state",
    d:"The Palace of Nestor at Pylos in present-day southwestern Greece is the best-preserved Mycenaean palace on the Greek mainland and the site that yielded the largest archive of Linear B tablets in Greece — approximately 1,000 tablets recording the palace's administrative activities in the final months before its destruction around 1180 BCE. The Linear B archive from Pylos, deciphered by Michael Ventris in 1952, provides the most detailed picture of Mycenaean palace economy available: rosters of rowers being mustered, allocations of bronze for spearheads, rations for women textile workers, land tenure records, and — hauntingly — preparations for coastal defence against an unnamed threat in what appear to be the palace's final administrative records before destruction by fire. The Homeric tradition identifies Pylos as the kingdom of the wise king Nestor, one of the Greek heroes at Troy, and the palace's evident sophistication and the wealth of its Linear B archive give some historical plausibility to the Homeric tradition." },

  { id:596, n:"Ugarit — Bronze Age Cosmopolitan City", r:"Middle East", t:"confirmed",
    s:-2000, e:-1185, p:8000, lang:"ugaritic", gov:"city-state",
    d:"Ugarit on the Syrian coast was the most cosmopolitan city of the Late Bronze Age international system — a port city whose archives document diplomatic correspondence in Akkadian with Egypt, Hatti, Cyprus, and the Aegean; commercial transactions in multiple languages; and literature in the Ugaritic language itself written in an alphabetic cuneiform script that is one of the direct ancestors of the Phoenician and therefore all subsequent alphabets. The Ugaritic mythological texts — the Baal Cycle, the Epic of Aqhat, the Legend of Keret — are among the oldest examples of Canaanite literature and provide essential background for understanding the development of Hebrew biblical literature, with clear parallels in narrative themes, poetic formulae, and divine epithets between Ugaritic and biblical texts. Ugarit was destroyed around 1185 BCE by the Sea Peoples in what appears to have been a sudden and complete catastrophe — the final Ugaritic letters, found in a kiln still awaiting firing, describe a terrifying enemy attack and desperate requests for military aid that never arrived." },

  { id:597, n:"Elam / Proto-Elamite Civilisation", r:"Middle East", t:"confirmed",
    s:-3200, e:-539, p:200000, lang:"elamite", gov:"empire",
    d:"The Elamite civilisation of southwestern Iran (~3200–539 BCE) was one of the oldest and most persistent civilisations of the ancient Near East — a contemporary and frequent rival of Sumer and Akkad, whose capital Susa was among the earliest urban centres in the world and whose Proto-Elamite script (~3200–2900 BCE) is one of the earliest writing systems known, predating or contemporaneous with proto-cuneiform but still undeciphered. The Elamites sacked Ur and captured the famous Law Code of Hammurabi (which is why it was found at Susa rather than Babylon). At the height of Elamite power under the Middle Elamite period (~1500–1100 BCE), the kingdom rivalled Assyria and Babylonia as a major Near Eastern power. Elam was eventually absorbed into the Achaemenid Persian Empire under Cyrus the Great in 539 BCE, but Elamite administrative traditions, the Elamite language (used in official Achaemenid inscriptions alongside Old Persian and Akkadian), and Elamite cultural influences profoundly shaped Persian civilisation." },

  { id:598, n:"Mittani Kingdom", r:"Middle East", t:"confirmed",
    s:-1500, e:-1270, p:300000, lang:"hurrian", gov:"empire",
    d:"The Mittani Kingdom (~1500–1270 BCE) of northern Syria and Mesopotamia was a major Bronze Age power whose ruling elite spoke Indo-Aryan — a language closely related to Vedic Sanskrit — while the general population spoke Hurrian, creating one of the most linguistically distinctive ancient Near Eastern states. Mittani horse-training documents written in Hurrian include technical terminology in Indo-Aryan (including names for horse gaits that are cognate with Sanskrit terms), providing crucial linguistic evidence for the eastward spread of Indo-European speakers into the Near East during the second millennium BCE. The Mittani kingdom played a critical diplomatic role in the Late Bronze Age international system, maintaining formal treaty relationships with Egypt and competing with the Hittites for Syrian hegemony. Mittani's diplomatic correspondence in the Amarna Letters documents the sophisticated protocol of Bronze Age international relations — royal marriages, gift exchanges, and carefully calibrated language of brotherhood between great kings. The kingdom was destroyed by a combination of Hittite military pressure and Assyrian expansion around 1270 BCE." },

  { id:599, n:"Kassite Babylonia", r:"Middle East", t:"confirmed",
    s:-1595, e:-1155, p:500000, lang:"kassite-akkadian", gov:"empire",
    d:"The Kassite dynasty of Babylonia (~1595–1155 BCE) — a people of uncertain origin who seized control of Babylon following the Hittite raid that ended the Old Babylonian period — ruled Mesopotamia for over 400 years, making it the longest-ruling dynasty in Babylonian history. The Kassites adopted Babylonian culture, language, and religion with remarkable completeness, becoming the custodians of the Mesopotamian literary and scholarly tradition and the patrons under whose rule many foundational Babylonian literary and scientific texts reached their canonical forms, including the Gilgamesh epic's standard version. Kassite Babylonia was a major player in the Late Bronze Age international system, documented extensively in the Amarna Letters exchanging diplomatic correspondence with Egypt, Assyria, and the Mittani. The Kassites introduced the kudurru — carved stone boundary markers documenting land grants, whose complex iconographic programmes document Babylonian religious art at a moment of considerable elaboration. Their dynasty ended when the Elamites raided Babylon and carried off the statue of Marduk." },

  { id:600, n:"Civilisation 600 — Milestone Entry", r:"Middle East", t:"confirmed",
    s:-3500, e:-2900, p:50000, lang:"proto-cuneiform", gov:"city-state",
    d:"The Early Dynastic period city-states of southern Mesopotamia (~3500–2900 BCE) represent the transition from the Uruk proto-urban phase to the full elaboration of Sumerian civilisation — the period in which writing developed from proto-cuneiform administrative notation toward a fully expressive system capable of recording literature, law, and mythology; in which cylinder seals became the primary medium of personal and institutional identification; and in which the distinctive Sumerian city-state system — each city ruled by a patron deity through a human king or priest-king — crystallised as the political template that would define Mesopotamian civilisation for two millennia. Cities including Ur, Eridu, Nippur, Lagash, Girsu, Umma, and Shuruppak developed their characteristic monumental architecture — the ziggurat temple platform — and the economic institutions of temple and palace that organised Sumerian society. The earliest known author in human history — Enheduanna, high priestess of the moon god Nanna at Ur and daughter of Sargon of Akkad (~2285–2250 BCE) — composed hymns in this tradition that established literary conventions still recognisable in subsequent millennia." },

  { id:601, n:"Phoenician — Tyre and Sidon", r:"Middle East", t:"confirmed",
    s:-1200, e:-64, p:200000, lang:"phoenician", gov:"city-state",
    d:"The Phoenician city-states of Tyre and Sidon on the Lebanese coast (~1200–64 BCE) were the great maritime trading civilisation of the Iron Age Mediterranean — the people who, through their trading diaspora stretching from Cyprus to Spain, spread the Phoenician alphabetic writing system that became the ancestor of virtually every alphabet in use today. Phoenician craftsmen worked for Solomon's Temple in Jerusalem; Phoenician purple dye (from Murex sea snails) was the most expensive textile colourant in the ancient world, costing more per gram than gold; and Phoenician merchant ships navigated the entire Mediterranean and Atlantic coasts. The Phoenician colony of Carthage, founded by Tyre around 814 BCE, became one of the great powers of the ancient Mediterranean. Herodotus records a Phoenician circumnavigation of Africa commissioned by the Egyptian pharaoh Necho II around 600 BCE — sailing from the Red Sea southward and returning through the Pillars of Hercules — a feat not confirmed by other sources but whose navigational plausibility modern scholars increasingly accept." },

  { id:602, n:"Neo-Assyrian Empire", r:"Middle East", t:"confirmed",
    s:-911, e:-609, p:5000000, lang:"assyrian-akkadian", gov:"empire",
    d:"The Neo-Assyrian Empire (~911–609 BCE) was the first true world empire in history — a military and administrative system that at its height controlled territory from Egypt and the Levant to Persia and Anatolia, sustaining dominance over this vast area through a combination of extreme military violence (mass deportations, deliberate psychological terror, and the destruction of cities), sophisticated provincial administration, and a professional standing army equipped with iron weapons, siege engines, and cavalry. Assyrian royal inscriptions document military campaigns with meticulous pride in destruction; the Assyrian kings competed to record the numbers of enemies killed, cities razed, and populations deported. The library of Ashurbanipal at Nineveh — over 30,000 clay tablet fragments — was the first systematically collected library in history, preserving the Gilgamesh epic, astronomical observations, medical texts, and religious literature that would otherwise have been lost. The empire's sudden collapse in 609 BCE, when a Babylonian-Median coalition destroyed Nineveh, shocked the ancient world — the apparent invincibility of Assyria had been the defining geopolitical fact of the Near East for three centuries." },

  { id:603, n:"Median Empire", r:"Middle East", t:"confirmed",
    s:-678, e:-549, p:2000000, lang:"old-iranian-median", gov:"empire",
    d:"The Median Empire (~678–549 BCE) was the first Iranian empire, the power that destroyed the Assyrian Empire in alliance with Babylonia and briefly controlled an enormous territory from Anatolia to Central Asia before being absorbed by the Persian Achaemenid dynasty of Cyrus the Great. The Medes are mentioned extensively in Assyrian records as a troublesome northeastern people from the Zagros Mountains, gradually coalescing into a unified kingdom under Deioces and subsequently expanding dramatically under Cyaxares, who coordinated the assault on Nineveh. The Median cultural and political contribution to subsequent Iranian history is poorly documented because no Median texts survive — our knowledge comes entirely from Assyrian, Babylonian, and Greek sources. Whether the Medes were the primary cultural predecessors of the Achaemenid Persians or whether the cultural continuity between Medes and Persians has been overstated by ancient sources (particularly Herodotus) who often conflate the two remains debated by ancient Iranian historians." },

  { id:604, n:"Palmyrene Empire", r:"Middle East", t:"confirmed",
    s:260, e:273, p:1000000, lang:"palmyrene-aramaic", gov:"empire",
    d:"The Palmyrene Empire (~260–273 CE) was one of history's most remarkable short-lived states — an empire carved from the Roman world by the regent Zenobia, ruling on behalf of her son Vaballathus after the assassination of her husband Odaenathus, that at its brief peak controlled Egypt, the Levant, Anatolia, and much of the Roman East. Zenobia — described by Roman sources as beautiful, scholarly, and militarily brilliant — declared independence from Rome, adopted the title Queen of Queens, and styled her court on a synthesis of Roman, Greek, and Egyptian traditions, corresponding with the philosopher Cassius Longinus and presenting herself as a descendant of Cleopatra. The Emperor Aurelian defeated Zenobia's forces in 272 CE and captured Palmyra; Zenobia herself was taken to Rome, where according to some sources she lived out her days in comfortable exile. Palmyra, her capital in the Syrian desert, was one of antiquity's most magnificent cities — its colonnaded street, temples, and funerary towers documented a unique synthesis of Roman and Near Eastern architectural traditions largely destroyed by ISIS in 2015." },

  { id:605, n:"Kingdom of Pontus", r:"Middle East", t:"confirmed",
    s:-302, e:-64, p:1000000, lang:"greek-iranian", gov:"monarchy",
    d:"The Kingdom of Pontus (~302–64 BCE) on the southern coast of the Black Sea was a Hellenistic state founded by an Iranian dynasty that embraced Greek culture while maintaining connections to Persian royal traditions, producing in Mithridates VI Eupator one of Rome's most formidable and persistent opponents. Mithridates VI — known as Mithridates the Great — fought three wars against Rome across 25 years (~88–63 BCE), at one point controlling most of the Black Sea coast, Anatolia, and Greece, and allegedly building immunity to poisons by consuming small doses daily (giving rise to the word 'mithridate' for an antidote). His pharmacological interests — documented in ancient sources as extensive practical experimentation — made him a foundational figure in the history of toxicology. The Kingdom of Pontus represents the complex cultural synthesis of the Hellenistic world: Greek language and artistic traditions grafted onto Iranian royal ideology in a Black Sea maritime environment, producing a distinctive civilisational hybrid that challenged Rome's eastern expansion for a generation." },

  { id:606, n:"Bactrian / Greco-Bactrian Kingdom", r:"Asia", t:"confirmed",
    s:-256, e:-125, p:1000000, lang:"greek-bactrian", gov:"monarchy",
    d:"The Greco-Bactrian Kingdom (~256–125 BCE) of present-day Afghanistan and Central Asia was the easternmost expression of Hellenistic civilisation — a Greek state founded by Diodotus I, a governor of Alexander's eastern territories who declared independence from the Seleucid Empire, maintaining Greek language, art, and political forms at the far eastern end of the Greek cultural world for over a century. Greco-Bactrian coinage is among the finest portrait coinage of the ancient world, with individual kings depicted with a psychological realism exceeding anything produced in the contemporary Hellenistic west. The kingdom's successor state, the Indo-Greek Kingdom, extended Greek rule into northwestern India, producing the remarkable Milindapanha — a philosophical dialogue between the Indo-Greek king Menander I and the Buddhist monk Nagasena that represents a genuine intellectual encounter between Greek philosophical tradition and Buddhist thought. Greco-Bactrian and Indo-Greek artistic traditions were a primary conduit through which Greek artistic conventions entered Buddhist art, giving rise to the Gandharan school in which the Buddha is first depicted in human form with distinctly Greek artistic characteristics." },

  { id:607, n:"Kushan Empire", r:"Asia", t:"confirmed",
    s:30, e:375, p:5000000, lang:"bactrian-greek", gov:"empire",
    d:"The Kushan Empire (~30–375 CE) of Central Asia and northwestern India was a remarkable multi-cultural state that served as the primary conduit for the transmission of Buddhism from India to China along the Silk Road, while simultaneously maintaining a cosmopolitan court culture in which Greek, Iranian, Indian, and steppe traditions coexisted and synthesised. The Kushan king Kanishka I (~127–150 CE) convened the Fourth Buddhist Council and patronised a vast building programme of Buddhist stupas and monasteries across his empire, sponsoring the development of Mahayana Buddhist doctrine. Kushan art — particularly the Gandharan Buddhist sculpture tradition — synthesised Greek figure-drawing with Indian iconography to produce the first human representations of the Buddha, establishing conventions (the ushnisha cranial protuberance, the elongated earlobes, the dhyana mudra hand position) that spread with Buddhism across Asia and remain definitive of Buddhist art to the present. The Kushan Empire's position at the intersection of four major civilisational spheres — Roman, Parthian, Indian, and Chinese — made it the critical cultural hub of the first millennium CE Eurasian world." },

  { id:608, n:"Sogdian Letter Network", r:"Asia", t:"confirmed",
    s:300, e:800, p:50000, lang:"sogdian", gov:"merchant-diaspora",
    d:"The Sogdian merchant diaspora along the Silk Road — documented through the remarkable Ancient Sogdian Letters found near Dunhuang in 1907, dating to approximately 313 CE and representing the earliest surviving merchant correspondence from the Silk Road — maintained a commercial and cultural network of extraordinary geographic reach and sophistication. The letters, written on paper and apparently lost when the messenger carrying them was abandoned in the desert, discuss commercial transactions, family matters, political events (including references to a Xiongnu attack on Luoyang in 311 CE — the earliest known reference to this historically significant event), and the difficulties of long-distance communication. The Sogdian network operated through a diaspora model — Sogdian merchants established trading colonies at regular intervals along the Silk Road from Samarkand to the Chinese capital, maintaining cultural identity across generations while adapting to local conditions. Their script was adopted by the Uyghurs, whose script was adopted by the Mongols, whose script was adopted by the Manchus — making the Sogdian writing tradition one of the most consequential in Asian history." },

  { id:609, n:"Pala Empire", r:"Asia", t:"confirmed",
    s:750, e:1174, p:5000000, lang:"bengali-proto", gov:"empire",
    d:"The Pala Empire (~750–1174 CE) of Bengal and Bihar was the last great Buddhist dynasty of India — a powerful state that patronised the final flourishing of Indian Buddhist culture and the monastic university tradition at Nalanda and Vikramashila before the Muslim conquest of northern India ended Buddhism as a significant Indian religious force. The Nalanda university under Pala patronage was arguably the greatest educational institution of the ancient world, housing up to 10,000 students and 2,000 scholars from across Asia in a vast complex of monasteries, lecture halls, and libraries; the Chinese monk Xuanzang's 7th-century account describes its scale and intellectual vitality in detail. The Pala maritime connections with the Srivijaya Empire of Sumatra facilitated the spread of Mahayana Buddhism into Southeast Asia and subsequently to Japan via China. Pala bronzes — the classical medium of late Indian Buddhist sculpture — achieved a technical and aesthetic refinement that influenced Buddhist artistic traditions across Southeast Asia, Tibet, and East Asia." },

  { id:610, n:"Chola Empire — Maritime Phase", r:"Asia", t:"confirmed",
    s:985, e:1279, p:8000000, lang:"tamil", gov:"empire",
    d:"The Chola Empire of southern India under Rajaraja I and Rajendra I (~985–1279 CE) achieved the most ambitious maritime military projection in medieval Asian history — naval expeditions that raided the Srivijaya Empire in Sumatra, established diplomatic relations with China, and briefly controlled the Strait of Malacca, projecting Tamil Hindu culture across the Bay of Bengal. The Chola navy, operating thousands of kilometres from its base in Tamil Nadu, represented an unprecedented southern Indian military reach into Southeast Asia. On land, the Chola patronised an extraordinary florescence of Tamil literature, bronze casting, and temple architecture — the Brihadeeswarar Temple at Thanjavur, built by Rajaraja I and completed in 1010 CE, is a UNESCO World Heritage Site and one of the great achievements of Indian architectural history, with a vimana tower of 66 metres built entirely of granite. Chola bronze casting — particularly the Nataraja (Shiva as Lord of Dance) figure — achieved an artistic synthesis of cosmic symbolism and technical perfection that has become globally recognised as one of humanity's supreme sculptural achievements." },
  // END PHASE 5af
];
